### PR TITLE
fix: tabbing past contenteditable=false in containing focusscope

### LINKED ISSUE #7321: [RAC] Disabled DatePicker stops Tab focus moving forward when used inside Modal & Dialog
### Provide a general summary of the issue here

When having disabled DatePicker inside Modal Dialog with some focusable elements before and after it (e.g. TextFields) and you start Tabbing through the fields with keyboard, the focus won't move past the DatePicker.

### 🤔 Expected Behavior?

Keyboard focus should jump over the disabled DatePicker and continue normally to next focusable element.

### 😯 Current Behavior

Keyboard focus gets stuck to last focusable element before disabled DatePicker.

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

Try adding to DatePicker with isDisabled=true after the "Last name" TextField in this example: https://react-spectrum.adobe.com/react-aria/Modal.html#example

### Version

react-aria-components v1.4.1

### What browsers are you seeing the problem on?

Firefox, Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Windows 11

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by nwidynski**
Closes #7321 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

File: packages/@react-aria/spinbutton/src/useSpinButton.ts [hunk 1]
```diff
@@ -176,6 +176,7 @@ export function useSpinButton(
   return {
     spinButtonProps: {
       role: 'spinbutton',
+      tabIndex: isDisabled ? -1 : undefined,
```
Comment (snowystinger) [inline packages/@react-aria/spinbutton/src/useSpinButton.ts:179]: We can see here that a disabled spin button only has `aria-disabled`, not `disabled`

Is there a reason you chose to use tabIndex to solve this, rather than expand the definition of disabled in FocusScope?
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L270

I'll bring it up with the team to see if we have any preferences.

Comment (nwidynski) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:179]: Ah no, we can definitely use `disabled` here instead.

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:179]: ah, no, i meant in FocusScope adding `[aria-disabled]` next to `[disabled]`

Comment (nwidynski) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:179]: Not sure whether I like using aria semantics to change focus order to be honest, feels wrong.

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:179]: Sorry, just looked at this again more closely.
The issue is just that we're too accepting of `contenteditable` https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/focus/src/FocusScope.tsx#L283
useDateSegment disabled has it set to false, so it's not a focusable element

We should restrict FocusScope to be any content editable EXCLUDING false (since contenteditable can be a couple different values https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/contenteditable#value)

but we should be able to do the exclude query selector
`[editable]:not([editable^="false"])`

File: packages/@react-aria/focus/src/FocusScope.tsx [hunk 2]
```diff
@@ -280,7 +280,7 @@ const focusableElements = [
   'embed',
   'audio[controls]',
   'video[controls]',
-  '[contenteditable]'
+  '[contenteditable]:not([contenteditable^="false"])'
```
Comment (snowystinger) [inline packages/@react-aria/focus/src/FocusScope.tsx:283]: Thanks for the quick fix. Would you mind adding a test?

**Review by snowystinger — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]
