### PR TITLE
fix(#3559): DatePicker: aria-live not announcing new months

### LINKED ISSUE #3559: DatePicker: aria-live not announcing new months
# 🐛 Bug Report 

When clicking on the right or left chevron, there should be an aria-live announcement that announces the newly displayed month. This is what occurs when opening the picker initially and reading through; however after you close and reopen the picker, it will no longer announce when clicking the chevron. If you remount the component by refreshing the page,  it will work again as described above. I'm using VoiceOver on Mac in Chrome and in Safari.

## 🤔 Expected Behavior

Screen reader should announce new month when clicking picker chevrons.

## 😯 Current Behavior

Screen reader will only announce new month when clicking chevrons the first time the picker is opened.  If you close and reopen the picker, clicking chevron no longer triggers announcement. 

## 🔦 Context

Our team can't use this component due to this a11y issue.

## 🌍 Your Environment

Spectrum 3.21.2

### PR DESCRIPTION
**Pull request by majornista**
When clicking on the right or left chevron, there should be an aria-live announcement that announces the newly displayed month. This is what occurs when opening the picker initially and reading through; however after you close and reopen the picker, it will no longer announce when clicking the chevron. If you remount the component by refreshing the page, it will work again as described above. I'm using VoiceOver on Mac in Chrome and in Safari.

When you first open the Calendar overlay in the [DatePicker Example](https://react-spectrum.adobe.com/react-spectrum/DatePicker.html#example), the LiveAnnouncer will not have initialized, because there has never been a need to announce anything. When you then navigate between months, a LiveAnnouncer region gets added at the start of the DOM, and is explicitly excluded from the elements to be hidden by `ariaHideOutside` (see [ariaHideOutside.ts#L33-L36](https://github.com/adobe/react-spectrum/blob/892d41e82dc781fb4651455d0e29c324376659ed/packages/%40react-aria/overlays/src/ariaHideOutside.ts#L33-L36) and [ariaHideOutside.ts#L88-L98](https://github.com/adobe/react-spectrum/blob/892d41e82dc781fb4651455d0e29c324376659ed/packages/%40react-aria/overlays/src/ariaHideOutside.ts#L88-L98)), which allows the live region to announce. However, when the Calendar overlay gets opened after the LiveAnnouncer has initialized, the `aria-modal-polyfill`, used to hide elements outside of the React-Spectrum provider, fails to omit the `LiveAnnouncer` region from the elements to be hidden from assistive technology. `LiveAnnouncer` fails to announce because it has been marked as `aria-hidden="true"`.

Closes #3559 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 3559](https://github.com/adobe/react-spectrum/issue/3559).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. With VoiceOver or NVDA running, open https://react-spectrum.adobe.com/react-spectrum/DatePicker.html#example, which exhibits the bug described in #3559.
2. Expand the DatePicker Calendar popover dialog
3. Use Next or Previous buttons to advance the the previous or next month.
4. Screen reader should announce new month and year.
5. Close the Calendar popover by pressing the Esc key.
6. Expand the DatePicker Calendar popover dialog a second time.
7. Use Next or Previous buttons to advance the the previous or next month.
8. Without this fix, the screen reader will no longer announce the new month and year.

9. Open https://reactspectrum.blob.core.windows.net/reactspectrum/866f13209f6ba7e3b12c1e492a4c9821a94e8310/docs/react-spectrum/DatePicker.html#example, which contains the fix in #3564.
10. Expand the DatePicker Calendar popover dialog
11. Use Next or Previous buttons to advance the the previous or next month.
12. Screen reader should announce new month and year.
13.  Close the Calendar popover by pressing the Esc key.
14. Expand the DatePicker Calendar popover dialog a second time.
15. Use Next or Previous buttons to advance the the previous or next month.
8. With the fix, the screen reader will announce the new month and year.

## 🧢 Your Project:

Adobe/Accessibility/RSP

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
seems more like something that ariaHideOutside should fix
should we not hide nodes with `data-live-announcer="true"`?

I guess what I'm asking is, what happens to a live announcer if it gets hidden mid sentence? is that possible?

File: packages/@react-aria/aria-modal-polyfill/src/index.ts [hunk 1]
```diff
@@ -34,14 +34,15 @@ export function watchModals(selector:string = 'body', {document = currentDocumen
   let undo: Revert | undefined;
 
   let observer = new MutationObserver((mutationRecord) => {
+    const liveAnnouncer: HTMLElement =  document.querySelector('[data-live-announcer="true"]');
```
Comment (snowystinger) [inline packages/@react-aria/aria-modal-polyfill/src/index.ts:37]: so this selects the top level one and assumes only one per application. this should probably be more general though. if we did
```
const liveAnnouncers: HTMLElement = document.querySelectorAll('[aria-live]');
///
undo = hideOthers([modal, ...liveAnnouncers])
```

that would be useful in other applications as well or with other libraries that implement their own live announcers

Comment (devongovett) [reply packages/@react-aria/aria-modal-polyfill/src/index.ts:37]: I don't think we necessarily want to preserve every `aria-live` element though, just our live announcer.

**Review by snowystinger — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
