### PR TITLE
Fixing combobox menu flipping on initial open

### LINKED ISSUE #2024: ComboBox - Menu direction does not flip correctly
### Expected Behaviour
- ComboBox menu will appear on top when attempting to open it while having it very low in the browser

### Actual Behaviour

1. ComboBox menu appears on bottom when attempting to open it while having it very low in the browser
2. While the ComboBox is low on the browser and menu is still open on the bottom, when the Chevron is double clicked, the menu will go up

#### Steps to Reproduce
1. Goto [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example)
2. Locate the first example 
3. Scroll down or up on ur browser till the ComboBox is near the bottom of the browser
4. Click the ComboBox's Chevron to open the menu
5. You will notice that the menu opens at the bottom
6. While the menu is opened, double click the Chevron in the ComboBox again
7. You will notice the menu going on top of the ComboBox now

#### Sample Code that illustrates the problem
- See the example here [https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#example)

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #2024 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

In any of the combobox stories, size your window in such a way that the listbox won't fit fully at the bottom. The listbox should be flipped to the top when opened

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-spectrum/combobox/src/ComboBox.tsx [hunk 1]
```diff
@@ -137,6 +137,17 @@ const ComboBoxBase = React.forwardRef(function ComboBoxBase<T extends object>(pr
...
+  // Update position once the ListBox has rendered. This ensures that
+  // it flips properly when it doesn't fit in the available space.
+  // TODO: add ResizeObserver to useOverlayPosition so we don't need this.
+  useLayoutEffect(() => {
+    if (state.isOpen) {
+      requestAnimationFrame(() => {
+        updatePosition();
+      });
+    }
+  }, [state.isOpen, updatePosition]);
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/ComboBox.tsx:149]: Taken straight from Picker. I thought I remembered this bit of code causing problems in the past for ComboBox but I dug through the repo/pulls/issues and couldn't find anything. Seems to work fine in testing

**Review by snowystinger — APPROVED** [review]
LGTM in chrome/ff/safari

**Comment by reidbarber** [comment]
LGTM

**Review by dannify — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
