### PR TITLE
 fix/bug useTablist #5996

### LINKED ISSUE #5996: "useTabList" hook keyboard navigation with arrow keys not considering orientation
### Provide a general summary of the issue here

We are using the `useTabList` hook to build a tab component that only uses the `horizontal` orientation. By the definition of [W3 regarding keyboard navigation](https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#keyboardinteraction) for tabs, the `horizontal` orientation should only be navigated by using `Left Arrow` & `Right Arrow` keys while using `Down Arrow` & `Up Arrow` should scroll the page.

We have currently implemented a workaround by overriding the `onKeyDown` with a custom callback that is blocking the `Down Arrow` & `Up Arrow` key navigation.

### 🤔 Expected Behavior?

When using `orientation="horizontal"` for `useTabList` from `'@react-aria/tabs'` users should only be able to switch the tabs with `Left Arrow` & `Right Arrow` keys. `Down Arrow` & `Up Arrow` keys should scroll the page.

### 😯 Current Behavior

When using `orientation="horizontal"` for `useTabList` from `'@react-aria/tabs'` users will switch the tab by either using `Left Arrow` & `Right Arrow` or `Down Arrow` & `Up Arrow` keys.

### 💁 Possible Solution

We are currently using a workaround to override the returned event handler `onKeyDown` with our own custom solution:

```ts
const { tabListProps } = useTabListReactAria({}, state, tabListRef);

const handleKeyDown = (e: KeyboardEvent<FocusableElement>) => {
    if (e.key === 'ArrowUp' || e.key === 'ArrowDown') {
        return;
    }

    tabListProps.onKeyDown?.(e);
};

const boxProps = {
    tabList: {
        ...tabListProps,
        onKeyDown: handleKeyDown,
    }
}
```

### 🔦 Context

https://www.w3.org/WAI/ARIA/apg/patterns/tabs/#keyboardinteraction

### 🖥️ Steps to Reproduce

* Create a tab with the available hooks (or use `react-spectrum` tabs component)
* Open the [sandbox link](https://codesandbox.io/p/sandbox/frosty-newton-fjj4m2?file=%2Fsrc%2FApp.js%3A2%2C69&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cltct3lpj00063b7xshv366yh%2522%252C%2522sizes%2522%253A%255B100%252C0%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cltct3lpj00023b7xcncxvaxr%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cltct3lpj00033b7xfsg2ayow%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cltct3lpj00053b7x16w3vfv8%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cltct3lpj00023b7xcncxvaxr%2522%253A%257B%2522id%2522%253A%2522cltct3lpj00023b7xcncxvaxr%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltctc70p00023b7zkk2z5lam%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A23%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A23%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522cltctkl4100023b7zte8hkp6t%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A2%252C%2522startColumn%2522%253A69%252C%2522endLineNumber%2522%253A2%252C%2522endColumn%2522%253A69%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.js%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522cltctkl4100023b7zte8hkp6t%2522%257D%252C%2522cltct3lpj00053b7x16w3vfv8%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cltct3lpj00043b7xb9fs0rpq%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522cltct3lpj00053b7x16w3vfv8%2522%252C%2522activeTabId%2522%253A%2522cltct3lpj00043b7xb9fs0rpq%2522%257D%252C%2522cltct3lpj00033b7xfsg2ayow%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522cltct3lpj00033b7xfsg2ayow%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Afalse%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D) and navigate to the tab list via keyboard (`Tab` key)
* Navigate the tab list with the arrow keys

### Version

`"@react-aria/tabs": "^3.8.5"` is currently used but the version does not matter.

### What browsers are you seeing the problem on?

Other

### If other, please specify.

Browser is not relevant, issue happens everywhere.

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by mdhmaiti**
Closes #5996 

## ✅ Pull Request Checklist:

- [x] Issue #5996 
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

1. run locally and navigate to the useTabList in the storybook.
2. try to move between the tabs using arrow keys.
3. Here I added restrictions to the upper arrow key and lower arrow key to solve the issue .

## 🧢 Your Project:

Added the  horizontal orientations in the TabsKeyboardDeligate to prevent moving of tabs using upper and lower arrow keys

### CODE REVIEW

**Comment by snowystinger** [comment]
Thanks for the PR! To answer some of your questions from the Issue, it should be your Github login for the CLA.

It would also appear that you have prettier or some auto formatted enabled because some files changed which I don't think you meant to change. It would be good to revert all the unrelated style changes so we can focus on the actual changes for the PR.

You can see how each of the ci steps are run by looking in the circle config file, package.json, and makefile. As for getting them to pass, if you look at the test that failed, you'll see that we're testing for the bad behavior https://github.com/adobe/react-spectrum/blob/a8ec9667a2b70b88b45e329bf44918f0f93d54f9/packages/%40react-spectrum/tabs/test/Tabs.test.js#L122 so you should be able to just assert that up/down doesn't move focus for horizontal tabs

**Comment by mdhmaiti** [comment]
Thanks for helping me. I will fix my code

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — COMMENTED** [review]
Thanks for the PR! I'm double checking the behavior we want here via https://github.com/adobe/react-spectrum/issues/5996#issuecomment-1986523075 so we'll be holding off on any further changes until we can confirm that.

As an aside, if this is indeed the behavior we want, we'll also need to modify useSelectableCollection to only conditionally prevent default behavior on various keydown events. As it is now, the changes in this PR actually aren't sufficient to allow ArrowUp/Down to scroll the page when the TabList's orientation is 'horizontal'

**Comment by mdhmaiti** [comment]
` getKeyBelow(key: Key) {
    if (this.tabDirection) {
        window.scrollBy(0, window.innerHeight);
        return null;
    }
    return this.getNextKey(key);
}
`
I thought of adding ``` window.scrollBy(0, window.innerHeight); ``` to provide vertical scroll but the useTablist story book only has the horizontal scroll so I was not sure window.scrollby was working or not, so I skipped this code

**Comment by snowystinger** [comment]
> `getKeyBelow(key: Key) { if (this.tabDirection) { window.scrollBy(0, window.innerHeight); return null; } return this.getNextKey(key); }` I thought of adding `window.scrollBy(0, window.innerHeight);` to provide vertical scroll but the useTablist story book only has the horizontal scroll so I was not sure window.scrollby was working or not, so I skipped this code

Better to just not preventDefault when we aren't actively handling that key and let the browser do its thing. It may not be the window which needs to scroll. It could be any ancestor.
https://github.com/adobe/react-spectrum/blob/89fa370bd1bb346be643c9ab2a0d79fab857e4d7/packages/%40react-aria/selection/src/useSelectableCollection.ts#L126

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 1]
```diff
@@ -123,7 +123,10 @@ export function useSelectableCollection(options: AriaSelectableCollectionOptions
   let onKeyDown = (e: KeyboardEvent) => {
     // Prevent option + tab from doing anything since it doesn't move focus to the cells, only buttons/checkboxes
     if (e.altKey && e.key === 'Tab') {
-      e.preventDefault();
+      // allowing default behavior for above and below key
+      if (!delegate.getKeyAbove || !delegate.getKeyBelow) {
+        e.preventDefault();
+      }
```
Comment (LFDanLu) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:129]: since this is in the `if (e.altKey && e.key === 'Tab') {` statement, this won't actually have the desired effect of allowing default behavior if the the delegate returns null from getKeyAbove/getKeyBelow. You'll want to look at the cases in the switch statement like here: https://github.com/adobe/react-spectrum/blob/449bc07cca60a810c48ebbb8aa3ec242036243ef/packages/%40react-aria/selection/src/useSelectableCollection.ts#L166 and make those `e.preventDefault` not be called if `nextKey` is null I imagine.

**Comment by yihuiliao** [comment]
I just wanted to pop in and let you know that the team might be slow to review as we work on some other priorities. We appreciate your understanding and apologize for the wait.

**Comment by mdhmaiti** [comment]
No no its okk , I also had my exams and I am still learning, I am willing to wait

**Comment by snowystinger** [comment]
Update on comment https://github.com/adobe/react-spectrum/pull/6023#pullrequestreview-1925979900 from above here:  https://github.com/adobe/react-spectrum/issues/5996#issuecomment-2173619669

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]
Verified that ArrowUp/Down still have browser default behavior when navigating a horizontally oriented TabList but ArrowUp/Down/Left/Right all still shift the Tab selection for vertical tabs. Thanks for the contribution!
