### PR TITLE
Fixes #1666: Omit duplicated type in ColorFieldProps

### LINKED ISSUE #1666: Color Component failing on typecheck
# 🐛 Bug Report 

Using "@react-spectrum/color": "^3.0.0-alpha.0".. It is failing on the typecheck for the onChange prop

## 😯 Current Behavior

Our code works fine as expected. The issue does not hinder the development but we cannot commit our changes to git.

## 🔦 Context

Interface 'ColorFieldProps' incorrectly extends interface 'ValueBase<string | Color>'.
Types of property 'onChange' are incompatible.
Type '((color: Color) => void) | undefined' is not assignable to type '((value: string | Color) => void) | undefined'.
Type '(color: Color) => void' is not assignable to type '(value: string | Color) => void'.
Types of parameters 'color' and 'value' are incompatible.
Type 'string | Color' is not assignable to type 'Color'.
Type 'string' is not assignable to type 'Color'.ts(2430)

image

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | "^3.6.0"
| Browser          | chrome
| Operating System | Mac OS

## 🧢 Your Company/Team

Adobe/Dynamic Chat

### PR DESCRIPTION
**Pull request by kwoncharles**
Closes #1666

- remove `onChange` prop of `ValueBase`

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/@react-types/color/src/index.d.ts [hunk 1]
```diff
@@ -76,7 +76,7 @@ export interface Color {
   formatChannelValue(channel: ColorChannel, locale: string): string
 }
 
-export interface ColorFieldProps extends ValueBase<string | Color>, InputBase, Validation, FocusableProps, TextInputBase, LabelableProps {
+export interface ColorFieldProps extends Omit<ValueBase<string | Color>, 'onChange'>, InputBase, Validation, FocusableProps, TextInputBase, LabelableProps {
```
Comment (devongovett) [inline packages/@react-types/color/src/index.d.ts:79]: Doesn't this get overridden below anyway? Do we need to explicitly omit it?

Comment (kwoncharles) [reply packages/@react-types/color/src/index.d.ts:79]: @devongovett
You are right. However, when the [`--strict`](https://www.typescriptlang.org/tsconfig#strict) or [`--strictFunctionTypes`](https://www.typescriptlang.org/tsconfig#strictFunctionTypes) option is enabled, Typescript complains about this as you can see in the [issue](https://github.com/adobe/react-spectrum/issues/1666). (Maybe the issue creator uses IDE default TS option)

If we don't need to consider it now, It's better to close it now :)

**Review by devongovett — APPROVED** [review]
