### PR TITLE
Prevent intl-messageformat error throw if `variable` values are undefined or null

### LINKED ISSUE #2543: ComboBox with section-less items breaks with error: "The intl string context variable "isGroupChange" was not provided..."
# 🐛 Bug Report 

Due to the changes in `intl-messageformat` made [here](https://github.com/formatjs/formatjs/commit/b3ac86d9a3eb082e349b1683312131df96796231), we need to pass non-null/undefined values in our variables object to `formatMessage` or it will throw an error. Locally we use have `intl-messageformat@^9.6.12`, this breaks with `intl-messageformat@9.9.5`

Here is where one such place is:
https://github.com/adobe/react-spectrum/blob/1e635d5e6540927a001f552194c30d8b3b48d8e8/packages/%40react-aria/combobox/src/useComboBox.ts#L245
Will need to check if there are any other places

## 🤔 Expected Behavior

User should be able to navigate/focus ComboBox items

## 😯 Current Behavior

Throws an error when focusing a ComboBox section-less item:

`The intl string context variable "isGroupChange" was not provided to the string "{isGroupChange, select, true {Entered group {groupTitle}, with {groupCount, plural, one {# option} other {# options}}. } other {}}{optionText}{isSelected, select, true {, selected} other {}}"`

## 💁 Possible Solution

Either go through the code and change all places where we return `null` to `false` in the variables provided to `formatMessage` or  have `useMessageFormatter` do this for use

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |. 3.14.1
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #2543 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

go to the ComboBox stories (one w/ sections and one w/o), turn on VoiceOver and test that you can move focus around in the dropdown menu via the arrow keys. The announcement should be the same as main for both story types

For further testing, bump ` intl-messageformat` to latest (our yarn.lock is at 9.6.12 whereas the breaking change happened in 9.9.5) and make sure the announcements still work. Other components (TableView, SearchField, anything with a selection checkbox, etc) that use `formatMessage` should be smoke tested but I went through them and most of them don't pass optional 2nd input arg `variables` so it should be ok 

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@internationalized/message/src/MessageFormatter.ts [hunk 1]
```diff
@@ -39,7 +39,14 @@ export class MessageFormatter {
       message = new IntlMessageFormat(msg, this.locale);
       this.cache[key] = message;
     }
+    let varCopy: Record<string, PrimitiveType | T | FormatXMLElementFn<T, string | T | (string | T)[]>> | undefined;
+    if (variables) {
+      varCopy = Object.keys(variables).reduce((acc, key) => ({
+        ...acc,
+        [key]: variables[key] == null ? false : variables[key]
+      }), {});
```
Comment (snowystinger) [inline packages/@internationalized/message/src/MessageFormatter.ts:47]: instead of copying the object a bunch (potentially), you could just assign. you already created a new object on line 47 to add to
```suggestion
      varCopy = Object.keys(variables).reduce((acc, key) => {
        acc[key] = variables[key] == null ? false : variables[key]
        return acc;
      }, {});
```

Comment (LFDanLu) [reply packages/@internationalized/message/src/MessageFormatter.ts:47]: good point 👍

**Review by snowystinger — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
Tested on Chome with VO

**Review by reidbarber — APPROVED** [review]
LGTM, tested in Chrome with VO
