### PR TITLE
isDisabled does not work as expected

### LINKED ISSUE #2467: isDisabled does not work as expected with useComboBox/useComboboxState
# 🐛 Bug Report 

isDisabled only prevents opening combobox when clicking on the input element.
Clicking on the label or button parts of a combobox that is disabled still opens the combobox.

This is probably related to https://github.com/adobe/react-spectrum/issues/1887

## 🤔 Expected Behavior

`disabled` should be set on both inputProps and buttonProps
when `isDisabled` is `true`, clicking on label, input, or button of a combobox should not open the combobox

## 😯 Current Behavior

`disabled` is only passed to `inputProps`.  The button remains enabled, and interacting with the label opens the combo box even when disabled.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by Onyinye91-ctrl**
Closes #2467 #1887

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Try the `Disabled` story in the `useComboBox` stories and verify that clicking + using the arrow keys on the button doesn't open the menu  

## 🧢 Your Project:
#2473

### CODE REVIEW

**Comment by Onyinye91-ctrl** [comment]
@reidbarber i have made the necessary changes. Please review

**Comment by Onyinye91-ctrl** [comment]
@snow893 i have corrected it
As for the CLA i signed it, i don't know why it;s saying that. I even got a mail to that effect But what do they mean by github login. Does that mean my username?

**Comment by Onyinye91-ctrl** [comment]
@reidbarber I have sign the CLA now

**Review by snowystinger — COMMENTED** [review]
I guess we can't pass disabled back out of our hook since the input props and trigger props are HTML attributes only?
was trying to see if we could get rid of this line https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/combobox/src/ComboBox.tsx#L343
it might still be worth it to pass it out of the useComboBox hook for those two objects though? then map them back to isDisabled since we have intermediate components before we get to the DOM?

File: packages/@react-aria/menu/src/useMenuTrigger.ts [hunk 1]
```diff
@@ -79,14 +79,14 @@ export function useMenuTrigger(props: MenuTriggerAriaProps, state: MenuTriggerSt
       id: menuTriggerId,
```
Comment (LFDanLu) [inline packages/@react-aria/menu/src/useMenuTrigger.ts:79]: Another thing to consider is whether or not we should propagate `isDisabled` through the button/trigger props returned by `useMenuTrigger`/`useComboBox`. This would save us the trouble from having to add these `isDisabled` checks to our press handlers and would save the user from having to pass `isDisabled` to `usePress` + they would automatically get `disabled: true` from the props that `usePress` returns. 

However, it would mean they would need to override that `disabled: true` if they wanted to have a trigger button that is focusable/pressable but has its overlay opening capabilities disabled.

Comment (LFDanLu) [reply packages/@react-aria/menu/src/useMenuTrigger.ts:79]: Talked with @snowystinger, I'll propagate isDisabled through for useComboBox for now

**Review by snowystinger — APPROVED** [review]

**Review by ktabors — APPROVED** [review]
