### PR TITLE
fix: RadioGroup should not validate on form reset

### LINKED ISSUE #8134: RadioGroup validates when reseting Form
### Provide a general summary of the issue here

RadioGroup component, with isRequired attribute, validates the parent Form when reseting it.
As a result, the FieldError is shown.

### 🤔 Expected Behavior?

The RadioGroup component should reset to it's original state like CheckBoxGroup component or any form field.

### 😯 Current Behavior

The RadioGroup component is not reset.

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

Here's a codesandbox : [](https://codesandbox.io/p/devbox/musing-gauss-frzcl6?workspaceId=ws_TU4H7Nb7c2NoJPiHd9kEEg)

Just click on reset

### Version

1.8.0

### What browsers are you seeing the problem on?

Microsoft Edge

### If other, please specify.

_No response_

### What operating system are you using?

Windows 11

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by chirokas**
Closes #8134

<del>
  Since the ref is not a stable reference, the previous `onReset` gets unmounted
  during a React discrete update.
</del>

https://github.com/adobe/react-spectrum/blob/ef27de089a92628089aeffb405fd69a6b88aa85f/packages/%40react-aria/form/src/useFormValidation.ts#L91-L93

<del>
  To solve this, we have to make sure that the `inputRef` is always a stable
  reference.
</del>

I can't clearly explain what happened, but [here](https://stackblitz.com/edit/vitejs-vite-kehnqmjs?file=src%2FApp.tsx)'s a similar case.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Comment by fivemtebex** [comment]
This is a well-structured codebase. I appreciate the clean separation of concerns.

File: packages/react-aria-components/src/RadioGroup.tsx [hunk 1]
```diff
@@ -186,7 +186,7 @@ export const Radio = /*#__PURE__*/ (forwardRef as forwardRefType)(function Radio
   } = props;
   [props, ref] = useContextProps(otherProps, ref, RadioContext);
   let state = React.useContext(RadioGroupStateContext)!;
-  let inputRef = useObjectRef(mergeRefs(userProvidedInputRef, props.inputRef !== undefined ? props.inputRef : null));
+  let inputRef = useObjectRef(useMemo(() => mergeRefs(userProvidedInputRef, props.inputRef !== undefined ? props.inputRef : null), [userProvidedInputRef, props.inputRef]));
```
Comment (snowystinger) [inline packages/react-aria-components/src/RadioGroup.tsx:189]: I think this is correct, we usually useMemo with mergeRefs and useObjectRef, it looks like this one was missed

**Review by snowystinger — APPROVED** [review]
Thanks for the fix! Doesn't look like we can test in jsdom, I tried it in 26.1.0 to see if the reset behaviour changed, but no luck. Probably have to file a bug against them at some point.

**Review by yihuiliao — APPROVED** [review]
