### PR TITLE
fix: ref.current is not checked to be set

### LINKED ISSUE #1549: useSelectableList Error: Uncaught TypeError: Cannot read property 'querySelector' of null
# 🐛 Bug Report 

`useSelectableList` called with `isVirtualized: false` does not check if the ref is set and throws this error:

> Error: Uncaught TypeError: Cannot read property 'querySelector' of null

https://github.com/adobe/react-spectrum/blob/abcd25984bc9cf726754e4dea9a392afdc3d8afb/packages/%40react-aria/selection/src/useSelectableList.ts#L107-L116

## 🤔 Expected Behavior

Refs should always be checked to be set.

## 😯 Current Behavior

`ref.current` is not checked to be set.

## 💁 Possible Solution

Add a check for `ref.current` to the if block.

```js
if (!isVirtualized && selectionManager.focusedKey && ref.current) {}
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by AndyOGo**
Closes #1549 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Call `useListBox({ isVirtualized: false })` with virtualization disabled.

### CODE REVIEW

File: packages/@react-aria/selection/src/useSelectableList.ts [hunk 1]
```diff
@@ -107,7 +107,7 @@ export function useSelectableList(props: SelectableListOptions): SelectableListA
   // If not virtualized, scroll the focused element into view when the focusedKey changes.
   // When virtualized, Virtualizer handles this internally.
   useEffect(() => {
-    if (!isVirtualized && selectionManager.focusedKey) {
+    if (!isVirtualized && selectionManager.focusedKey && ref.current) {
```
Comment (LFDanLu) [inline packages/@react-aria/selection/src/useSelectableList.ts:110]: Perhaps
```suggestion
    if (!isVirtualized && selectionManager.focusedKey && ref?.current) {
```
since `ref` could technically be undefined? Or we could move to `let element = ref?.current?.querySelector...`

**Review by LFDanLu — CHANGES_REQUESTED** [review]
small suggestion, lemme know what you think

File: packages/@react-aria/selection/src/useSelectableList.ts (hunk 1 above)
Comment (AndyOGo) [reply packages/@react-aria/selection/src/useSelectableList.ts:110]: I prefer the optional chaining op.

In this case though I think you know better in how many cases this hook is utilized.

I use this hook indirectly via [`useListBox`](https://react-spectrum.adobe.com/react-aria/useListBox.html), there the `ref` is required.
https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/listbox/src/useListBox.ts#L52

**Review by snowystinger — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Comment by AndyOGo** [comment]
Guess you are quite busy with all sorts of things.
May I ask when the next release is planned?

**Comment by LFDanLu** [comment]
@AndyOGo Sorry about the delay, I'll merge this and it will go out with the next release (either today or early next week).
