### PR TITLE
Fix prop types for useListBox

### LINKED ISSUE #1100: Unable to type useSelect's usage of useListBox
# 📝 Feedback

This could just be feedback on better documentation or there may be a TypeScript issue here. Following the [example for `useSelect`](https://react-spectrum.adobe.com/react-aria/useSelect.html) it seems like `useListBox` requires `children` as the input type extends `CollectionBase` but the example doesn't pass any props or property called `children` to `useListBox`. Things also seem to work fine with that too.

## 🔦 Context

Just trying to implement a component using `useSelect` with TypeScript

## 💻 Code Sample

[Here is a running example of the documentation code with some attempted typing in TypeScript](https://codesandbox.io/s/reverent-beaver-7vf6f?file=/src/App.tsx:2241-2335). 

These lines specifically are the problem:

```js
let { listBoxProps } = useListBox(
    {
      autoFocus: state.focusStrategy || true,
      disallowEmptySelection: true
    },
    state,
    ref
  );
```

```
Argument of type '{ autoFocus: FocusStrategy; disallowEmptySelection: true; }' is not
assignable to parameter of type 'AriaListBoxOptions<any>'.
Property 'children' is missing in type '{ autoFocus: FocusStrategy; disallowEmptySelection: true; }'
but required in type 'AriaListBoxOptions<any>'
```

## 🌍 Your Environment

See the CodeSandbox

## 🧢 Your Company/Team

N/A

### PR DESCRIPTION
**Pull request by mischnic**
Closes #1100

`AriaListBoxOptions -> AriaListBoxProps -> ListBoxProps -> CollectionBase.children`

Any `children` prop passed into `useListBox` was never actually used.

### CODE REVIEW

File: packages/@react-aria/listbox/src/useListBox.ts [hunk 1]
```diff
@@ -49,7 +49,7 @@ interface AriaListBoxOptions<T> extends AriaListBoxProps<T> {
  * @param props - Props for the listbox.
  * @param state - State for the listbox, as returned by `useListState`.
  */
-export function useListBox<T>(props: AriaListBoxOptions<T>, state: ListState<T>, ref: RefObject<HTMLElement>): ListBoxAria {
+export function useListBox<T>(props: Omit<AriaListBoxOptions<T>, 'children'>, state: ListState<T>, ref: RefObject<HTMLElement>): ListBoxAria {
```
Comment (devongovett) [inline packages/@react-aria/listbox/src/useListBox.ts:52]: My poor documentation generator. It seems to still be showing children. Maybe move the omit to the extends clause on the interface above and see if that works?

**Review by devongovett — APPROVED** [review]
