### PR TITLE
Slider refactor and a11y improvements

### LINKED ISSUE #1231: Slider Accessibility Audit
# 🐛 Bug Report 

Following accessibility related issues have been identified in Slider and RangeSlider:

## 🤔 Expected Behavior

1. `<label>` should always reference the `input` element for the first slider thumb using the `for` attribute, so that clicking the label will focus the slider input control.
2. Minimum/Maximum slider thumb inputs in a two thumb range slider are not be labelled as such using i18n, unless otherwise explicitly labelled.
3. Pressing the `displayValue` should focus the corresponding input.
4. For displayValue, use `<output>` with appropriate `aria-labelledby`, `aria-live="off"` and `htmlFor` referring to the corresponding input to label the output value segments. 
5. Focused slider thumb should always be on top in the z-index order.
6. Update Slider (hooks) examples to implement labelling similar to how Slider and RangeSlider do and to pass text contrast requirements for the text labels.

## 😯 Current Behavior

1. `<label>` incorrectly references the container element with `role="group"` using the `for` attribute, so clicking the label fails to focus the slider input control.
2. Minimum/Maximum slider thumb inputs in a RangeSlider are not be labelled as such using i18n.
3. Pressing the display value does not focus the corresponding input.
4. Slider currently uses a `role="textbox"` with `aria-readonly="true"`, which seems about as appropriate as `output` with `aria-live="off"`, but `output` supports the `htmlFor` attribute making it easy to implement the focus on press behavior using an `onPress` event handler.
5. Slider thumb z-index order currently follows DOM order, so the last thumb is always on top regardless of the current focus, which gets confusing when thumbs overlap.
6. Slider hooks should implement `label[htmlFor]`, `output[htmlFor]`, make use of the localized minimum/maximum strings, and pass WAI-ARIA text contrast requirements.

## 💁 Possible Solution

Suggested fixes have been implemented in https://github.com/adobe/react-spectrum/pull/1148.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |   [v3.0.0-alpha.1 ](https://reactspectrum.blob.core.windows.net/reactspectrum/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/storybook-17/index.html?path=/story/slider--label)
| Browser          | Chrome Version 86.0.4240.183 (Official Build) (x86_64)
| Operating System | macOS 10.15.7 (19H2)

## 🕷 Tracking Issue (optional)

https://github.com/adobe/react-spectrum/pull/1148

### PR DESCRIPTION
**Pull request by devongovett**
Based on #1148. Closes #1148. Closes #1231.

* Adds `outputProps` to `useSlider`, which associates the `<output>` element with each slider thumb.
* Uses a single `<output>` element for the whole value label given that we support custom value formats through `valueLabel`. This loses clicking on the individual values to focus the thumb, but I think this should hopefully be ok since it was kind of undiscoverable anyway.
* Manually handles clicking on the label to focus the first thumb since Safari does not do this on a native `<input type="range">`.
* Adds "minimum" and "maximum" labels to the thumbs in RangeSlider. This is moved to Spectrum since we can't assume that all 2-thumbed sliders are range sliders.
* Refactors the way `SliderBase` works so that `SliderThumb` is a separate component rather than breaking the rules of hooks.

### CODE REVIEW

**Review by dannify — DISMISSED** [review]

**Review by dannify — APPROVED** [review]

File: packages/@react-aria/slider/src/useSlider.ts [hunk 1]
```diff
@@ -162,6 +176,11 @@ export function useSlider(
       onMouseDown(e: React.MouseEvent<HTMLElement>) { onDownTrack(e, undefined, e.clientX, e.clientY); },
       onPointerDown(e: React.PointerEvent<HTMLElement>) { onDownTrack(e, e.pointerId, e.clientX, e.clientY); },
       onTouchStart(e: React.TouchEvent<HTMLElement>) { onDownTrack(e, e.changedTouches[0].identifier, e.changedTouches[0].clientX, e.changedTouches[0].clientY); }
-    }, moveProps)
+    }, moveProps),
+    outputProps: {
+      htmlFor: state.values.map((_, index) => getSliderThumbId(state, index)).join(' '),
+      'aria-labelledby': labelProps.id,
+      'aria-live': 'off'
+    }
```
Comment (LFDanLu) [inline packages/@react-aria/slider/src/useSlider.ts:184]: Just to make sure:
when you say `Uses a single <output> element for the whole value label given that we support custom value formats through valueLabel. This loses clicking on the individual values to focus the thumb, but I think this should hopefully be ok since it was kind of undiscoverable anyway.`
does this mean:
-  clicking on the `<output>` shouldn't focus the thumb at all 
OR
- that clicking the individual values in the output (e.g. in a range slider) should focus the same thumb, we are just losing the individual thumb focus behavior that was added previously

Comment (devongovett) [reply packages/@react-aria/slider/src/useSlider.ts:184]: I don't believe clicking does anything anymore.
