### PR TITLE
Ensure react is a peer dependency instead of a dependency

### LINKED ISSUE #799: [@react-stately/collections] Uses 'react' as a "dependency" rather than a "peerDependency"
# 🐛 Bug Report  
`@react-stately/collections` includes `react` as a "dependency" making it extra difficult to alias React out of a build when attempting to leverage the stately hooks in other contexts.

## 🤔 Expected Behavior
All dependencies on React would be the same so that the `alias` technique could be the same across the board.

## 😯 Current Behavior
The use of "dependency" vs "peerDependency" prevents from above `alias`ing from replace React in the application.

## 🔦 Context
The Spectrum Web Components project is investigating whether it's possible to leverage the stately and aria hooks in their project. https://github.com/adobe/spectrum-web-components/pull/717

## 🧢 Your Company/Team
Adobe Spectrum

### PR DESCRIPTION
**Pull request by devongovett**
Closes #799

### CODE REVIEW

File: scripts/lint-packages.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ const fs = require('fs');
 const assert = require('assert');
 const chalk = require('chalk');
 let path = require('path');
-let packages = glob.sync(__dirname + '/packages/@{react,spectrum}-*/*/package.json');
+let packages = glob.sync(path.dirname(__dirname) + '/packages/@{react,spectrum}-*/*/package.json');
```
Comment (devongovett) [inline scripts/lint-packages.js:18]: we were linting the wrong directory 😬
