### PR TITLE
Ensure that arrow keys in grid cells always win over children

### LINKED ISSUE #5877: Picker in TableView creates a focus trap with arrow key navigation
### Provide a general summary of the issue here

- A Picker in a TableView or ListView creates a focus trap when using ArrowLeft for grid navigation.
- ArrowRight will change the value of a Picker even when focus has moved to another cell or element within the grid.

### 🤔 Expected Behavior?

It should be possible to navigate from a cell containing a Picker to the previous or next cell in the row using ArrowLeft or ArrowRight:

1. without focus getting trapped on the Picker.
2. without the value of the Picker changing unexpectedly when navigating to a new cell.

### 😯 Current Behavior

1. Focus remains on the Picker when trying to use ArrowLeft to navigate to the previous cell in a row.
2. The value of the Picker changes as the focus moves to the next cell using ArrowRight.

### 💁 Possible Solution

1. In `useSelect`, wait a frame, and verify that focus remains on the Picker before changing the value on ArrowRight or ArrowLeft.
2. In `HiddenSelect`, focusing the `input` should verify that the `relatedTarget` is not the `triggerRef.current`, before marshalling focus to the `triggerRef.current`.

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/pedantic-euler-csggfh?file=%2Fsrc%2FApp.tsx

1. Open the example app at https://csggfh.csb.app/
2. The example app consists of a TableView in which the last row has a Picker in the second cell.
3. Press Tab to navigate and set focus to the first row in the TableView.
4. Press ArrowDown until the last row, containing the Picker has focus.
5. Press ArrowRight to focus the Switch in the first cell.
6. Press ArrowRight again to focus the Picker in the second cell.
7. Press ArrowLeft to try to move focus to the previous cell in the row.
8. Notice that focus remains on the Picker when trying to use ArrowLeft.
9. Press ArrowRight to move focus to the next cell, containing the word "Three."
10. Notice that the value of the Picker changes as the focus moves to the next cell.

### Version

3.34.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If other, please specify.

_No response_

### What operating system are you using?

macOS 14.4 Beta (23E5191e)

### 🧢 Your Company/Team

Adobe/Accessibility

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by devongovett**
Closes #5877, closes #5878

Alternative solution to #5878. This fixes picker inside a table cell. It applies the same solution we have for up and down arrows already: grid cell stops propagation in the capture phase so the event does not reach its children, and then re-dispatches it from the parent element so that it bubbles up to the table if there are no more focusable elements in the cell.

### CODE REVIEW

**Review by LFDanLu — APPROVED** [review]
LGTM, tested locally with the Picker in various locations in the Row and with additional focusable elements in the same cell, things seem to work well. Lets get this in for testing.

**Review by reidbarber — APPROVED** [review]
LGTM

File: packages/@react-aria/focus/src/isElementVisible.ts [hunk 1]
```diff
@@ -43,6 +43,8 @@ function isStyleVisible(element: Element) {
 function isAttributeVisible(element: Element, childElement?: Element) {
   return (
     !element.hasAttribute('hidden') &&
+    // Ignore HiddenSelect when tree walking.
+    !(element.hasAttribute('data-a11y-ignore') && element.getAttribute('aria-hidden') === 'true') &&
```
Comment (snowystinger) [inline packages/@react-aria/focus/src/isElementVisible.ts:47]: won't this conflate hiding things from the axe plugin vs implementation?

Comment (devongovett) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: maybe, this came from Michael's pr. I'm on pto next week but you could ask him about it. Not sure why just checking aria-hidden without the data-a11y-ignore wouldn't work.

Comment (majornista) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: It came from my PR: https://github.com/adobe/react-spectrum/pull/5878/commits/d160bac41a51c839858b0c4614fb95da5e799ffd#diff-e1bb593250b04d4c80095b5a414062150d86db252d886ee3a8040c7eb126425b

We can test with just skipping `aria-hidden`.

Comment (majornista) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: Simply ignoring `!(element.getAttribute('aria-hidden') === 'true')` will break tree walking to Tab/Shift+Tab focus the next or previous element when a Picker or Menu is open, because all elements under a modal popover have `aria-hidden="true"`.

Comment (snowystinger) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: Seems like we should introduce a new data attribute then? there may be other reasons for this data attribute being used, and it can be used by non-rsp projects on any component. It's very specific to AXE and other related tools

Comment (majornista) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: Any suggestions? `data-ignore-tree-walking`?

Comment (snowystinger) [reply packages/@react-aria/focus/src/isElementVisible.ts:47]: yeah, i think that's a good place to start the discussion, thank you!
