### PR TITLE
fix(#2632): Dialog Heading should use H2 rather than H3

### LINKED ISSUE #2632: Dialog Heading should use H2 rather than H3
# 🐛 Bug Report 

For a more consistent heading level hierarchy, Dialogs within React-Spectrum should use H2 rather than H3 as the element for Dialog heading.

Note: This may have been a relic of v2 Storybook, where each Story page includes an H1 and H2s.

## 🤔 Expected Behavior

Follow WAI-ARIA Authoring Practices Guide example: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/alertdialog.html and use H2 for Dialog element header. This way, assuming the web page containing the dialog has an H1, the heading level for the Dialog will appear in an appropriate hierarchical order for the page.

## 😯 Current Behavior

We currently use H3.

## 💁 Possible Solution

Heading slots default to H3:
https://github.com/adobe/react-spectrum/blob/9ba765f71bdde97d1545d91f76326e61bd35ae30/packages/%40react-spectrum/text/src/Heading.tsx#L24

We could either change this or override it as appropriate for different components that use it.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  @react-spectrum/text@3.1.3, @react-spectrum/dialog@3.3.4
| Browser          |  Chrome v96.0.4664.55 (Official Build) (x86_64)
| Operating System | macOS 11.6.1 (20G224)

## 🧢 Your Company/Team

Adobe/Accessibility

### PR DESCRIPTION
**Pull request by majornista**
Add a level prop to specify the Heading level for Dialog heading slot.

Closes #2632 
## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 2632](https://github.com/adobe/react-spectrum/issues/2632).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Open Dialog/AlertDialog examples, verify that the Heading element within each Dialog uses H2 rather than H3.

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

**Comment by majornista** [comment]
Question. Do we need to provide `level` as an public API for setting the Dialog heading level, or can we just make it static?

**Comment by snowystinger** [comment]
The API is already there, so it's going to stay for a little while at least. Are all dialogs truly always only h2?

**Comment by majornista** [comment]
> The API is already there, so it's going to stay for a little while at least. Are all dialogs truly always only h2?

The API for setting a level on Heading is there, but it doesn't seem to be exposed by Dialog, and AlertDialog just uses the default, which is currently H3. I think it is probably safe to use H2. Dialogs render in a Portal, if we assume there is at least one H1 in the underlying page, H2 seems appropriate.

**Comment by snowystinger** [comment]
@majornista Wouldn't the H1 in the page behind be hidden? so shouldn't the Dialog be an H1?

**Comment by majornista** [comment]
> @majornista Wouldn't the H1 in the page behind be hidden? so shouldn't the Dialog be an H1?

Depending on the automated testing library, using a second H1 might be flagged as an error as well, despite the underlying H1 being hidden using aria-hidden. I'm following the WAI-ARIA Authoring Practices Guide Modal Dialoge example provided here: https://www.w3.org/TR/wai-aria-practices/examples/dialog-modal/dialog.html.

File: packages/@react-spectrum/dialog/src/AlertDialog.tsx [hunk 1]
```diff
@@ -72,7 +72,7 @@ function AlertDialog(props: SpectrumAlertDialogProps, ref: DOMRef) {
       size="M"
       role="alertdialog"
       ref={ref}>
-      <Heading>{title}</Heading>
+      <Heading level={2}>{title}</Heading>
```
Comment (snowystinger) [inline packages/@react-spectrum/dialog/src/AlertDialog.tsx:75]: given the change below, this should be unnecessary

File: packages/@react-spectrum/dialog/src/Dialog.tsx [hunk 2]
```diff
@@ -63,7 +63,7 @@ function Dialog(props: SpectrumDialogProps, ref: DOMRef) {
   let slots = useMemo(() => ({
     hero: {UNSAFE_className: styles['spectrum-Dialog-hero']},
     header: {UNSAFE_className: styles['spectrum-Dialog-header']},
-    heading: {UNSAFE_className: classNames(styles, 'spectrum-Dialog-heading', {'spectrum-Dialog-heading--noHeader': !hasHeader}), ...titleProps},
+    heading: {UNSAFE_className: classNames(styles, 'spectrum-Dialog-heading', {'spectrum-Dialog-heading--noHeader': !hasHeader}), level: 2, ...titleProps},
```
Comment (snowystinger) [inline packages/@react-spectrum/dialog/src/Dialog.tsx:66]: if we do this, then no one can make a dialog with h3 or anything else, it'll always be h2

Comment (snowystinger) [reply packages/@react-spectrum/dialog/src/Dialog.tsx:66]: otherwise probably best if we waited and handled this with part of typography

Comment (dannify) [reply packages/@react-spectrum/dialog/src/Dialog.tsx:66]: Right now it is always h3 now anyway right? So it would be no different. Later we will probably fix this with auto headings

Comment (devongovett) [reply packages/@react-spectrum/dialog/src/Dialog.tsx:66]: Right now it's h3 by default, but users can override by setting the `level` prop. But with slots, they won't be able to override anymore (slots always win). I can't really think of a use case to make it higher than h2 though...

Comment (majornista) [reply packages/@react-spectrum/dialog/src/Dialog.tsx:66]: I'm a bit confused by the ask here. An earlier commit added a public API for a `level` prop on the `Dialog` that would default to `2`: https://github.com/adobe/react-spectrum/pull/2633/commits/53fe561ad6ab7afcbb8f9c66a02b040960e8b72b. Is this what we want, or is it better just to explicitly set to `level={2}` on the slot as done here?

Comment (snowystinger) [reply packages/@react-spectrum/dialog/src/Dialog.tsx:66]: The issue with adding it to the slot is that we use slots to enforce certain things in children. So if you put a level 2 in the slots, even if someone did `<Heading level={5}>` it'd still produce a level 2 Heading. @devongovett 's question is, would anyone need to either set a Dialog's Heading to anything other than 2?

**Review by snowystinger — APPROVED** [review]
Approving per discussion in standup

**Review by reidbarber — APPROVED** [review]
