### PR TITLE
3199 resize window tabs flicker

### LINKED ISSUE #3199: Resizing a window with a Tabs-Control who is collapsed makes the line jump around
# 🐛 Bug Report 

If one has a Tabs-Control who is in collapsed state and one eg makes the window even smaller the line below the picker jumps around.

## 🤔 Expected Behavior

Line stays where it is not jumping left/right

## 😯 Current Behavior

Line moves to the right and then jumps back to the left

## 💁 Possible Solution

I looked a bit at the code and the problem I think is: To compute if it is necessary to collapse the tab-list the DOM is modified for a rendering cycle adding back the complete tab-list. 

I think this problem could be solved without modifying the DOM but simply hiding the tab-list instead of removing it.

## 🔦 Context

It makes the Tabs-Control look slugish

## 💻 Code Sample

- go to https://react-spectrum.adobe.com/react-spectrum/Tabs.html#customizing-layout 
- add some more tabs then resize the page so that the picker is shown
- resize even more to see the line jumping

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | main
| Browser          | Firefox, Chrome,
| Operating System | OS-X

### PR DESCRIPTION
**Pull request by tomsontom**
Closes #3199 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by tomsontom** [comment]
There's one failing test but I have no clue how to fix it - I doubt it is a regression I introduce but more a problem with the test itself

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 1]
```diff
@@ -425,7 +423,7 @@ function TabPicker<T>(props: TabPickerProps<T>) {
           items={items}
           ref={ref}
           isQuiet
-          isDisabled={isDisabled}
+          isDisabled={!visible || isDisabled}
```
Comment (tomsontom) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:426]: I don't think this is needed but the "should focus the selected tab when tabbing in for the first time" fails arguing that the focus is at the picker who is in a (visually) hidden container

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 2]
```diff
@@ -288,7 +277,9 @@ export function TabList<T>(props: SpectrumTabListProps<T>) {
         },
         orientation === 'vertical' && styleProps.className
       )
-      }>
+      }
+      aria-hidden={collapse}
+      style={style}>
```
Comment (snowystinger) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:282]: this is going to override the `{...stylePropsForVertical}` on line 265

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 3]
```diff
@@ -270,6 +257,8 @@ export function TabList<T>(props: SpectrumTabListProps<T>) {
   }, [state.disabledKeys, state.selectedItem, state.selectedKey, props.children]);
   let stylePropsForVertical = orientation === 'vertical' ? styleProps : {};
 
+  let style : React.CSSProperties = collapse ? {visibility: 'hidden', position: 'absolute'} : {};
```
Comment (snowystinger) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:260]: This isn't quite right, if you go to `path=/story/tabs--collapse-behavior-isemphasized-true` and add a bunch of tabs, eventually, the screen will start scrolling. 

I think this would take care of it and allow the overflow calculation to still work
```suggestion
  let style : React.CSSProperties = collapse ? {maxWidth: 'calc(100% + 1px)', overflow: 'hidden', visibility: 'hidden', position: 'absolute'} : {maxWidth: 'calc(100% + 1px)'};
```

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 4]
```diff
@@ -408,7 +404,9 @@ function TabPicker<T>(props: TabPickerProps<T>) {
           'spectrum-Tabs--emphasized': isEmphasized
         },
         className
-      )}>
+      )}
+      style={style}
+      aria-hidden={!visible}>
```
Comment (snowystinger) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:409]: I think aria-hidden is one of those fields, where, instead of false, it should be omitted
```suggestion
      aria-hidden={visible ? undefined : true}>
```

File: packages/@react-spectrum/tabs/src/Tabs.tsx (hunk 1 above)
Comment (snowystinger) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:426]: I also don't think this is needed. I think the failures are telling us that the accessibility is wrong somewhere.
I'm not quite sure where.
That or RTL/Jest DOM has a bug.

**Review by snowystinger — COMMENTED** [review]
Thanks for having a go at it. Here's an initial review.

File: packages/@react-spectrum/tabs/src/Tabs.tsx (hunk 1 above)
Comment (tomsontom) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: So I think this is a JEST-DOM bug. 

Adding the following test cases to the picker tests:
```js
  it('test visibility=hidden', function () {
    render(
      <Provider theme={theme}>
        <div style={{visibility: 'hidden'}}>
          <Picker label="Test" data-testid="test" onSelectionChange={onSelectionChange}>
            <Item>One</Item>
            <Item>Two</Item>
            <Item>Three</Item>
          </Picker>
        </div>
      </Provider>
    );

    userEvent.tab();

    expect(document.activeElement.tagName).toBe('BODY');
  });

  it('test display=none', function () {
    render(
      <Provider theme={theme}>
        <div style={{display: 'none'}}>
          <Picker label="Test" data-testid="test" onSelectionChange={onSelectionChange}>
            <Item>One</Item>
            <Item>Two</Item>
            <Item>Three</Item>
          </Picker>
        </div>
      </Provider>
    );

    userEvent.tab();

    expect(document.activeElement.tagName).toBe('BODY');
  });

  it('test isDisabled', function () {
    render(
      <Provider theme={theme}>
        <div>
          <Picker isDisabled label="Test" data-testid="test" onSelectionChange={onSelectionChange}>
            <Item>One</Item>
            <Item>Two</Item>
            <Item>Three</Item>
          </Picker>
        </div>
      </Provider>
    );

    userEvent.tab();

    expect(document.activeElement.tagName).toBe('BODY');
  });
```
I get the following results:
- test visibility=hidden => fail
- test display=none => fail
- test isDisabled => success

File: packages/@react-spectrum/tabs/src/Tabs.tsx (hunk 3 above)
Comment (snowystinger) [reply packages/@react-spectrum/tabs/src/Tabs.tsx]: Yes, that appears to work. I'm not sure where I missed that earlier when I was trying it out. Thanks for pointing it out.

File: packages/@react-spectrum/tabs/src/Tabs.tsx (hunk 1 above)
Comment (tomsontom) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: @snowystinger so what do we do on this? Keep the work-around with disabling the control or trying to find a work around for the tests.

Comment (snowystinger) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: Looks like we might be able to update userEvent https://openbase.com/js/@testing-library/user-event/versions search page for "tab: skip elements with visibility:hidden"
if that's minimal work to update, then we can do here, otherwise, maybe we apply skip with a todo and we update userEvent in a separate PR

Comment (tomsontom) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: I tried updateing to user-even v14.2.0 and yes this makes the disabled work-around not needed anymore but there are then tests failing all over the place. So unless I did something really wrong I think updating user-event should be done in a follow up PR.

Comment (tomsontom) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: So I think from my side we are done

Comment (snowystinger) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: thanks, we're actually on break right now, but we'll be back next week

Comment (snowystinger) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:428]: Thanks for the reminder, I'll review it today

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 5]
```diff
@@ -268,12 +255,18 @@ export function TabList<T>(props: SpectrumTabListProps<T>) {
     setTabListState(state);
     // eslint-disable-next-line react-hooks/exhaustive-deps
   }, [state.disabledKeys, state.selectedItem, state.selectedKey, props.children]);
-  let stylePropsForVertical = orientation === 'vertical' ? styleProps : {};
+
+  let collapseStyle : React.CSSProperties = collapsed && orientation !== 'vertical' ? {maxWidth: 'calc(100% + 1px)', overflow: 'hidden', visibility: 'hidden', position: 'absolute'} : {maxWidth: 'calc(100% + 1px)'};
+  let stylePropsFinal = orientation === 'vertical' ? styleProps : {style: collapseStyle};
+
+  if (collapsed && orientation !== 'vertical') {
```
Comment (snowystinger) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:262]: question for second reviewer, should we move this into our aria hook? it seems very specific to our implementation in rendering, so I think it's fine here

**Review by snowystinger — APPROVED** [review]
Looks like it's working as expected, and looks good with VO as well, not seeing any strange messages

**Comment by LFDanLu** [comment]
GET_BUILD

File: packages/@react-spectrum/tabs/src/Tabs.tsx (hunk 5 above)
Comment (LFDanLu) [reply packages/@react-spectrum/tabs/src/Tabs.tsx:262]: I agree, the collapse behavior is specific to Spectrum, I'd rather not force these styles on aria hook consumers.

**Review by LFDanLu — APPROVED** [review]
LGTM
