### PR TITLE
Fixes for mobile combobox focus and input reset behavior

### LINKED ISSUE #1833: ComboBox mobile bugs
# 🐛 Bug Report 

-  When you blur from the combobox button on mobile, the input value doesn't reset to the selected key's text
- Can't close "menuTrigger='focus'" combobox on mobile unless you select an option
- Mobile combobox isn't autofocused when `autoFocus` is applied
- Mobile combobox opens when user clicks the buttons to change the controlled input value (see story). Pre-existing issue, only occurs if the user had previously interacted with the ComboBox
## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #1833

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 1]
```diff
@@ -55,20 +56,39 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
...
+    menuTrigger = 'input'
   } = props;
 
   let {contains} = useFilter({sensitivity: 'base'});
   let state = useComboBoxState({
     ...props,
     defaultFilter: contains,
     allowsEmptyCollection: true,
-    shouldCloseOnBlur: false
+    shouldCloseOnBlur: true
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:68]: This fixes the following bug: "When you blur from the field in Android, the input value doesn't reset to the selected key's text". However, runs counter to the behavior setup in this pull: https://github.com/adobe/react-spectrum/pull/1176 and this commit specifically: https://github.com/adobe/react-spectrum/commit/39be0d7ab9bf1391ef4560281df1a0ce43fde85b

If we want to preserve the behavior where the combobox value isn't committed upon closing the tray but have the input value reset when blurring from the mobile combobox button, we'll need to expose `commitSelection` or something from `useComboBoxState` and use it in the mobile combobox button blur perhaps.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 2]
```diff
@@ -92,7 +112,7 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
         ref={domRef}
         includeNecessityIndicatorInAccessibilityName>
         <ComboBoxButton
-          {...mergeProps(triggerProps, fieldProps)}
+          {...mergeProps(triggerProps, fieldProps, {onBlur: trayInputProps.onBlur, onFocus: trayInputProps.onFocus, autoFocus: props.autoFocus})}
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:115]: Fixes the following bugs:
- Mobile combobox isn't autofocused when autoFocus is applied
- Mobile combobox opens when user clicks the buttons to change the controlled input value (see story)

Root issue is that the mobile combobox button doesn't have the blur/focus handlers that `useComboBox` returns so `state.isFocused` doesn't get updated when blurring/focusing the button

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 3]
```diff
@@ -55,20 +56,39 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
...
     ...props,
     defaultFilter: contains,
     allowsEmptyCollection: true,
-    shouldCloseOnBlur: false
+    shouldCloseOnBlur: true
   });
 
   let buttonRef = useRef<HTMLElement>();
   let domRef = useFocusableRef(ref, buttonRef);
   let {triggerProps, overlayProps} = useOverlayTrigger({type: 'listbox'}, state, buttonRef);
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:73]: Note that I haven't fixed the following bug yet: `Can't close "menuTrigger='focus'" combobox on mobile unless you select an option`. The core issue is that closing the tray sets `isFocused` to false because the input field loses focus.

One way to fix this would be to restore the following changes from a older pull:
- https://github.com/adobe/react-spectrum/blob/975957a3c3fb4a9f3be358428e0980a4d4e51c1a/packages/%40react-aria/combobox/src/useComboBox.ts#L140 
-  https://github.com/adobe/react-spectrum/blob/975957a3c3fb4a9f3be358428e0980a4d4e51c1a/packages/%40react-aria/combobox/src/useComboBox.ts#L230-L246
(for the second bullet point, specifically the logic where we track `prevOpenState` and have modify the `(isMobile && state.isOpen && e.relatedTarget === null)` part of the `onBlur` logic to see if we are going from `prevOpenState = open` to `prevOpenState = close`.

Perhaps another way would be to track `prevOpenState` in `useComboBoxState` and block `setFocused` from triggering `open`. Maybe we could just have isFocused not become false when the user closes the tray...

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 4]
```diff
@@ -402,6 +423,15 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
...
   }, [loadingState, inputValue, showLoading]);
 
+  let onBlur = (e: React.FocusEvent<HTMLInputElement>) => {
+    // Ignore blur if focus moves from tray input to something outside the popover (i.e. tray is being closed via tapping outside the tray -> focus will return to combobox button -> prevent menuTrigger = focus from reopening the combobox tray).
+    if (e.target === inputRef?.current && !popoverRef.current?.contains(e.relatedTarget as HTMLElement)) {
+      return;
+    }
+
+    inputProps.onBlur(e);
+  };
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:433]: Fixes the following bug: `Can't close "menuTrigger='focus'" combobox on mobile unless you select an option`

Early returns `onBlur` so `isFocused` doesn't get set to false when you close the tray. Put it here because this feels specific to our mobile combobox implementation

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:68]: e9d81f9565f173329e04cbe1aff280de2fd4a164 makes it so the input value doesn't reset when the tray input gets blurred even though `shouldCloseOnBlur` is true (early returns `onBlur` so `setFocused` from useComboBoxState doesn't get called), but then allows blurring the combobox button to reset the input value because `shouldCloseOnBlur` is true

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 3 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:73]: e9d81f9 is what I settled on to fix this, open to suggestions

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 5]
```diff
@@ -402,6 +423,15 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
...
 
+  let onBlur = (e: React.FocusEvent<HTMLInputElement>) => {
+    // Ignore blur if focus moves from tray input to something outside the popover (i.e. tray is being closed via tapping outside the tray -> focus will return to combobox button -> prevent menuTrigger = focus from reopening the combobox tray).
+    if (!popoverRef.current?.contains(e.relatedTarget as HTMLElement)) {
+      return;
+    }
+
+    inputProps.onBlur(e);
+  };
+
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:434]: Fixes the following bug: `Can't close "menuTrigger='focus'" combobox on mobile unless you select an option`

Early returns `onBlur` so `isFocused` doesn't get set to false when you close the tray. Put it here because this feels specific to our mobile combobox implementation

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:434]: perhaps should be

```
...
if (!state.isOpen)) {
    return;
}
...
```

**Comment by LFDanLu** [comment]
Will add tests when approach is approved

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 2 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:115]: Rob found an interesting bug where occasionally a mobile combobox with `menuTrigger=focus` will open and automatically close on tap. Did some digging and I believe this is due to the tray opening on pressdown (focus opens the tray due to `menuTrigger=focus`) and the subsequent press up triggers a onInteractOutside causing the tray to close. Still trying to think about how to handle this, but kinda at a loss (almost wanna say that `menuTrigger=focus` shouldn't work on mobile). 

100% reproduction steps:
1. Go to combobox story w/ `menuTrigger = autofocus` 
2. Make sure the combobox isn't focused by tapping on the background
3. Tap and hold on the combobox. Notice the tray opens
4. Release your press. Note that the tray closes

Comment (snowystinger) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:115]: I think it just doesn't make any sense for it to open on press start, makes more sense to open on press end like when we handle touch for menus
It might be weird, but can focus occur on pressend instead?

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:115]: yep, that was going to be my next experiment

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 6]
```diff
@@ -159,9 +186,28 @@ const ComboBoxButton = React.forwardRef(function ComboBoxButton(props: ComboBoxB
       valueId,
       validationState === 'invalid' ? invalidId : null
     ].filter(Boolean).join(' '),
-    elementType: 'div'
+    elementType: 'div',
+    // Prevent focus on press and focus on press end to avoid situations where user
+    // presses and holds on the combobox button and tray immediately opens due to menuTrigger=focus
```
Comment (snowystinger) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:191]:
```suggestion
    // Prevent focus on `press` and instead focus on `pressend` to avoid situations where users
    // press and holds the combobox button and tray immediately opens due to menuTrigger=focus
```

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 7]
```diff
@@ -159,9 +186,28 @@ const ComboBoxButton = React.forwardRef(function ComboBoxButton(props: ComboBoxB
...
+    // @ts-ignore
```
Comment (snowystinger) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:192]: i'm surprised you need this?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 8]
```diff
@@ -159,9 +186,28 @@ const ComboBoxButton = React.forwardRef(function ComboBoxButton(props: ComboBoxB
...
+  // Prevents tray open -> useInteractOutside called on press end -> tray closing immediately when menuTrigger = "focus" and user presses and holds combobox button on mobile
+  useEffect(() => {
+    let button = ref.current;
+    let onTouchStart = (e) => e.preventDefault();
+    button.addEventListener('touchstart', onTouchStart);
+
+    return () => {
+      button.removeEventListener('touchstart', onTouchStart);
+    };
+  }, [ref]);
```
Comment (snowystinger) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:209]: what's the difference between this and the preventFocusOnPress?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 7 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:192]: yeah, I was too but it turns out we don't document `preventFocusOnPress` in the types cuz we probably want it to be internal:
https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/button/src/useButton.ts#L57-L58

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 8 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:209]: So we don't actually call preventDefault on touchStart in usePress, removed by this pull in favor of an alternative method for iOS: https://github.com/adobe/react-spectrum/pull/317. However, Android seems to work differently where a long press causes the button to be focused, hence the need to prevent default on touchStart here. I'll add this to the comment

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 2 above)
Comment (snowystinger) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:115]: I can no longer reproduce :)

**Review by snowystinger — DISMISSED** [review]
LGTM!
tested on iPhone 12

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:68]: I think it's weird to keep it until the outer button is blurred. Would it make more sense to have it reset when the tray closes? Looks like we already call `commit` on blur, but I guess it does nothing in this case because nothing is focused? Maybe there should be an `else` case there that calls `resetInputValue`?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 9]
```diff
@@ -55,20 +56,39 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
...
 
   let buttonRef = useRef<HTMLElement>();
   let domRef = useFocusableRef(ref, buttonRef);
   let {triggerProps, overlayProps} = useOverlayTrigger({type: 'listbox'}, state, buttonRef);
+  let layout = useListBoxLayout(state);
+  let popoverRef = useRef<HTMLDivElement>();
+  let listBoxRef = useRef<HTMLDivElement>();
+  let inputRef = useRef<HTMLInputElement>();
+
+  let {inputProps: trayInputProps, listBoxProps, labelProps: trayInputLabelProps} = useComboBox(
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:79]: I would be very careful about calling this here. `useComboBox` does a bunch of things (e.g. announcements) that might not make sense for the mobile combobox. Plus, manually copying over very specific props is kinda brittle to future changes. Perhaps this would be not needed given my other comment above?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 7 above)
Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:192]: Should we even support `menuTrigger = focus` for mobile combo box? That seems weird in general. Generally buttons don't do anything on focus.

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:192]: I'm fine with removing this option for mobile comboboxes, I'll make a note to make a follow up PR to mention this in the docs.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 9 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:79]: I'll see if I can change this, I'll probably need to copy the `onBlur` and `onFocus` logic from useComboBox and replicate it here so that I can fix: `Mobile combobox opens when user clicks the buttons to change the controlled input value` (issue was that we weren't updating the isFocused state when user blurred/focused the button)

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:68]: Hrm, lemme dig, but I think we won't be able to add a `else` that calls `resetInputValue` (aka `resetInputValue` if `commit` is called and there isn't a `focusedKey`) since it would cause the following flow to break:
1. User types in the field and the menu opens
2. No item is focused and user hits enter key
3. Nothing should happen but with this change the input value would get wiped.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 10]
```diff
@@ -83,6 +84,15 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
     }
   };
 
+  // When mobile ComboBox button recieves focus, set state.isFocused (i.e. the tray input's focus tracker) to false.
+  // This is to prevent state.isFocused from being set to true when the tray closes
+  // (FocusScope attempts to restore focus to the tray input when tapping outside the tray due to "contain")
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:89]: Interesting. Where is that focusing of the button happening? Doesn't FocusScope handle that via `restoreFocus`? And at that point it will have unmounted so contain shouldn't apply anymore? If not, then that's a problem in FocusScope that might affect other components.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:67]: Hmm. Is that weird that nothing happens if you don't have an item focused? Should it still close the menu and reset? Though I guess on mobile we wouldn't want it to close when pressing enter? We could override it to just blur the input and hide the keyboard I guess...

Alternatively, we could expose another method on the state that resets the value and call that when the tray closes.

Either way, it feels weird right now that this fix is reliant on changes in 3 seemingly unrelated places. It would be nice to make it a bit more explicit.

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:67]: So this would depend on what we would want the non-mobile case to do as well. If a user types in the field and hits enter, do we want it to close the menu and reset the text? I _think_ we discussed this as a team previously and decided that it should do nothing since it matched v2 combobox.

I'm leaning towards returning `resetInputValue` in state, lemme change that

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:67]: Another interesting case is that hitting the escape key doesn't call the Tray's onClose since useComboBox handles closing the tray on escape. I'll have mobile combobox change the escape key behavior to do `commit -> reset -> close` flow as well

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 10 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:89]: To reproduce, you can change https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/overlays/src/Overlay.tsx#L40 to be `!isOpen` so that the overlay immediately disappears, making it so that https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L244 will not fire since the overlay and its contents are unmounted

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: What first comes to mind is informing the FocusScope that an element/the FocusScope itself is transitioning out/being removed and thus suspend focus restoring/containment for the element/the FocusScope itself

Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: Hmm but the focus restoration happens in a requestAnimationFrame after the focus scope has unmounted. By that point the events should be unbound? https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L378

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: Just to make sure we are on the same page, this is the flow that currently happens from what I can tell:
1. User taps on underlay to close the tray. 
2. This blurs the combobox tray input. 
3. FocusScope's contain behavior refocuses the tray input via https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L235-L247. This triggers because the FocusScope hasn't unmounted at this point due to Overlay's transition time. This means combobox's `state.isFocused` is true.
4. The tray closes and the FocusScope unmounts. The FocusScope's containment behavior focus focuses the ComboBox button via https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/focus/src/FocusScope.tsx#L378 but `state.isFocused` is still true hence why I have the change here to set that to false.

Am I misunderstanding something in the above?

Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: Oh, so onBlur doesn't fire when the tray input unmounts?

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: yep, thats right, looks like react doesn't call onBlur on unmount: https://github.com/facebook/react/issues/12363

Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: Can we handle the underlying problem instead? i.e. set state.isFocused to false when the tray unmounts rather than handling focus on the button, which is a side effect of the former.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 11]
```diff
@@ -402,6 +423,16 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
     lastInputValue.current = inputValue;
   }, [loadingState, inputValue, showLoading]);
 
+  // Need to handle onKeyDown here, Tray's onClose doesn't trigger when hitting escape since useComboBox's escape handler closes the tray
+  let onKeyDown = (e) => {
+    // If there isn't a selected key and allowsCustomValue is true, then we avoid reseting input value so the new custom value persists
+    if (e.key === 'Escape' && !(!state.selectedKey && allowsCustomValue)) {
+      state.resetInputValue();
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:430]: I think this could go away also if you call `state.setFocused(false)` when the tray unmounts?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx]: Ok, @dannify and I discussed and I think we came to the following conclusions:

* Pressing Enter should always do something. If you haven't focused any items, then it should reset the input value and close the menu. I think that should avoid the need to expose state.resetInputValue. On mobile, we should override this keyboard listener and only hide the software keyboard rather than close the tray (i.e. move focus to the listbox).
* Pressing Escape should also reset and close the menu/tray.

What do you think? Also, I'm sorry. 😉

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 10 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:88]: Ah, derp, makes sense. I'll make it a useEffect cleanup in the ComboBox tray component

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 11 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:430]: We still need this to reset the input value when the user hits escape (unless you are suggesting that we make `shouldCloseOnBlur=true` in our `useComboBox` call?)

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 1 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx]: Sounds good, I'll give it a shot. One clarification for the following case: MobileComboBox w/ allowsCustomValue. I presume that pressing escape should only reset the input value if there is a selectedKey? IMO if there was a custom value previously entered and the user opens the tray -> modifies the input -> hits escape, the new value should replace the old value (this mirrors what happens in desktop combobox at the moment).

Another clarification: should pressing Escape really reset the input value for desktop combobox? IMO what we have for the desktop combobox right now is fine i.e. hitting escape closes the menu only, blurring the field resets the input.

Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx]: I think of Escape as a "cancel" action rather than only "close". So IMO it should behave exactly like onBlur.

To answer your questions:

1. Yes, it should do whatever `onBlur` does now. I think for `allowsCustomValue`, it would only close the menu/tray and not try to reset (i.e. `commitCustomValue`) otherwise reset (`commitSelection`).
2. I think so? Again, I see it more as a cancel.

I guess this should be exposed as a method on the state like `state.revert()`. So we'd have `state.commit` and `state.revert`, which seems to make sense to me.

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx]: Regarding moving the focus to the listbox when Enter is pressed on mobile, do we really want to do that or was that just a suggestion on how to close the software keyboard? Feels like that breaks the virtual focus setup that we have since we have all of our keydown handlers on the input itself.

I can close the virtual keyboard by setting readonly on to the field -> blurring the field -> removing the readonly if that sounds fine to you

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 12]
```diff
@@ -299,14 +309,21 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
...
     state
   );
 
   React.useEffect(() => {
     focusSafely(inputRef.current);
+
+    // When the tray unmounts, set state.isFocused (i.e. the tray input's focus tracker) to false.
+    // This is to prevent state.isFocused from being set to true when the tray closes via tapping on the underlay
+    // (FocusScope attempts to restore focus to the tray input when tapping outside the tray due to "contain")
+    return () => {
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:323]: Can you link to the React bug here?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 13]
```diff
@@ -83,6 +86,11 @@ export const MobileComboBox = React.forwardRef(function MobileComboBox<T extends
     }
   };
 
+  let onClose = () => {
+    state.commit();
+    state.close();
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:91]: I think it'll already get closed in `state.commit` right?

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 14]
```diff
@@ -402,6 +419,22 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
...
+    // Close virtual keyboard if user hits Enter w/o any focused options
+    if (e.key === 'Enter' && state.selectionManager.focusedKey == null) {
+      inputRef.current.readOnly = true;
+      popoverRef.current.focus();
+
+      // Required to keep keyboard from reopening, 6ms is minimum time so that editing the field and hitting enter hides the virtual keyboard in iOS
+      setTimeout(() => {
+        inputRef.current.focus();
+        inputRef.current.readOnly = false;
+      }, 6);
```
Comment (devongovett) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:432]: Is all of that really necessary? I tried it locally with only `popoverRef.current.focus()` and it seemed to work for me.

**Comment by devongovett** [comment]
Behavior seems good to me!

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 14 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:432]: Well, I wanted to keep the input field focused in case the user wanted to perform other operations (arrow keys to navigate through the options, typing, etc) but if I only have `popoverRef.current.focus()` they wouldn't be able to do that.

That being said, I don't know how many people use a keyboard with their phone haha, figured I'd play it safe.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 13 above)
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:91]: AHHH, yep, that should be handled now with the final else statement in `commit`, good catch

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx (hunk 14 above)
Comment (devongovett) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:430]: Ohh, didn't realize that. Yeah... I kinda doubt it. Also in that case, the software keyboard wouldn't even be visible in the first place. IMO we should keep it simple.

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx]: Ohhhhh good point. Kk, will remove the extra stuff and only focus the popover

**Review by devongovett — APPROVED** [review]

**Review by dannify — APPROVED** [review]
