### PR TITLE
fix: offset calculation to handle transformed elements with translateY or translateX in scrollIntoView

### LINKED ISSUE #7716: Incorrect offset calculation for elements positioned with transform: translate() in scrollIntoView
### Provide a general summary of the issue here

Incorrect offset calculation when child elements are positioned with `transform: translateY()` or `translateX()`.

### 🤔 Expected Behavior?

The function should return the correct offset even when the child element is positioned using CSS `transform: translateY()` or `translateX()`.

### 😯 Current Behavior

The current function only considers `offsetTop` and `offsetLeft`, which do not account for elements transformed using `translateY()` or `translateX()`. This results in incorrect positioning calculations.

### 💁 Possible Solution

Use `getBoundingClientRect()` to calculate the relative offset instead of relying on `offsetTop` and `offsetLeft`.

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

1. Create an element inside an ancestor with `transform: translateY(100px);`  
2. Use the current function to compute its relative offset  
3. Observe that the function does not account for the transformed position

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macos

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by piecyk**
Closes #7716

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Review by hshoja — APPROVED** [review]
Looks great, tested with tanstack virtuliazer and gridlist from react aria 👍🏼

**Comment by reidbarber** [comment]
Thanks for the PR! Is there an existing story we can test this with? If not, could you create a new one?

**Review by reidbarber — DISMISSED** [review]

File: packages/@react-aria/utils/src/scrollIntoView.ts [hunk 1]
```diff
@@ -73,23 +73,18 @@ export function scrollIntoView(scrollView: HTMLElement, element: HTMLElement) {
...
-      // If the ancestor is not `position:relative`, then we stop at
-      // _its_ offset parent, and we subtract off _its_ offset, so that
-      // we end up with the proper offset from child to ancestor.
-      sum -= ancestor[prop];
-      break;
-    }
-    child = child.offsetParent as HTMLElement;
-  }
-  return sum;
+  let childRect = child.getBoundingClientRect();
```
Comment (snowystinger) [inline packages/@react-aria/utils/src/scrollIntoView.ts:76]: We're a little nervous about this change. We think it's missing some cases. Looking at some other libraries, there is a fair amount of complexity in determining this. For example https://www.npmjs.com/package/compute-scroll-into-view

We might be able to use this library, though are reluctant to bring in the size increase. So the thing we need to prove is that this change is "enough" for our use cases or decide we're ok with the size increase.

**Comment by uhyo** [comment]
@snowystinger Hello! Can we get a chance to get this merged?

I just hit the issue when I tried to use DatePicker inside a virtually scrolled container. I really need this fix.

> So the thing we need to prove is that this change is "enough" for our use cases

I understand this concern, but I would like to emphasize that the current implementation is actually broken in some sense. The new `getBoundingClientRect`-based approach might possibly not be perfect, but its intent looks obvious; it seems clearly better than the current naive `offsetLeft`/`offsetTop` accumulation approach.

I'd appreciate if you could revisit this change.

@piecyk Thank you for the fix!

**Comment by snowystinger** [comment]
Thanks, I'll bump with the team to see if we can more concretely define what "enough" means. If anyone has any ideas on how to prove this, we'd welcome the ideas

**Review by yihuiliao — APPROVED** [review]
approving for testing

**Comment by LFDanLu** [comment]
We ran into a bug with our V3 TableView and horizontally scrolling Grid lists where navigating the rows via ArrowDown would cause the horizontal scroll position to shift erratically. Unfortunately had to pull this out of the release, but if you'd like to investigate that would be helpful!

**Comment by nwidynski** [comment]
@LFDanLu The mentioned issue as well as what this PR did is addressed by #9146  👍

**Comment by LFDanLu** [comment]
sweet, I had a feeling it did given some of the original recordings you shared in the original PR looked very similar to the bug we found during testing
