### PR TITLE
Cover all plural forms in NumberParser

### LINKED ISSUE #5104: Issue with pluralisation in the NumberField
### Provide a general summary of the issue here

Using the NumberField in slavic languages causes issues when adding the formatOptions `{ type: 'unit', unit: 'year', style, unitDisplay: 'long' }`.

### 🤔 Expected Behavior?

The user should still be able to cycle through the options. For example for polish it should start with:
- 0 lat
- 1 rok
- 2-4 lata
- 5 lat

But in case the value uses decimals it should be 3.1 roku.

### 😯 Current Behavior

When the user starts interacting with the NumberField the value would always be 0 lat.

### 💁 Possible Solution

The issue seems to be caused in the getSymbols method of the NumberFieldParser where the characters are determined which can be in front or at the end of the entered value. This only checks the used symbols for the a large decimal number `10000.111` `-10000.111` and `1` causing the year option not to work in case pluralisation rules needs to be applied.

https://github.com/adobe/react-spectrum/blob/a399db1e314243a023f7b5c95e319eba4496604c/packages/%40internationalized/number/src/NumberParser.ts#L196-L198

### 🔦 Context

There is an article I found showing the different types of pluralisation rules in different languages. https://lingohub.com/blog/2019/02/pluralization

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/cool-fast-mhls6q?file=/src/App.js

### Version

1.0.0-alpha-5

### What browsers are you seeing the problem on?

Other

### If other, please specify.

The issue is in all browsers

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by jbovenschen**
Closes #5104 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

This feature is testable by either looking up different forms of pluralisation in the https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#comparison table. This can be done by updating the formatOptions on a NumberField component to `{ style: 'unit', type: 'year' }` for example.

### CODE REVIEW

File: packages/@internationalized/number/src/NumberParser.ts [hunk 1]
```diff
@@ -191,11 +191,18 @@ class NumberParserImpl {
 
 const nonLiteralParts = new Set(['decimal', 'fraction', 'integer', 'minusSign', 'plusSign', 'group']);
 
+// This list is derived from https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#comparison and includes
+// all unique numbers which we need to check in order to determine all the plural forms for a given locale.
+// TODO: add a link to the used script
+const pluralNumbers = [
```
Comment (jbovenschen) [inline packages/@internationalized/number/src/NumberParser.ts:197]: This list of values I've extracted from the table on https://www.unicode.org/cldr/charts/43/supplemental/language_plural_rules.html#comparison. Using the following script:

```
function getRange(row) {
  let range = [];

  let th = row.firstElementChild;

  do {
    const { textContent } = th;

    let [start, end = start] = textContent.split('-');

    if (start === '') {
      range.push([]);
    } else {
      start = start.replace(/\.x$/, '.1');
      end = end.replace(/\.x$/, '.1');

      range.push([Number(start), Number(end)]);
    }
  } while ((th = th.nextElementSibling));

  return range;
}

function getLocales(cell) {
  let locales = [];

  let element = cell.firstElementChild;

  do {
    if (element.tagName === 'SPAN') {
      locales.push(element.title);
    }
  } while ((element = element.nextElementSibling));

  return locales;
}

function getPlurals(tr, categories, range) {
  const rules = Object.fromEntries(categories.map((key) => [key, []]));

  let td = tr.firstElementChild;

  let index = 1;

  do {
    const category = td.title;

    let columns = td.hasAttribute('colspan')
      ? Number(td.getAttribute('colspan'))
      : 1;

    do {
      rules[category].push(range[index]);

      index++;
    } while (columns-- > 1);
  } while ((td = td.nextElementSibling));

  return rules;
}

function extractTable(integerTable, fractionTable) {
  function extract(table) {
    const tbody = table.querySelector('tbody');

    let tr = tbody.firstElementChild;

    let current;
    let results = {};

    do {
      if (tr.firstElementChild.tagName === 'TH') {
        if (current) {
          for (const language of current.languages) {
            if (!results[language]) {
              results[language] = Object.fromEntries(
                Object.keys(current.rules).map((key) => [key, []])
              );
            }

            for (let rule in current.rules) {
              results[language][rule] = [].concat(
                results[language][rule],
                current.rules[rule]
              );
            }
          }
        }

        current = {
          range: [],
          languages: [],
          rules: {},
        };

        current.range = getRange(tr);
      } else if (
        tr.children[1] instanceof HTMLTableCellElement &&
        tr.children[1].classList.contains('l')
      ) {
        current.languages = getLocales(tr.children[1]);
      } else {
        const [lang] = current['languages'];

        const { pluralCategories } = new Intl.PluralRules(
          lang
        ).resolvedOptions();

        current.rules = getPlurals(tr, pluralCategories, current.range);
      }
    } while ((tr = tr.nextElementSibling));

    return results;
  }

  const integer = extract(integerTable);
  const fraction = extract(fractionTable);

  let values = new Set();

  for (let language in integer) {
    for (let rule in integer[language]) {
      if (integer[language][rule].length > 1) {
        values.add(integer[language][rule][0][0]);
      }
    }
  }

  for (let language in fraction) {
    for (let rule in fraction[language]) {
      if (fraction[language][rule].length > 1) {
        values.add(fraction[language][rule][0][0]);
      }
    }
  }

  return Array.from(values);
}

const [integerTable, fractionTable] = document.querySelectorAll('.pluralComp');

let values = extractTable(integerTable, fractionTable);
```

The code itself is not written optimal but it works to get a list of values with which we would get all plural forms.

Comment (snowystinger) [reply packages/@internationalized/number/src/NumberParser.ts:197]: This is wonderful, thank you for sharing this.

**Review by snowystinger — APPROVED** [review]

File: packages/@internationalized/number/src/NumberParser.ts (hunk 1 above)
Comment (snowystinger) [reply packages/@internationalized/number/src/NumberParser.ts:197]: Add the script to our repo
https://github.com/adobe/react-spectrum/pull/5141

**Review by devongovett — APPROVED** [review]
