### PR TITLE
Check is window exists in setupGlobalFocusEvents

### LINKED ISSUE #767: useFocusRing not working with SSR
# 🐛 Bug Report 

When using component with `useFocusRing` hook within, application crashes if component is rendered on server side.

## 🤔 Expected Behavior

`useFocusRing` hook should work the same on both server and client side.

## 😯 Current Behavior

On server side there is a `RefferenceError: HTMLElement is not defined`. I use `Next.js` as an SSR framework.
Error stack:
```
 | ReferenceError: HTMLElement is not defined
 |     at $b83372066b2b4e1d9257843b2455c$var$setupGlobalFocusEvents (/home/jakub/Projects/devomnifrontend/node_modules/@react-aria/interactions/dist/main.js:1031:15)
 |     at useFocusVisible (/home/jakub/Projects/devomnifrontend/node_modules/@react-aria/interactions/dist/main.js:1091:3)
 |     at useFocusRing (/home/jakub/Projects/devomnifrontend/node_modules/@react-aria/focus/dist/main.js:430:7)
 |     at Object.Switch [as render] (webpack-internal:///../ui/Switch/index.tsx:78:77)
 |     at ReactDOMServerRenderer.render (/home/jakub/Projects/devomnifrontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3535:44)
 |     at ReactDOMServerRenderer.read (/home/jakub/Projects/devomnifrontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3373:29)
 |     at renderToString (/home/jakub/Projects/devomnifrontend/node_modules/react-dom/cjs/react-dom-server.node.development.js:3988:27)
 |     at render (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/render.js:3:298)
 |     at Object.renderPage (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/render.js:46:1020)
 |     at Function.getInitialProps (webpack-internal:///../../node_modules/next/dist/pages/_document.js:133:19)
 |     at Function.getInitialProps (webpack-internal:///./pages/_document.tsx:49:85)
 |     at loadGetInitialProps (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/lib/utils.js:5:101)
 |     at renderToHTML (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/render.js:46:1330)
 |     at async /home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:68:285
 |     at async /home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:67:142
 |     at async DevServer.renderToHTMLWithComponents (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:91:254)
 |     at async DevServer.renderToHTML (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:92:254)
 |     at async DevServer.renderToHTML (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/server/next-dev-server.js:22:539)
 |     at async DevServer.render (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:48:236)
 |     at async Object.fn (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:35:852)
 |     at async Router.execute (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/router.js:28:28)
 |     at async DevServer.run (/home/jakub/Projects/devomnifrontend/node_modules/next/dist/next-server/server/next-server.js:44:494)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/focus| 3.0.1 
| Next.js | 9.4.4
| Operating System | Ubuntu 18.04

### PR DESCRIPTION
**Pull request by RafalFilipek**
`setupGlobalFocusEvents` should check if window exists to prevent crash on server side.

cc @Skona27

Closes #767

### CODE REVIEW

File: packages/@react-aria/interactions/src/useFocusVisible.ts [hunk 1]
```diff
@@ -105,7 +105,7 @@ function handleWindowBlur() {
  * Setup global event listeners to control when keyboard focus style should be visible.
  */
 function setupGlobalFocusEvents() {
-  if (hasSetupGlobalListeners) {
+  if ( window === 'undefined' || hasSetupGlobalListeners) {
```
Comment (devongovett) [inline packages/@react-aria/interactions/src/useFocusVisible.ts:108]:
```suggestion
  if (typeof window === 'undefined' || hasSetupGlobalListeners) {
```
