### PR TITLE
fix(#1885) Making ListLayout updateItemSize early return if layoutInfo is undefined

### LINKED ISSUE #1885: RS3 Table [Alpha] - Cannot set property 'estimatedSize' of undefined
# 🐛 Bug Report 
Toggling the selectionMode of the Table component causes an TypeError "Cannot set property 'estimatedSize' of undefined.  This issue seems to occur when one of the table rows is selected.

## 🤔 Expected Behavior
After having selected a row, changing the selectionMode should not cause an exception.

## 😯 Current Behavior
I have generated a sample that can reproduce the error.  https://codesandbox.io/s/determined-wilbur-ozcif?file=/src/App2.tsx Once the application loads:
1. select the "show" radio button
2. select the checkbox in the first row
3. click the "hide" radio button

## 💁 Possible Solution
🤷‍♂️

## 🔦 Context
Unable to drive the table dynamically causes our use case to not usable. 

## 💻 Code Sample
https://codesandbox.io/s/determined-wilbur-ozcif?file=/src/App2.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.9.0 |
| react-spectrum/table   | 3.0.0-alpha.11 |
| Browser          | Chrome |
| Operating System | Mac |

## 🧢 Your Company/Team
AEM

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #1885

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test steps:
1. Go to http://localhost:9003/?path=/story/tableview--controlled-selection-mode
2. change selection mode to multiple
3. Select any table row
4. Change selection mode to none. Note the table shouldn't throw

### CODE REVIEW

File: packages/@react-stately/layout/src/ListLayout.ts [hunk 1]
```diff
@@ -311,6 +311,11 @@ export class ListLayout<T> extends Layout<Node<T>> implements KeyboardDelegate {
 
   updateItemSize(key: Key, size: Size) {
     let layoutInfo = this.layoutInfos.get(key);
+    // If no layoutInfo, item has been deleted/removed.
+    if (!layoutInfo) {
+      return false;
+    }
```
Comment (LFDanLu) [inline packages/@react-stately/layout/src/ListLayout.ts:317]: Alternative/supplemental fix: maybe change https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/virtualizer/src/Virtualizer.ts#L907 to something like
```
let changed = !this.layout.getLayoutInfo(key) || this.layout.updateItemSize(key, size);
```
aka if that key doesn't have layout info, don't bother calling updateItemSize and perform a relayout (or maybe don't relayout?)

File: packages/@react-spectrum/table/test/Table.test.js [hunk 2]
```diff
@@ -3306,6 +3306,37 @@ describe('TableView', function () {
 
         scrollHeight.mockRestore();
       });
+
+      // To test https://github.com/adobe/react-spectrum/issues/1885
+      it('should not throw error if selection mode changes with overflowMode="wrap" and selection was controlled', function () {
```
Comment (snowystinger) [inline packages/@react-spectrum/table/test/Table.test.js:3311]: i know you probably ran this test before you made the change, but given that the description is fulfilled implicitly by making it all the way through this test and there is no explicit check for a not to throw at any point, can you confirm?
maybe the thing to do is add a comment at the point where it was throwing just so that if anyone breaks it in that way, they'll know if it was the same issue vs something new

File: packages/@react-spectrum/table/stories/Table.stories.tsx [hunk 3]
```diff
@@ -240,6 +242,13 @@ storiesOf('TableView', module)
       </TableView>
     )
   )
+  .add(
+    // For testing https://github.com/adobe/react-spectrum/issues/1885
+    'controlled selection mode',
```
Comment (snowystinger) [inline packages/@react-spectrum/table/stories/Table.stories.tsx:247]:
```suggestion
    'swap selection mode',
```
it's not really controlled as it's not a value that onChanges

File: packages/@react-spectrum/table/test/Table.test.js (hunk 2 above)
Comment (LFDanLu) [reply packages/@react-spectrum/table/test/Table.test.js:3311]: sure, I'll add a comment. For posterity, the error thrown happens at the rerender and looks like this:
```
 Uncaught [TypeError: Cannot set property 'estimatedSize' of undefined]
```

**Review by snowystinger — APPROVED** [review]
LGTM, tested in Chrome
i do see your other question, I don't have an opinion right now because it wouldn't really be informed. I'm happy to see how this one goes. Though if you want to elaborate on the two approaches (pros/cons?) maybe that'd help me form more of an opinion

**Comment by LFDanLu** [comment]
The pro of adding/using the virtualizer change would be that it is perhaps a more central change (it is the one calling layout.updateItemSize). However, it makes the assumption that if `this.layout.getLayoutInfo(key)` is `undefined` we don't need to call `layout.updateItemSize` making an assumption on how `updateItemSize` is written (this might be a reasonable assumption to make though). Additionally, I'm not entirely sure if we should call `relayout` when this situation occurs, but the test I wrote breaks when it does get called so I'm leaning towards no

**Review by ktabors — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
