### PR TITLE
Landmarks followup

### LINKED ISSUE #2894: Landmarks followup
Followup items from https://github.com/adobe/react-spectrum/pull/2750

- add a blur/focusout handler to handle case of clicking outside the window
- In console.errors, log the offending landmarks so they're easier to find
- consider using binary search at `compareDocumentPosition` for better performance
- consider only calling `checkLabels` in development for better performance

Investigate:
- NVDA: reads entire contents of landmark upon navigating to it (e.g. all cells of a table) 
- NVDA doesn't announce the main landmark when you use f6 and it lands on the textfield within (Nested Landmark story). It does so properly for other stories 

# 🐛 Bug Report 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #2894

- [x] In console.errors, log the offending landmarks so they're easier to find
- [x] ~only call checkLabels in development for better performance~ 
- [x] use binary search at addLandmark for better performance
- [x] add focusout handler to handle case of clicking outside the window

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test Landmarks stories for additions mentioned above

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-aria/landmark/src/useLandmark.ts [hunk 1]
```diff
@@ -140,14 +147,21 @@ class LandmarkManager {
   private checkLabels(role: AriaLandmarkRole) {
     let landmarksWithRole = this.getLandmarksByRole(role);
     if (landmarksWithRole.size > 1) {
-      if ([...landmarksWithRole].some(landmark => !landmark.label)) {
-        console.warn(`Page contains more than one landmark with the '${role}' role. If two or more landmarks on a page share the same role, all must be labeled with an aria-label or aria-labelledby attribute.`);
+      let duplicatesWithoutLabel = [...landmarksWithRole].filter(landmark => !landmark.label);
+      if (duplicatesWithoutLabel.length > 0) {
+        console.warn(
```
Comment (reidbarber) [inline packages/@react-aria/landmark/src/useLandmark.ts:152]: Should these be `console.warn` or `console.error`? Right now we have `console.error` for when you try to add more than one main landmark.

File: packages/@react-aria/landmark/test/useLandmark.test.tsx [hunk 2]
```diff
@@ -1116,6 +1120,40 @@ describe('LandmarkManager', function () {
...
+    let nav = getByRole('navigation');
+
+    fireEvent.keyDown(document.activeElement, {key: 'F6'});
+    fireEvent.keyUp(document.activeElement, {key: 'F6'});
+    expect(nav).toHaveAttribute('tabIndex', '-1');
+    expect(document.activeElement).toBe(nav);
+
+    act(() => {
+      (document.activeElement as HTMLElement).blur();
+    });
```
Comment (snowystinger) [inline packages/@react-aria/landmark/test/useLandmark.test.tsx:1150]: Using fireEvent with mousedown/up on the document.body won't actually blur this or move focus to the document.body because technically the body isn't focusable in the traditional sense and fireevent wont' move focus to it because of that

File: packages/@react-aria/landmark/src/useLandmark.ts [hunk 3]
```diff
@@ -98,29 +101,33 @@ class LandmarkManager {
...
+
+    this.landmarks.splice(start, 0, newLandmark);
   }
 
   public updateLandmark(landmark: Pick<Landmark, 'ref'> & Partial<Landmark>) {
     let index = this.landmarks.findIndex(l => l.ref === landmark.ref);
     if (index >= 0) {
       this.landmarks[index] = {...this.landmarks[index], ...landmark};
-      this.checkLabels(this.landmarks[index].role);
+      if (process.env.NODE_ENV !== 'production') {
```
Comment (snowystinger) [inline packages/@react-aria/landmark/src/useLandmark.ts:128]: So this actually doesn't survive our build step, we'll need to do some research or ask Devon if he knows how React handles dev mode
Screen Shot 2022-03-08 at 9 42 43 AM

Comment (reidbarber) [reply packages/@react-aria/landmark/src/useLandmark.ts:128]: @ktabors Not really useful in production, so probably better to just skip this check. There are probably other places we could start doing this as well.

Comment (reidbarber) [reply packages/@react-aria/landmark/src/useLandmark.ts:128]: @devongovett is going to bring this up with the parcel team, so I'll remove this for now.

**Review by snowystinger — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
