### PR TITLE
fix(#2901): ColorArea followup

### LINKED ISSUE #2901: ColorArea followup
# 🐛 Bug Report 

Testing followup:
-  Screen reader announcement is extremely verbose and unclear that it is referring to a color. "2d slider" is used as a role description rather than "color area". It reads the full color, and then some of the channels again, every single time you press an arrow key. 
- adjust color in color area, then color in slider. the z-index of the slider thumb is wrong, and appears behind the color area
  -  To reproduce, you must click on the colorarea/colorslider itself, not the thumb
- Aria-label "foo" story isn't overriding the default aria-label which is set on the input fields.
- There isn't a color announcement made when the ColorSlider value is changed. in NVDA 

Story improvements:
- Should the ColorSlider in the ColorArea stories have the same step value applied to it? Right now it doesn't.  (UPDATE STORY)
- stories might make more sense if the third channel (slider) defaulted to zero rather than 100% 

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by majornista**
1. aria-label for ColorArea inputs on desktop are simply "Color picker."
2. externally set aria-label is prepended to the default accessibility name so that "Color picker" is always included as part of the accessibility name.
3. On first focus, when interacting with the mouse, and on blur, inputs will have aria-valuetext set to channel name and value for both channels.
4. After a keyboard interaction, aria-valuetext will be the channel name and value for the channel that changed.
~5. We still use title to provide all three channel names and values as help text/accessibility description. When we include a color name string, it should be prepended to this.~
5. Remove use of `title` attribute to announce the full RGB/HSL/HSB value. Deferring until we have an API for providing color name.
6. Remove x/y translation string, because it is no longer needed.
7. Fix z-index of ColorLoupe
8. So that only a single "2d slider" control shows up when listing form elements for screen readers, add `aria-hidden="true"` to the unfocused input when the value has not changed via the keyboard, but remove `aria-hidden` to reveal the input for each channel when the value has changed with the keyboard.

Closes #2901 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding React Spectrum GitHub Issue: #2901.
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/5a6c7cb40a9fa380a8618d27d156d9b49da6b9b1/storybook/index.html?path=/story/colorarea--x-blue-y-green and move focus to the Storybook story iframe.
2. Turn on VoiceOver
3. Press Control+Option+U (possibly followed by ArrowRight) to bring up a list of Form Controls in the Storybook story.
4. The first Form Control in the list should be identified as "Blue: 255, Green: 255, foo Color picker, 2d slider"
5. Press ArrowDown to highlight the "Blue: 255, Green: 255, foo Color picker, 2d slider" .
6. Press Enter or Space key to set focus on the "Blue: 255, Green: 255, foo Color picker, 2d slider".
7. Use ArrowLeft to decrease the value for the x-Channel, Blue by 1.
8. VoiceOver will announce the value change as "Blue: 254"
9. Press fn+ArrowDown to trigger a PageDown event, decreasing the value for the y-Channel, Green by its page step, 17.
10. VoiceOver will announce the value change as "Green: 238, foo Color picker, 2d Slider." Note that whenever you change the value along a different axis, the screen reader will announce the accessibility name and role description for the input after the event, because the focus has changed.
11. Use ArrowUp to increase the value for the y-Channel, Green by 1. 
12. VoiceOver will announce the value change as "Green: 239."
13. Press Control+Option+U  to bring up the list of Form Controls in the Storybook story again.
14. The first two Form Controls in the list should be identified as "Blue: 254, foo, Color picker, 2d slider" and "Green 238, foo, Color picker, 2d slider". We show both inputs after a value change using the keyboard, so that both values will be displayed in the list of controls.
15. Press ArrowDown to highlight the "Blue: 254, foo, Color picker, 2d slider" .
16. Press Enter or Space key to set focus on the "Blue: 254, Green: 239, foo, Color picker, 2d slider". Note that VoiceOver announces both the x and y channel names and values, because the focus has now moved from the y-Channel input to the x-Channel input. When you select and restore focus to the same channel input that you just changed using the keyboard, only the channel name and value for that input will be announced.
17. Change the value again using the arrow keys.
18. Use mouse to click on the ColorArea gradient to change the value. Notice that when changing the value using the mouse, VoiceOver will always announces both the x and y channel names and value. 
19. Change the value again using the arrow keys, so VoiceOver announces only the channel name and value for the axis that changed.
20. Press Tab to move focus to the Red channel ColorSlider.
21. Press Shift+Tab to move focus back to the ColorArea.
22. Notice that when restoring focus to the ColorArea VoiceOver again announces both the x and y channel names and values.

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

File: packages/@react-aria/color/src/useColorArea.ts [hunk 1]
```diff
@@ -295,24 +312,38 @@ export function useColorArea(props: ColorAreaAriaProps, state: ColorAreaState):
...
+  }
+
+  let colorPickerLabel = formatMessage('colorPicker');
+  let xChannelLabel = getAriaLabelForChannel(xChannel);
+  let yChannelLabel = getAriaLabelForChannel(yChannel);
+
   let xInputLabellingProps = useLabels({
     ...props,
-    'aria-label': isMobile  ? state.value.getChannelName(xChannel, locale) : formatMessage('x/y', {x: state.value.getChannelName(xChannel, locale), y: state.value.getChannelName(yChannel, locale)})
+    'aria-label': ariaLabel ? `${ariaLabel} ${xChannelLabel}` : xChannelLabel
```
Comment (snowystinger) [inline packages/@react-aria/color/src/useColorArea.ts:329]: is this order true for all locales?

Comment (majornista) [reply packages/@react-aria/color/src/useColorArea.ts:329]: This is the equivalent to the ordering of IDREFs using `aria-labelledby`. `ariaLabel` is the external label, like "foo" in the Storybook example that demonstrates labelling using `aria-label`. the `xChannelLabel` is either "Color picker", on desktop or the channel name, e.g. "Green", on mobile.

Comment (snowystinger) [reply packages/@react-aria/color/src/useColorArea.ts:346]: right, I get that it's the same ordering you'd get joining id's together for aria-labelledby, but doesn't the screen reader put commas between each id in that case? or some sort of pause? here, we're just putting a space?

Comment (majornista) [reply packages/@react-aria/color/src/useColorArea.ts:346]: I could add a comma, if you think it would be appropriate.

**Review by snowystinger — DISMISSED** [review]
lgtm tested in Safari with VO

File: packages/@react-aria/color/src/useColorArea.ts [hunk 2]
```diff
@@ -295,32 +311,59 @@ export function useColorArea(props: ColorAreaAriaProps, state: ColorAreaState):
...
+    return (
+      isMobile || valueChangedViaKeyboard.current ?
+      formatMessage('colorNameAndValue', {name: state.value.getChannelName(channel, locale), value: state.value.formatChannelValue(channel, locale)})
+      :
+      [
+        formatMessage('colorNameAndValue', {name: state.value.getChannelName(xChannel, locale), value: state.value.formatChannelValue(xChannel, locale)}),
+        formatMessage('colorNameAndValue', {name: state.value.getChannelName(yChannel, locale), value: state.value.formatChannelValue(yChannel, locale)})
+      ].join(', ')
+    );
+  }
```
Comment (LFDanLu) [inline packages/@react-aria/color/src/useColorArea.ts:344]: If I'm understanding this correctly, mobile screenreaders will always only announce the current channel's value and name. What if the screen reader user performs a double tap + drag interaction to move the slider handle, should/could we have the screenreader announce both channel values like it does for mouse?

I dunno if this is possible (we would have to distinguish the screen reader double tap + drag interaction). Also, not sure if a screenreader user would usually perform a double tap + drag interaction instead of changing the value of each individual channel using swipe motions but I would guess it could happen

File: packages/@react-spectrum/color/test/ColorArea.test.tsx [hunk 3]
```diff
@@ -62,23 +62,25 @@ describe('ColorArea', () => {
     describe('attributes', () => {
       it('sets input props', () => {
         let {getAllByRole} = render(<Component defaultValue={'#ff00ff'} />);
-        let sliders = getAllByRole('slider');
-
-        let [xSlider, ySlider] = sliders;
+        let [xSlider] = getAllByRole('slider');
+        let ySlider = xSlider.nextElementSibling;
```
Comment (LFDanLu) [inline packages/@react-spectrum/color/test/ColorArea.test.tsx:66]: This is fine for now, but a fyi: if you wanna get the aria-hidden slider you can do `getAllByRole('slider', {hidden: true})` as per https://testing-library.com/docs/queries/byrole/#hidden. Would make it less brittle in case the DOM structure changed in the future and the other slider wasn't a sibling of the first slider

**Review by LFDanLu — COMMENTED** [review]
A question and a note, but I'm happy for this to go in as is. I'll approve the PR based off the discussion of the question

File: packages/@react-spectrum/color/test/ColorArea.test.tsx (hunk 3 above)
Comment (majornista) [reply packages/@react-spectrum/color/test/ColorArea.test.tsx]: See 13133361ad96325b1d3b90770e22c2c08e0c8e90.

File: packages/@react-aria/color/src/useColorArea.ts (hunk 2 above)
Comment (majornista) [reply packages/@react-aria/color/src/useColorArea.ts]: See 13133361ad96325b1d3b90770e22c2c08e0c8e90.

Comment (majornista) [reply packages/@react-aria/color/src/useColorArea.ts]: I've includes both channels in `aria-valuetext` on mobile, and label both inputs as a "Color Picker" and "2d slider" so that users can understand it to interact differently than a regular slider. Double tap and hold allows the user to drag the thumb. On Talkback, value text for both channels gets announced intermittently while dragging and when dragging stops. With VoiceOver for iOS, the value text will not be announced as the value changes, but if the user single taps after finishing the drag,  value text for both channels will announce.

**Review by LFDanLu — APPROVED** [review]
LGTM, confirmed the new mobile behavior. Thanks for the quick update!

**Review by snowystinger — APPROVED** [review]
