### PR TITLE
OverlayContainer createPortal when document is ready

### LINKED ISSUE #1055: OverlayContainer createPortal(contents, document.body) before document is ready(for SSR)
# 🐛 Bug Report 

An error occurred when using OverlayContainer and Next.js in combination. Of course, I also use SSRProvider.

```
Unhandled error during request: ReferenceError: document is not defined
at OverlayContainer (/vercel/4bfb0cda/node_modules/@react-aria/overlays/dist/main.js:672:43)
at d (/vercel/4bfb0cda/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
...

```

The following seems to be the cause.
https://github.com/adobe/react-spectrum/blob/9d3b925ee5bbea9d63db95a53a32d03e9a1a686e/packages/%40react-aria/overlays/src/useModal.tsx#L118

## 🤔 Expected Behavior

Make sure the OverlayContainer component support SSR.

## 😯 Current Behavior

Not working for SSR.

## 💁 Possible Solution

check `document.readyState !== 'loading'`

## 🔦 Context
ref: #1052

## 💻 Code Sample

"next": "^9.5.3"
pages/_app.tsx
```
const MyApp = ({ Component, pageProps }: AppProps) => {
  return (
    <SSRProvider>
      <OverlayContainer>
        <Component {...pageProps} />
      </OverlayContainer>
    </SSRProvider>
  );
};
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/overlays   | 3.3.0 |
| Next.js   | 9.5.3 |

### PR DESCRIPTION
**Pull request by kobayang**
Closes #1055 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

- `useModal.ssr.test.js` checks not to occur any errors on SSR.

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Thanks for the code and test, it appears to be working as expected in non-ssr as well. Tested in Chrome/Safari/Firefox on Mac.

**Comment by reidbarber** [comment]
GET_BUILD

File: packages/@react-aria/overlays/src/useModal.tsx [hunk 1]
```diff
@@ -122,16 +122,25 @@ interface OverlayContainerProps extends ModalProviderProps {
...
+  }, [portalContainer]);
+
+  React.useEffect(() => {
+    if (currentPortalContainer?.closest('[data-overlay-container]')) {
       throw new Error('An OverlayContainer must not be inside another container. Please change the portalContainer prop.');
     }
-  }, [portalContainer]);
+  }, [currentPortalContainer]);
+
+  if (!currentPortalContainer) {
```
Comment (devongovett) [inline packages/@react-aria/overlays/src/useModal.tsx:138]: Why do we need state for this? Won't that introduce an extra render? Could we change the above to `portalContainer = typeof document !== 'undefined' ? document.body : null`, and this to `if (!portalContainer)` instead?

Comment (kobayang) [reply packages/@react-aria/overlays/src/useModal.tsx:138]: This approach seems to work well, but SSR test did not pass because the results of the server render and the client's initial render are different.

```
Warning: Expected server HTML to contain a matching <div> in <div>.
```

ref: https://app.circleci.com/pipelines/github/adobe/react-spectrum/9241/workflows/addeabee-d62d-4f5c-b78a-892173ba46ba/jobs/89756

Comment (devongovett) [reply packages/@react-aria/overlays/src/useModal.tsx:138]: Ah ok. Then I think we can use useIsSSR for this in addition to my previously proposed solution. That will cause a re-render only after hydration, so no extra re-render for client only apps.

Comment (kobayang) [reply packages/@react-aria/overlays/src/useModal.tsx]: https://github.com/adobe/react-spectrum/pull/3186/commits/e68a26ff8c89012909d3f40d44a40869904ca1f5 ✅

File: packages/@react-aria/overlays/src/useModal.tsx [hunk 2]
```diff
@@ -12,6 +12,7 @@
 
 import React, {AriaAttributes, HTMLAttributes, ReactNode, useContext, useEffect, useMemo, useState} from 'react';
 import ReactDOM from 'react-dom';
+import {useIsSSR} from '../../../react-aria';
```
Comment (devongovett) [inline packages/@react-aria/overlays/src/useModal.tsx:15]:
```suggestion
import {useIsSSR} from '@react-aria/ssr';
```

might also need to be added as a dependency.

Comment (kobayang) [reply packages/@react-aria/overlays/src/useModal.tsx]: https://github.com/adobe/react-spectrum/pull/3186/commits/be93533b6d84316629d90e9b0f4405d3d8344826 Add a `@react-aria/ssr` dependency in package.json

**Review by devongovett — APPROVED** [review]
LGTM, thank you!

**Review by snowystinger — APPROVED** [review]

**Comment by eliobricenov** [comment]
Hi, in which NPM package version can I find this fix?

**Comment by snowystinger** [comment]
This will be in our next release, either end of this month or early next month. For now I suggest using patch-package

**Comment by eliobricenov** [comment]
> This will be in our next release, either end of this month or early next month. For now I suggest using patch-package

Thanks
