### PR TITLE
Fix Android TalkBack double tap behavior with TableView/ListView highlight selection

### LINKED ISSUE #2512: Talkback bugs in TableView highlight selection mode
# 🐛 Bug Report 

- In the "selectionStyle: highlight, onAction" ListView story:
using talkback on android, I'm able to toggle selection on a ListView item via double tapping it a couple of times. This triggers onAction a couple of times (which is expected) and then the item gets the selected styles. If you then perform a long press via tap + tap and hold on a different item, you'll be able to see that the previous item is indeed selected.
  - (TableView) Double tapping on a row with TalkBack will select it and fire onAction. Perhaps same as above
- In the "selectionStyle: highlight" TableView story, multiple row selection via Talkback only works if you double tap when focusing a cell. If the entire row is focused and you double tap to select it, it actually unselects all previously selected rows and only selects the current row.
  - Double tapping on a ListView row with TalkBack will occasionally deselect all other rows and select the focused row. This may be the same bug as above

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #2512 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Go to the ListView/TableView "selectionStyle: highlight" story
2. Using Android TalkBack, select a row via moving the cursor to a row cell and double tapping
3. Move the cursor to a new row and double tap. Verify that the previously selected row isn't deselected and that the new row is selected as well
4. Go to the ListView/TableView "selectionStyle: highlight, onAction" story 
5. Move the cursor to the row. If in the ListView story do this by tapping on a row and swiping left once (this moves the cursor from the cell to the row) 
6. Double tap. Verify that onAction is fired and the row isn't selected

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-aria/interactions/src/usePress.ts [hunk 1]
```diff
@@ -740,5 +740,9 @@ function shouldPreventDefault(target: Element) {
 
 function isVirtualPointerEvent(event: PointerEvent) {
   // If the pointer size is zero, then we assume it's from a screen reader.
-  return event.width === 0 && event.height === 0;
+  // Android TalkBack double tap will sometimes return a event with width and height of 1 so we need to check for a specific combo of buttons, type, and pressure.
+  // According to https://w3c.github.io/pointerevents/#dom-pointerevent-pressure, devices that don't support pressure measures will always return .5 if there is an active button
+  // so this check will return false for mouse clicks. Touch events have a pressure of 1 so this will return false as well so TalkBack double tap is the only combo that will
+  // have pressure = 0 and buttons = 1.
+  return (event.width === 0 && event.height === 0) || (event.buttons === 1 && event.type === 'pointerdown' && event.pressure === 0);
```
Comment (LFDanLu) [inline packages/@react-aria/interactions/src/usePress.ts:747]: not thrilled about this but this seems like a combination unique to Android talkback double tap. Trying to see if I can repro the TalkBack behavior outside our code

Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:747]: also note I've restricted it to `pointerdown`, pressure is 0 for `pointerup` so can't really distinguish between the two. usePress `onPointerUp` uses `state.pointerType` luckily so we get the proper pointer type from detecting the Android TalkBack double tap in `onPointerDown`

**Review by snowystinger — COMMENTED** [review]
This seems to have broken iOS ability to go into long press selection mode. lets get together next week and try to work through it

**Comment by LFDanLu** [comment]
shoot, from what I can tell iPad returns 0 for pressure zzz, lemme see if I can add some other checks to distinguish (worse case I add width === 1 and height === 1)

**Comment by ktabors** [comment]
Is this new with this change or something I haven't seen previously?
image

**Comment by ktabors** [comment]
> @ktabors what repro steps and what stories? I'd be surprised if those were introduced in this PR since there aren't any css changes but maybe the press stuff affects some styles that are applied? Can you reproduce these in main?

Yeah, this are both in master and I didn't recall seeing them before. 

To reproduce both it is basically just tab into the list or table. List shows that is ever row, table is only the top row.

**Comment by LFDanLu** [comment]
@ktabors Would be good to file it in a separate issue if it exists in main.

File: packages/@react-aria/interactions/src/usePress.ts [hunk 2]
```diff
@@ -740,5 +740,17 @@ function shouldPreventDefault(target: Element) {
...
+  // and pointerType === 'mouse' so we need to check for a specific combination of event attributes.
+  return (
+    (event.width === 0 && event.height === 0) ||
+    (event.buttons === 1 &&
+      event.width === 1 &&
+      event.height === 1 &&
+      event.type === 'pointerdown' &&
+      event.pressure === 0 &&
+      event.pointerType === 'mouse' &&
+      event.detail === 0
```
Comment (LFDanLu) [inline packages/@react-aria/interactions/src/usePress.ts:753]: Made this super specific to the Android TalkBack double tap event so that we hopefully don't run into an issue where other pointer events are mistaken as virtual pointer events. A brief rundown:
- Desktop click events share the same `width`, `height`, `type: pointerdown`, and `pointerType === mouse` as the Android TalkBack double tap. The above attributes (i.e. pointerType and pressure) however help distinguish the TalkBack event from touch events
- For devices that don't support pressure measurements, their pointer event usually return .5 matching the following spec: https://w3c.github.io/pointerevents/#dom-pointerevent-pressure. Unfortunately this doesn't happen for Safari pointer events which return `pressure: 0` on touch and desktop
- Mouse clicks in Safari are only distinguishable from the Android TalkBack double tap events via `detail` (i.e. `detail: 1` vs `detail: 0`

Technically I could minimize the check above to be `event.detail === 0 && event.pointerType === 'mouse'` but making it more specific felt safer

Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:753]: Thanks @reidbarber for helping me check, stylus/pen returns `pointerType === 'pen' this check should be ok as well

**Comment by LFDanLu** [comment]
TODO: revert 3ddac42 after testing

**Review by snowystinger — APPROVED** [review]
Tested iOS VO and non-VO, chrome w/VO and non-VO

**Review by snowystinger — DISMISSED** [review]

File: packages/@react-spectrum/table/test/Table.test.js [hunk 3]
```diff
@@ -2394,6 +2432,13 @@ describe('TableView', function () {
         expect(onSelectionChange).not.toHaveBeenCalled();
         expect(onAction).toHaveBeenCalledTimes(1);
         expect(onAction).toHaveBeenCalledWith('Foo 5');
+
+        // Android TalkBack double tap test
```
Comment (ktabors) [inline packages/@react-spectrum/table/test/Table.test.js:2436]: This seems like it should be in a separate test, not a second half of a single tap onAction test. Or rename this.
And should we have a test for a non-android double tap?
Should the android double tap test have both events be android events?

**Review by ktabors — COMMENTED** [review]
I'm finding a couple bugs with this when I test on safari. I confirmed they are in main.

I'm able to get the voiceover selection box on an item, "Item 4", then I double finger tab on item 1 and then all the items get checkboxes. Once I get the checkboxes I'm able to check all the rows. I turn off voiceover and I'm not able to repeat this.

IMG_0734

In voiceover when I double tap on an item, it calls on action on the row above my tap and the row I'm tapping. When in the checkbox selection mode both rows are checked. It's a double tap so it should be the same position. I'm able to confirm this by looking at the addon tab and I see two actions one for each row.

**Comment by LFDanLu** [comment]
@ktabors 
> I'm able to get the voiceover selection box on an item, "Item 4", then I double finger tab on item 1 and then all the items get checkboxes. Once I get the checkboxes I'm able to check all the rows. I turn off voiceover and I'm not able to repeat this.

Are you doing a double tap and keeping your finger pressed down on the second tap? The behavior shown looks like the long press being triggered thus showing those checkboxes. Does a long press not bring up the checkboxes when you turn off voiceover?

> In voiceover when I double tap on an item, it calls on action on the row above my tap and the row I'm tapping. When in the checkbox selection mode both rows are checked. It's a double tap so it should be the same position. I'm able to confirm this by looking at the addon tab and I see two actions one for each row.

Possibly https://bugs.webkit.org/show_bug.cgi?id=223202? Does if you open the story outside the storybook iframe?

Either way, you can file separate issues for these if these occur in main as well, shouldn't be a blocker for this PR.

File: packages/@react-spectrum/table/test/Table.test.js (hunk 3 above)
Comment (LFDanLu) [reply packages/@react-spectrum/table/test/Table.test.js:2436]: I included it here because this test case is testing screen reader tap interactions. The `userEvent.click` done just before this section of code is simulating what VoiceOver will fire on the cell upon a double tap. This block of code simulates the special case of Android TalkBack double tap but IMO still falls under the scope of this test case since it is testing the same interaction.

> And should we have a test for a non-android double tap

The stuff above my code is testing the non-android double tap case

> Should the android double tap test have both events be android events

The code here simulates the pointer event fired upon double tapping w/ Android TalkBack double tap

**Comment by ktabors** [comment]
> Either way,

@LFDanLu For the VO going into the checkbox mode. I can't get long press to work in VO to enter that mode. I'm not leaving my finger down when I double tap, but maybe I'm doing them in rapid enough succession that it is reading a long press?

And for the other one it is probably that Safari bug, but opening it in a window doesn't let me test it because I can't see if onAction is being called when opened in an iframe on mobile. :(

**Review by ktabors — APPROVED** [review]
LGTM, but I wasn't able to test on an Android, just confirming that it works with VO on iPhone Safari

**Comment by LFDanLu** [comment]
Don't merge for now, trying to fix a bug that will happen if this is merged with the datepicker PR

File: packages/@react-aria/interactions/src/usePress.ts [hunk 4]
```diff
@@ -259,7 +259,7 @@ export function usePress(props: PressHookProps): PressResult {
 
           // If triggered from a screen reader or by using element.click(),
           // trigger as if it were a keyboard click.
-          if (!state.ignoreClickAfterPress && !state.ignoreEmulatedMouseEvents && isVirtualClick(e.nativeEvent)) {
+          if (!state.ignoreClickAfterPress && !state.ignoreEmulatedMouseEvents && (state.pointerType === 'virtual' || isVirtualClick(e.nativeEvent))) {
```
Comment (LFDanLu) [inline packages/@react-aria/interactions/src/usePress.ts:262]: This change is specifically to make this PR work with the changes made in https://github.com/adobe/react-spectrum/commit/649ac075260190e88ee6d9de7e32f9646d69d4ac#diff-e93ec4d995a5d193a3779d4879091f2fd9e8199ceffc3d917fa823cfd2622737 (PR: https://github.com/adobe/react-spectrum/pull/2510/)

The above commit defers triggering the press events to `onClick` when `onPointerDown`'s event is a virtual pointer event. The problem that then occurs is that `isVirtualClick` thinks the click event from Android TalkBack double tap is NOT a virtual click because the event has `detail: 1` and `pointerType: 'mouse'`. I would love to make `isVirtualClick` properly detect the Android TalkBack double tap but doesn't seem to be a great way to distinguish the TalkBack click event from a browser click event. Here is a diff (on the left is a browser event, on the right is the Android TalkBack event): https://www.diffchecker.com/ccP88a4H. I could possible use the `pointerType: mouse` + `buttons: 1` + `isPrimary: true` + `type: click` as a way to distinguish the Android TalkBack event from browser clicks and from other pointer events but feels kinda iffy

The above change works around this issue by using `state.pointerType` over the `isVirtualClick` check if it exists since  usePress `onPointerDown` will properly detect the Android TalkBack double as a virtual pointer event and set `state.pointerType` accordingly. `onPointerDown` seems to always fire before `onClick` which seems to be backed up by what is described in the w3 pointer spec.

The Android TalkBack event structure seems to be a bug though as suggested by https://w3c.github.io/pointerevents/#dfn-click-auxclick-and-contextmenu-events which states that "For these events (read as click), all PointerEvent specific attributes (defined in this spec) other than pointerId and pointerType will have their default values". Will file a bug

defaults: https://w3c.github.io/pointerevents/#pointerevent-interface

**Review by snowystinger — COMMENTED** [review]
I think we've broken iOS again, in TableView selectionStyle: highlight, it's no longer replace mode, it's toggle and long pressing doesn't switch to checkboxes

**Review by snowystinger — DISMISSED** [review]
Working in iOS 👍🏻

File: packages/@react-aria/interactions/src/usePress.ts (hunk 4 above)
Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:262]: https://issuetracker.google.com/issues/206039945

File: packages/@react-aria/interactions/src/usePress.ts (hunk 2 above)
Comment (devongovett) [reply packages/@react-aria/interactions/src/usePress.ts:755]: The part that seems the most concerning to me to rely on is `pointerType === 'mouse'`. It seems like a bug that on a touchscreen device it would emit a mouse event, and I fear that this will be fixed and we will be broken again. Is `width === 1 && height === 1 && detail === 0 && pressure === 0` enough? I think the width/height should eliminate real touch events as well as all screen readers other than TalkBack, detail === 0 should eliminate Safari mouse events, and pressure === 0 should eliminate chrome. My Apple Pencil reports events with 0.5 width and height, and a non-zero pressure as well. Any other cases I missed?

File: packages/@react-aria/interactions/src/usePress.ts (hunk 4 above)
Comment (devongovett) [reply packages/@react-aria/interactions/src/usePress.ts:262]: Slightly concerning given that we use `isVirtualClick` in some other places as well... It's weird that Chrome appears to have started emitting `PointerEvent` values for the `click` event rather than `MouseEvent`. Seems like no other browser does this. Looks like it's possibly broken even in desktop VoiceOver in Chrome too (`e.detail === 1`). That might cause issues if the talkback check doesn't also apply to VO?

Comment (devongovett) [reply packages/@react-aria/interactions/src/usePress.ts:262]: Looks like https://groups.google.com/a/chromium.org/g/blink-dev/c/bta50W_Hg24

Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:262]: Yeah, the stuff in that link looks like it matches the [w3c specs for click](https://w3c.github.io/pointerevents/#the-click-auxclick-and-contextmenu-events), perhaps an attempt to move towards a new standard

File: packages/@react-aria/interactions/src/usePress.ts (hunk 2 above)
Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:755]: Yep, I think that should be all since FF/Edge will have pressure === .5 as well. I'm fine w/ `width === 1 && height === 1 && detail === 0 && pressure === 0`, was just wary of a touch event that coincidentally had `width/height ===1` but with the level of precision that those attributes get measured its probably ok haha.

File: packages/@react-aria/interactions/src/usePress.ts (hunk 4 above)
Comment (LFDanLu) [reply packages/@react-aria/interactions/src/usePress.ts:262]: Hm, looks like `buttons: 1` and `isPrimary: true` is the only thing that distinguishes desktop Chrome click vs desktop Chrome VO click for now...

**Review by devongovett — APPROVED** [review]

**Review by dannify — APPROVED** [review]
