### PR TITLE
Slider accessibility name calculation fixes for Chrome (#1148)

### LINKED ISSUE #1231: Slider Accessibility Audit
# 🐛 Bug Report 

Following accessibility related issues have been identified in Slider and RangeSlider:

## 🤔 Expected Behavior

1. `<label>` should always reference the `input` element for the first slider thumb using the `for` attribute, so that clicking the label will focus the slider input control.
2. Minimum/Maximum slider thumb inputs in a two thumb range slider are not be labelled as such using i18n, unless otherwise explicitly labelled.
3. Pressing the `displayValue` should focus the corresponding input.
4. For displayValue, use `<output>` with appropriate `aria-labelledby`, `aria-live="off"` and `htmlFor` referring to the corresponding input to label the output value segments. 
5. Focused slider thumb should always be on top in the z-index order.
6. Update Slider (hooks) examples to implement labelling similar to how Slider and RangeSlider do and to pass text contrast requirements for the text labels.

## 😯 Current Behavior

1. `<label>` incorrectly references the container element with `role="group"` using the `for` attribute, so clicking the label fails to focus the slider input control.
2. Minimum/Maximum slider thumb inputs in a RangeSlider are not be labelled as such using i18n.
3. Pressing the display value does not focus the corresponding input.
4. Slider currently uses a `role="textbox"` with `aria-readonly="true"`, which seems about as appropriate as `output` with `aria-live="off"`, but `output` supports the `htmlFor` attribute making it easy to implement the focus on press behavior using an `onPress` event handler.
5. Slider thumb z-index order currently follows DOM order, so the last thumb is always on top regardless of the current focus, which gets confusing when thumbs overlap.
6. Slider hooks should implement `label[htmlFor]`, `output[htmlFor]`, make use of the localized minimum/maximum strings, and pass WAI-ARIA text contrast requirements.

## 💁 Possible Solution

Suggested fixes have been implemented in https://github.com/adobe/react-spectrum/pull/1148.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |   [v3.0.0-alpha.1 ](https://reactspectrum.blob.core.windows.net/reactspectrum/879cbbdd5031a8d6ac4e91272c8e73d7dd38b0c9/storybook-17/index.html?path=/story/slider--label)
| Browser          | Chrome Version 86.0.4240.183 (Official Build) (x86_64)
| Operating System | macOS 10.15.7 (19H2)

## 🕷 Tracking Issue (optional)

https://github.com/adobe/react-spectrum/pull/1148

### PR DESCRIPTION
**Pull request by majornista**
Per https://github.com/adobe/react-spectrum/pull/1148#pullrequestreview-553088926 and https://bugs.chromium.org/p/chromium/issues/detail?id=1159567

Closes #1231, relates to #1148. Closes #1148. Closes #1231.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 1231](https://github.com/adobe/react-spectrum/issues/1231).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- Filled out test instructions.
- Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

Adobe/accessibility

### CODE REVIEW

**Review by LFDanLu — APPROVED** [review]
LGTM, confirmed that the calculated accessibility name is "Label [Maximum/Minimum]" for the range slider handles.

image

Confirmed that normal sliders announced the same in VoiceOver and that the hook slider 3 thumb stories aria-label story announced the thumb letter properly now

File: packages/@react-aria/slider/src/useSliderThumb.ts [hunk 1]
```diff
@@ -49,10 +50,13 @@ export function useSliderThumb(
   let {addGlobalListener, removeGlobalListener} = useGlobalListeners();
 
   let labelId = sliderIds.get(state);
+  let id = getSliderThumbId(state, index);
+  let thumbId = `${id}-thumb`;
```
Comment (devongovett) [inline packages/@react-aria/slider/src/useSliderThumb.ts:54]:
```suggestion
  let thumbId = ariaLabel ? `${id}-thumb` : undefined;
```

File: packages/@react-aria/slider/src/useSliderThumb.ts [hunk 2]
```diff
@@ -49,10 +50,13 @@ export function useSliderThumb(
...
   const {labelProps, fieldProps} = useLabel({
     ...opts,
-    id: getSliderThumbId(state, index),
-    'aria-labelledby': `${labelId} ${opts['aria-labelledby'] ?? ''}`.trim()
+    id,
+    'aria-label': undefined,
```
Comment (devongovett) [inline packages/@react-aria/slider/src/useSliderThumb.ts:58]: Add a comment to explain what's going on here:

```suggestion
    // Override due to a Chrome bug where aria-labelledby cannot be a self-reference.
    // Instead, we put the label on the thumb element and point to it with aria-labelledby.
    // See https://bugs.chromium.org/p/chromium/issues/detail?id=1159567
    'aria-label': undefined,
```

File: packages/@react-aria/color/src/useColorSlider.ts [hunk 3]
```diff
@@ -37,6 +37,7 @@ export function useColorSlider(props: ColorSliderAriaOptions, state: ColorSlider
   let {containerProps, trackProps, labelProps} = useSlider(props, state, trackRef);
   let {inputProps, thumbProps} = useSliderThumb({
     ...props,
+    'aria-label': undefined,
```
Comment (devongovett) [inline packages/@react-aria/color/src/useColorSlider.ts:40]:
```suggestion
    // Avoid label being repeated on the thumb since it will already be labeled by the group
    'aria-label': undefined,
```

**Review by devongovett — APPROVED** [review]
I suppose we should come up with a more general workaround for other components at some point but this is fine for now.
