### PR TITLE
fix(@react-aria/selection): allow selection on focus in multiple selection mode (#1842)

### LINKED ISSUE #1842: bug(@react-aria/selection): keyboard navigation doesn't work as expected when selectOnFocus is on and selectMode is multiple
# 🐛 Bug Report 

In a selectable collection, if `selectOnFocus` is true, selection should change when navigating with the keyboard. It currently works fine when selectionMode is "single", but for doesn't for multi select collections. 

## 🤔 Expected Behavior
if `selectOnFocus` is true, navigation with keyboard should always set the selection instead of only setting the focus, and it should not depend on selection mode. A few examples of this expected behavior:
- Native html select behavior in multiple mode
- Mac's finder
- List views and tree views in [Java Swing](https://www.javatpoint.com/java-swing) (Intellij IDEs for example, or you can check out `ListDemo` in [Swing examples](https://docs.oracle.com/javase/tutorial/uiswing/examples/components/index.html))

## 😯 Current Behavior

Currently, there is an unnecessary check for selection mode here in https://github.com/adobe/react-spectrum/blob/3a1f15494c22fb9f06de7285f8b920f46f959fac/packages/%40react-aria/selection/src/useSelectableCollection.ts#L124
Which makes it broken in the multi select mode.

## 💁 Possible Solution

Remove check for single selection mode when handling `selectOnFocus`.
Regarding usages in the existing packages, the only place `selectOnFocus` can be `true` is in `useTabList`, which only supports single select mode. So there won't be any breaking change with regard to existing packages in react spectrum libraries.

## 🔦 Context

I'm trying to implement a list which behaves similar to examples mentioned above, which has `selectOnFocus` beahvior and support multi and single select modes.

## 💻 Code Sample

https://codesandbox.io/s/react-forked-r8lee?file=/src/App.tsx

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/selection   |  3.4.0
| Browser          | Not relevant
| Operating System | Not relevant

### PR DESCRIPTION
**Pull request by alirezamirian**
Notes:
- For home and end, there is an additional check for ctrl key, because of which new `navigateToKey` function is not used to handle the focus and selection logic. Not sure about the reasoning behind requiring ctrl key in this case, unlike other actions like page-up and page-down.
- Another bug is also fixed with this change: if selectionMode is multiple, shift key is held down, and we are at the end of the list, extendSelection is called with null, which empties selection. This is not inline with the common behaviour of not changing the selection in this case.
- It might be reasonable to have the logic of "select on focus" encapsulated in `SelectionManager`, and allowed by an option.

Closes #1842

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
   - No tests or storybook for @react-aria/selection, so technically checked, but I would be happy to add some tests.
- [ ] Filled out test instructions.
  - There is no use case in the stories and tests that captures this combination of configuration for selectable lists, so not sure about test instructions. I tested it manually on a code outside react spectrum.
- [x] Updated documentation (if it already exists for this component).
  - No documentation
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)
  - I found [the listbox keyboard interaction practices](https://www.w3.org/TR/wai-aria-practices-1.1/#listbox_kbd_interaction) a little confusing, but it seems it is at least one of the supported behavior modes:
    > Alternative selection model -- moving focus without holding a Shift or Control modifier unselects all selected nodes except the focused node. I think for multiselect lists, this "Alternative selection model" should correspond to `selectOnFocus`.
## 📝 Test Instructions:
There is no use case in the stories and tests that captures this combination of configuration for selectable lists
I can create a codesandbox if needed. Or I can add some unit tests for @react-aria/selection

### CODE REVIEW

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 1]
```diff
@@ -111,88 +111,58 @@ export function useSelectableCollection(options: SelectableCollectionOptions): S
...
-          } else if (shouldFocusWrap) {
-            let wrapKey = delegate.getFirstKey(manager.focusedKey);
-            manager.setFocusedKey(wrapKey);
-            if (manager.selectionMode === 'single' && selectOnFocus) {
-              manager.replaceSelection(wrapKey);
-            }
-          }
-
-          if (e.shiftKey && manager.selectionMode === 'multiple') {
-            manager.extendSelection(nextKey);
```
Comment (alirezamirian) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:136]: Here nextKey can be null/undefined, which means when pressing shift+arrowDown at the end of a multi-select list empties selection, which empties selection. It doesn't seem like an expected behavior and is changed in `navigateToKey`

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 2]
```diff
@@ -201,11 +171,10 @@ export function useSelectableCollection(options: SelectableCollectionOptions): S
           e.preventDefault();
           let firstKey = delegate.getFirstKey(manager.focusedKey, isCtrlKeyPressed(e));
           manager.setFocusedKey(firstKey);
-          if (manager.selectionMode === 'single' && selectOnFocus) {
-            manager.replaceSelection(firstKey);
-          }
           if (isCtrlKeyPressed(e) && e.shiftKey && manager.selectionMode === 'multiple') {
```
Comment (alirezamirian) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:174]: `isCtrlKeyPressed(e)` prevented the use of `navigateToKey` here too.

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 3]
```diff
@@ -111,88 +111,58 @@ export function useSelectableCollection(options: SelectableCollectionOptions): S
...
 
+    const navigateToKey = (key: Key | undefined, childFocus?: FocusStrategy) => {
+      if (key != null) {
+        manager.setFocusedKey(key, childFocus);
+
+        if (e.shiftKey && manager.selectionMode === 'multiple') {
+          manager.extendSelection(key);
+        } else if (selectOnFocus) {
+          manager.replaceSelection(key);
+        }
```
Comment (LFDanLu) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:122]: Just wanna make sure, what is the expected behavior here if `selectionMode` is "multiple" but the shift key isn't held down and `selectOnFocus` is true? It would select the newly focused option and deselect the rest of the options?

Comment (alirezamirian) [reply packages/@react-aria/selection/src/useSelectableCollection.ts:122]: Yes, exactly. 
I found WAI-ARIA Authoring Practices a little confusing about it, but I still think this behavior makes the most sense and is what the native select does too.

**Review by LFDanLu — COMMENTED** [review]
@alirezamirian Tested it out locally and it seems to works well. Some strange behavior when focus wrapping is on + multiple selection is enabled + user wraps goes from the last to first item while holding shift, but this existed prior to your change so no need to handle this in your pull. Team is still discussing the overall behavior change but just wanted to give an update

**Review by LFDanLu — APPROVED** [review]
Going to give this a provisional approval for now. The behavior was review by the team and looked good to us, we've made some followup issues that can be handled outside of this pull. Merging this pull may be delayed until we write some additional tests for ListBox and Table just to make sure we aren't breaking anything with this update.

Thanks for the contribution!

**Review by devongovett — APPROVED** [review]
