### PR TITLE
fix(focus): handle single radio button in FocusScope

### LINKED ISSUE #9569: FocusScope crashes with single radio button in form
### Provide a general summary of the issue here

`FocusScope` throws `TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable` when it contains a form with exactly **one** unchecked radio button.

The bug is in the `isTabbableRadio` function in `@react-aria/focus`. It assumes `form.elements.namedItem()` always returns a `RadioNodeList`, but per the [DOM spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection/namedItem), it returns:
- `RadioNodeList` (iterable) when there are **2+ elements** with the same name
- `Element` (NOT iterable) when there is **exactly 1 element** with that name
- `null` when no elements match

### 🤔 Expected Behavior?

`FocusScope` should handle forms with a single radio button without crashing.

### 😯 Current Behavior

When a `FocusScope` contains a form with exactly one unchecked radio button, the following error is thrown:

```
TypeError: (intermediate value)(intermediate value)(intermediate value) is not iterable
    at isTabbableRadio (FocusScope.mjs:222:16)
    at Object.acceptNode (FocusScope.mjs:579:22)
    ...
```

The error occurs at line 306-307 in `FocusScope.tsx`:
```typescript
let radioList = element.form?.elements?.namedItem(element.name) as RadioNodeList;
radios = [...(radioList ?? [])] as HTMLInputElement[];  // CRASHES here when radioList is Element
```

### 💁 Possible Solution

Check if `namedItem()` returns a single `Element` before spreading:

```typescript
// Before (buggy)
let radioList = element.form?.elements?.namedItem(element.name) as RadioNodeList;
radios = [...(radioList ?? [])] as HTMLInputElement[];

// After (fixed)
let radioList = element.form?.elements?.namedItem(element.name);
if (radioList instanceof Element) {
  radios = [radioList as HTMLInputElement];
} else if (radioList) {
  radios = [...radioList] as HTMLInputElement[];
}
```

### 🔦 Context

Our application has a modal (using `FocusScope`) containing a form where users select from available options rendered as radio buttons. When only one option is available, the form renders a single radio button, which causes this crash.

This is a regression introduced in PR #8488 (merged 2025-07-09) which added the `isTabbableRadio` function.

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/devbox/nice-benz-pyl67f?workspaceId=ws_Sdyx9f621KCtw6eyHa9hZK

1. Create a component that uses `FocusScope` with `contain` prop
2. Inside the FocusScope, add a form with exactly ONE unchecked radio button
3. Render the component
4. Error is thrown

```tsx
import { FocusScope } from 'react-aria';

function BugRepro() {
  return (
    <FocusScope contain restoreFocus autoFocus>
      <div>
        <button>First button</button>
        <form>
          {/* Single radio button triggers the bug */}
          <input type="radio" name="option" value="only" />
          <label>Only Option</label>
        </form>
        <button>Second button</button>
      </div>
    </FocusScope>
  );
}
```

### Version

- `react-aria`: 3.45.0 - `@react-aria/focus`: 3.21.3

### What browsers are you seeing the problem on?

Chrome, Other

### If other, please specify.

All browsers - this is a DOM API behavior, not browser-specific

### What operating system are you using?

macOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by jtstothard**
## Summary
Fixes #9569

`FocusScope` crashes with `TypeError: (intermediate value) is not iterable` when containing a form with exactly one unchecked radio button.

## Root Cause
Per the [DOM spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection/namedItem), `form.elements.namedItem()` returns:
- `RadioNodeList` (iterable) for **2+ elements** with the same name
- `Element` (**NOT** iterable) for **exactly 1 element**
- `null` for no elements

The `isTabbableRadio` function assumed it always returns `RadioNodeList` and tried to spread it, causing the crash.

## Solution
Refactored into two pure functions with proper type narrowing:

```typescript
function getRadiosInGroup(element: HTMLInputElement): HTMLInputElement[] {
  // ...
  const radioList = element.form.elements.namedItem(element.name);
  if (radioList instanceof RadioNodeList) {
    return Array.from(radioList).filter(
      (el): el is HTMLInputElement => el instanceof HTMLInputElement
    );
  }
  if (radioList instanceof HTMLInputElement) {
    return [radioList];
  }
  return [];
}

function isTabbableRadio(element: HTMLInputElement): boolean {
  if (element.checked) {
    return true;
  }
  const radios = getRadiosInGroup(element);
}
```

**Key improvements:**
- Extracted `getRadiosInGroup` as a pure function with early returns
- No `let` declarations - only `const`
- No type casting - uses `instanceof` checks and type predicates
- Explicit return type annotations
- `isTabbableRadio` is now a simple composition

## Testing
- Added regression test for single radio button scenario
- All 58 FocusScope tests pass

## Checklist
- [x] Tests added
- [x] Lint passes
- [x] References issue #9569

### CODE REVIEW

File: packages/@react-aria/focus/src/FocusScope.tsx [hunk 1]
```diff
@@ -295,23 +295,36 @@ function shouldContainFocus(scopeRef: ScopeRef) {
...
   }
-  if (!radios) {
-    return false;
+
+  // namedItem returns RadioNodeList (iterable) for 2+ elements, but a single Element for exactly 1.
+  // https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormControlsCollection/namedItem
+  const radioList = element.form.elements.namedItem(element.name);
+  if (radioList instanceof RadioNodeList) {
+    return Array.from(radioList).filter(
+      (el): el is HTMLInputElement => el instanceof HTMLInputElement
```
Comment (snowystinger) [inline packages/@react-aria/focus/src/FocusScope.tsx]:
```suggestion
  let ownerWindow = getOwnerWindow(element);
  if (radioList instanceof ownerWindow.RadioNodeList) {
    return Array.from(radioList).filter(
      (el): el is HTMLInputElement => el instanceof ownerWindow.HTMLInputElement
```

File: packages/@react-aria/focus/src/FocusScope.tsx [hunk 2]
```diff
@@ -295,23 +295,36 @@ function shouldContainFocus(scopeRef: ScopeRef) {
...
+    );
   }
-  let anyChecked = radios.some(radio => radio.checked);
+  if (radioList instanceof HTMLInputElement) {
```
Comment (snowystinger) [inline packages/@react-aria/focus/src/FocusScope.tsx]:
```suggestion
  if (radioList instanceof ownerWindow.HTMLInputElement) {
```

**Comment by jtstothard** [comment]
@snowystinger thanks for the review, is there any way to add the ready to review tag so others review too?

**Comment by snowystinger** [comment]
thanks for the reminder, it's actually just a tag for myself, has no bearing on when others will review it
