### PR TITLE
fix(#2675): TableView: when renderEmptyTableState select all throws if selected from kb

### LINKED ISSUE #2675: TableView: when renderEmptyTableState `select all` throws if selected from kb
# 🐛 Bug Report 

A multiple selection TableView with a few columns but no items. renderEmptyState is set to render an IllustratedMessage.
With your debugger console open, using the keyboard navigate to the `Select all` checkbox and enter `Space`. You may have to get there by tabbing to the element after the TableView and then tabbing backwards.

## 🤔 Expected Behavior

In this state I would expect this checkbox to be disabled. 
(Similarly I would expect any sort indicators to be disabled but they are not).

## 😯 Current Behavior

```
Uncaught TypeError: Cannot read properties of undefined (reading 'childNodes')
    at $dabf6db3fde4ddfaf13a80216b120e5f$export$TableKeyboardDelegate.getKeyBelow (module.js?537f:80)
    at $dabf6db3fde4ddfaf13a80216b120e5f$export$TableKeyboardDelegate.getKeyForSearch (module.js?537f:223)
    at onKeyDown (module.js?726b:43)
    at HTMLUnknownElement.callCallback (react-dom.development.js?61bb:188)
    at Object.invokeGuardedCallbackDev (react-dom.development.js?61bb:237)
    at invokeGuardedCallback (react-dom.development.js?61bb:292)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js?61bb:306)
    at executeDispatch (react-dom.development.js?61bb:389)
    at executeDispatchesInOrder (react-dom.development.js?61bb:411)
    at executeDispatchesAndRelease (react-dom.development.js?61bb:3278)
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |3.14.0 |
| Browser          | Chrome 96.0.4664.55 |
| Operating System | MacOS 11.2.3 |

## 🧢 Your Company/Team

Adobe/Admin Console

### PR DESCRIPTION
**Pull request by ilumin**
Closes #2675 

As @snowystinger suggest, issue is cause from undefined `firstItem` which is cause from undefined value from `getFirstKey()`.

So, I check nullish `getFirstKey()` on `getKeyBelow()` and also check nullish `key` on `getKeyForSearch()` too.

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues/2675).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

In storybook path `/story/tableview--crud `

- Remove all items 
- Click the select al checkbox 
- Hit spacebar 
  expected no error on console

## 🧢 Your Project:

RSP

### CODE REVIEW

**Review by snowystinger — APPROVED** [review]
Added a test and verified the fix

**Review by LFDanLu — APPROVED** [review]
LGTM, tested locally and confirmed that space/down arrow on the select all checkbox no longer causes an error to be thrown for a empty table

File: packages/@react-aria/table/src/TableKeyboardDelegate.ts [hunk 1]
```diff
@@ -35,7 +35,12 @@ export class TableKeyboardDelegate<T> extends GridKeyboardDelegate<T, TableColle
         return child.key;
       }
 
-      let firstItem = this.collection.getItem(this.getFirstKey());
+      let firstKey = this.getFirstKey();
+      if (!firstKey) {
```
Comment (dannify) [inline packages/@react-aria/table/src/TableKeyboardDelegate.ts:39]: What if key is "0" or empty string? @LFDanLu ?
