### PR TITLE
Fix: Table Header does not support className Prop

### LINKED ISSUE #4420: TableHeader(react-aria-components): Type does not support `className`
# 🐛 Bug Report 

When using `TableHeader` component from `react-aria-components` and trying to pass `className` prop ([as in docs](https://react-spectrum.adobe.com/react-aria/Table.html#tableheader-1)), TypeScript says that `TableHeaderProps` does not support `className` property.

## 🤔 Expected Behavior

User should be able to pass `className` without any type warnings

## 😯 Current Behavior

```ts
Type '{ children: Element[]; className: string; }' is not assignable to type 'IntrinsicAttributes & TableHeaderProps<object>'.
  Property 'className' does not exist on type 'IntrinsicAttributes & TableHeaderProps<object>'
```

## 💁 Possible Solution

Extend `TableHeaderProps` with `RenderProps` or `StyleRenderProps` interface.

## 💻 Code Sample

https://codesandbox.io/s/goofy-marco-r8c6dx?file=/src/App.tsx

### PR DESCRIPTION
**Pull request by akash1412**
Closes   #4420 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/react-aria-components/src/Table.tsx [hunk 1]
```diff
@@ -368,7 +368,7 @@ export function useTableOptions(): TableOptionsContextValue {
   return useContext(TableOptionsContext)!;
 }
 
-export interface TableHeaderProps<T> {
+export interface TableHeaderProps<T> extends StyleRenderProps<T> {
```
Comment (devongovett) [inline packages/react-aria-components/src/Table.tsx:371]: I think this should just extend StyleProps. Otherwise this would have to support a function with T as the argument which doesn't really seem that useful.
