### PR TITLE
fix: Improve consistency of Popover --trigger-width

### LINKED ISSUE #5331: [React Aria Components] `--trigger-width` incorrect if ComboxBox inside Modal
### Provide a general summary of the issue here

When you place a ComboxBox inside of a Modal using Popover, the variable for `--trigger-width` is incorrectly set.

### 🤔 Expected Behavior?

The `--trigger-width` should always update to be the width of the trigger.

### 😯 Current Behavior

From my testing, it seems that it measures when the modal is triggered (and the input is one size). Then the modal finishes rendering contents and they are a different size. However, for some reason the resize observer is not fired.

If I breakpoint at the time this code is run, it is correctly identifying the inputs and their widths (although they are shorter). If I then let it play through, and check the widths of the inputs, they are larger. However, it has not triggered the resize.
https://github.com/adobe/react-spectrum/blob/403ec27bf8f5af6e19529b78782526f680c171ca/packages/react-aria-components/src/ComboBox.tsx#L153-L166C6

### 💁 Possible Solution

Not sure why the resize event isn't being fired.

I have seen some libraries accept a list of dependencies that should trigger recalculation. E.g. a prop that takes an array of references, and if any resize then it recalculates. That doesn't seem like it should be necessary though.

**Update**
After finding that it is because of the scale animation, maybe the ComboBox/Select could detect when inside a Modal/Dialog and update the width when the animation is finished (e.g. `data-entering`).

Alternatively, the simplest option could just be to measure when it is triggered, so it is always up to date based on the current interaction.

### 🔦 Context

I am building a form in a Modal that needs to use a ComoBox

### 🖥️ Steps to Reproduce

https://codesandbox.io/s/react-typescript-forked-2ly428?file=/src/App.tsx

Apologies the styles are a bit yuck, I copied them from the docs.

- Click Signup...
- Click the menu or start typing

### Version

1.0.0-beta.2

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

I also tried the nightly build and same issue

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### LINKED ISSUE #9451: `--trigger-width` does not reflect width of `triggerRef` when `triggerRef` passed to `<Popover>` inside `<Select>`
### Provide a general summary of the issue here

The `--trigger-width` CSS variable of the `<Popover>` component does not always reflect the width of the element passed as the `triggerRef` when `<Popover>` is used inside a `<Select>` component.

For example:

```tsx
import { useRef } from 'react';
import { Button, Group, Popover, Select, SelectValue } from 'react-aria-components';

export function SelectExample() {
  const triggerRef = useRef<HTMLDivElement>(null);

  return (
    <Select>
      <Group ref={triggerRef} style={{ width: 250 }}>
        <SelectValue style={{ width: 200 }}>{({ selectedText }) => selectedText}</SelectValue>
        <Button style={{ width: 50 }}>Open</Button>
      </Group>

      <Popover triggerRef={triggerRef} style={{ width: 'var(--trigger-width)' }} />
    </Select>
  );
}
```

In this case `--trigger-width` will be equal to `50px` (the width of the `<Button>` component), when it should be `250px` (the width of the `<Group>` component). 

### 🤔 Expected Behavior?

The `--trigger-width` CSS custom property on `<Popover>` should always reflect the width of the element provided to the `triggerRef` prop of `<Popover>`.

### 😯 Current Behavior

The `--trigger-width` CSS custom property on `<Popover>` does not always reflect the width of the element provided to the `triggerRef` prop of `<Popover>`.

### 💁 Possible Solution

`--trigger-width` is computed based on the internal `buttonRef` created inside the `<Select>` component here: https://github.com/adobe/react-spectrum/blob/953488a1a691c9693c4a49199e48ef3bc930740a/packages/react-aria-components/src/Select.tsx#L146-L176

This is passed to the `PopoverContext` here:
https://github.com/adobe/react-spectrum/blob/953488a1a691c9693c4a49199e48ef3bc930740a/packages/react-aria-components/src/Select.tsx#L208-L216

I wonder if this logic could be moved into [Popover.tsx](https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Popover.tsx) itself?

This logic is also duplicated in at least two places:
- [Dialog.tsx](https://github.com/adobe/react-spectrum/blob/953488a1a691c9693c4a49199e48ef3bc930740a/packages/react-aria-components/src/Dialog.tsx#L58-L69)
- [Select.tsx](https://github.com/adobe/react-spectrum/blob/953488a1a691c9693c4a49199e48ef3bc930740a/packages/react-aria-components/src/Select.tsx#L165-L176)

### 🔦 Context

I am following the example for using a `<TagGroup>` inside a `<Select>` as described in the docs here: https://react-aria.adobe.com/Select#taggroup

The example provides a custom `triggerRef` to the `<Popover>` which is a ref to the containing `<Group>` element in order to correctly position the popover - this works well.

In order to handle dynamic field widths, it would be great to use the `--trigger-width` custom property, rather than using a fixed width for the input+popover as the example does.

As a workaround, I have duplicated the code from [Select.tsx](https://github.com/adobe/react-spectrum/blob/953488a1a691c9693c4a49199e48ef3bc930740a/packages/react-aria-components/src/Select.tsx#L165-L176) to calculate `--trigger-width` into my component and used the `triggerRef` as the observed element. I am then overriding the `style` prop on the `<Popover>` to set `--trigger-width` to the correct width.

### 🖥️ Steps to Reproduce

Take the [`TagGroup` example from the docs](https://react-aria.adobe.com/TagGroup#taggroup).

Delete the fixed width of `250px` from the `<Popover>` style prop and open the popover.

### Version

1.14.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by devongovett**
Closes #9451, closes #5331

Updates the behavior of the Popover `--trigger-width` CSS variable so it works consistently. Instead of being set by each trigger component, it is now set within `Popover`. This means:

* It respects the `triggerRef` prop in case positioning is re-targeted
* It is measured when the popover first opens instead of when the trigger is rendered, fixing issues with triggers nested inside modals with scale animations (#5331)
* It works with standalone popovers, which are rendered without a trigger.

In addition, for ComboBox, we now position relative to the `<Group>` element wrapping the input and button, instead of trying to measure both and find the union of their bounding boxes. This provides better default behavior, especially in cases like multi-select ComboBoxes which also add a TagGroup to display the selected items. Previously the menu would move to be positioned near the input rather than the visual grouping around everything. If a Group is not rendered, we fall back to the old behavior.

### CODE REVIEW

File: packages/react-aria-components/src/Popover.tsx [hunk 1]
```diff
@@ -222,10 +223,24 @@ function PopoverInner({state, isExiting, UNSTABLE_portalContainer, clearContexts
     return children;
   }, [renderProps.children, clearContexts]);
 
+  let [triggerWidth, setTriggerWidth] = useState<string | null>(null);
+  let onResize = useCallback(() => {
+    if (props.triggerRef.current) {
```
Comment (snowystinger) [inline packages/react-aria-components/src/Popover.tsx:228]: If I recall, we did it in the parent component because if the order of these was different, it's possible the triggerRef wouldn't be available? I'll have to check later, but I think it was this setup.
```
<Trigger>
  <Popover />
  <Button />
</Trigger>
```

Comment (devongovett) [reply packages/react-aria-components/src/Popover.tsx:228]: hmm I don't think so? refs are attached before effects run

**Comment by nwidynski** [comment]
@snowystinger Linking https://github.com/adobe/react-spectrum/pull/7663#discussion_r1946339166 here, since I had previously addressed these issues. Did anything change as far as the original concerns go?

**Review by snowystinger — APPROVED** [review]

**Comment by devongovett** [comment]
@nwidynski not sure I understand the concern. The PR you linked to is setting `minWidth`, whereas this is setting `--trigger-width`.

**Comment by nwidynski** [comment]
It was more so directed towards the comment about adding a resize observer on every popover mount. I'm not too concerned personally about the performance of that, but linked it since it was mentioned.

Regarding the styling though, I'm not sure I follow why `minWidth` vs CSS variable matters, as far as the concern goes, which was that userland may be relying on the popover being smaller than the custom trigger element. If they styled with `--trigger-width`, their styling may regress , similarly as it would have with `minWidth`, no?

**Comment by devongovett** [comment]
Oh. I actually think the performance might be better than before. Previously the resize observer would be active even when the popover was not open since it lived within the trigger. Now it only measures when the popover first opens.

re. minWidth I think the concern before was that setting a default minWidth via inline styles would override the user's css. doing it via a var is opt-in. nothing is really changing there.

**Review by yihuiliao — APPROVED** [review]
