### PR TITLE
fix: Don't crash on unknown segment types in DateField

### LINKED ISSUE #8017: Got invalid_argument RangeError with zh-CN-u-ca-chinese locale
### Provide a general summary of the issue here

Hello. I'm not sure if there are any recent changes on locale or not. I found that with the latest version of `@react-aria/i18n` on npm, it seems that  `<I18nProvider locale="zh-CN-u-ca-chinese">` is not working on date picker. It works if I change the locale to `zh-CN`. Also working fine with locales like `hi-IN-u-ca-indian`.

Currently in our production, using `zh-CN-u-ca-chinese` seems working fine. See https://www.heroui.com/docs/components/range-calendar#international-calendars

### 🤔 Expected Behavior?

Should render the date picker with correct locale.

### 😯 Current Behavior

It throws `RangeError invalid_argument`, breaking the app.

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

See https://codesandbox.io/p/devbox/strange-jepsen-mf54sp?workspaceId=ws_E9TSdmNxfxGoviy8wSEWyp

### Version

latest

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

HeroUI

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by devongovett**
Closes #8017

Some additional segment types are now returned by `Intl.DateTimeFormat#formatToParts`, including `'yearName'` and `'relatedYear'`. These are mainly returned for the Chinese calendar ([reference](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/formatToParts#named_years)). `Intl.DisplayNames` does not accept these segment types as inputs causing a crash. In addition the rest of our code does not support these and treats them as non-editable. This PR maps these segments to known types to avoid the crash.

While we don't technically support the Chinese calendar in `@internationalized/date` and there is a bunch of other broken behavior at the moment, at least we don't crash on these segment types anymore.

### CODE REVIEW

File: packages/@react-stately/datepicker/src/useDateFieldState.ts [hunk 1]
```diff
@@ -118,9 +118,13 @@ const PAGE_STEP = {
   second: 15
 };
 
-// Node seems to convert everything to lowercase...
 const TYPE_MAPPING = {
-  dayperiod: 'dayPeriod'
+  // Node seems to convert everything to lowercase...
```
Comment (snowystinger) [inline packages/@react-stately/datepicker/src/useDateFieldState.ts:122]: Are you trying on node 22? I'm not seeing the issue in my local node environment
Screenshot 2025-05-22 at 5 40 14 pm

**Review by snowystinger — APPROVED** [review]

File: packages/@react-stately/datepicker/src/useDateFieldState.ts (hunk 1 above)
Comment (devongovett) [reply packages/@react-stately/datepicker/src/useDateFieldState.ts:122]: this was there before. probably from some older version
