### PR TITLE
fix(#2189): Chrome warning about window.navigator.userAgent and window.navigator.platform access

### LINKED ISSUE #2189: Chrome warning about window.navigator.userAgent and window.navigator.platform access
# 🐛 Bug Report 

After adopting `react-aria` (specifically `"@react-aria/button": "^3.3.2"`) in my codebase, I notice that Chrome shows a warning about accessing `window.navigator.userAgent` and `window.navigator.platform`.

## 🤔 Expected Behavior

The warning should not appear.

## 😯 Current Behavior

Chrome (Version 92.0.4515.107 (Official Build) (64-bit)) shows the following warning:

image

Full text:

Audit usage of navigator.userAgent, navigator.appVersion, and navigator.platform
A page or script is accessing at least one of navigator.userAgent, navigator.appVersion, and navigator.platform. In a future version of Chrome, the amount of information available in the User Agent string will be reduced. To fix this issue, replace the usage of navigator.userAgent, navigator.appVersion, and navigator.platform with feature detection, progressive enhancement, or migrate to navigator.userAgentData. Note that for performance reasons, only the first access to one of the properties is shown. 1 source client.js:1 Learn more: [User-Agent String Reduction](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html)

## 💁 Possible Solution

Research options described in [Update on User-Agent String Reduction in Chrome](https://blog.chromium.org/2021/05/update-on-user-agent-string-reduction.html). One viable options may be to migrate to [`navigator.userAgentData`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData).

Access of the offending fields appears localized to https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/platform.ts.

## 🌍 Your Environment

`"@react-aria/button": "^3.3.2"`

Chrome (Version 92.0.4515.107 (Official Build) (64-bit)) 

Ubuntu Linux

### PR DESCRIPTION
**Pull request by majornista**
Use `navigator.userAgentData` when available.

Closes #2189

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 2189](https://github.com/adobe/react-spectrum/issues/2189).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-aria/utils/src/platform.ts [hunk 1]
```diff
@@ -11,27 +11,32 @@
...
-    ? re.test(window.navigator.userAgent)
-    : false;
+  if (typeof window === 'undefined' || window.navigator == null) {
+    return false;
+  }
+  return (
+    window.navigator['userAgentData'] &&
+    window.navigator['userAgentData'].brands.some((brand: {brand: string, version: string}) => re.test(brand.brand))
+  ) ||
+  re.test(window.navigator.userAgent);
```
Comment (majornista) [inline packages/@react-aria/utils/src/platform.ts:21]: First see if [`window.navigator.userAgentData`](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData) is available, and if so, test to see if one or more of the `window.navigator.userAgentData.brands` matches the regexp, otherwise fallback to test the regexp against `window.navigator.userAgent`.

Comment (majornista) [reply packages/@react-aria/utils/src/platform.ts:21]: Note, I use `window.navigator['userAgentData']`, because `userAgentData` is not currently included as a [Navigator property in TypeScript](https://microsoft.github.io/PowerBI-JavaScript/interfaces/_node_modules_typedoc_node_modules_typescript_lib_lib_dom_d_.navigator.html).

File: packages/@react-aria/utils/src/platform.ts [hunk 2]
```diff
@@ -11,27 +11,32 @@
...
 }
 
 function testPlatform(re: RegExp) {
   return typeof window !== 'undefined' && window.navigator != null
-    ? re.test(window.navigator.platform)
+    ? re.test((window.navigator['userAgentData'] || window.navigator).platform)
```
Comment (majornista) [inline packages/@react-aria/utils/src/platform.ts:26]: Favor `window.navigator.userAgentData.platform` over `window.navigator.platform`.

**Review by LFDanLu — DISMISSED** [review]
LGTM, tested on Windows/Mac/Android,Ipad + Chrome, FF, Safari

**Review by snowystinger — APPROVED** [review]
looks good to me with new story on my iPhone, and on my Mac safari/chrome/ff

**Review by snowystinger — APPROVED** [review]

File: packages/@react-aria/utils/src/platform.ts [hunk 3]
```diff
@@ -11,27 +11,31 @@
...
 
 function testUserAgent(re: RegExp) {
-  return typeof window !== 'undefined' && window.navigator != null
-    ? re.test(window.navigator.userAgent)
-    : false;
+  if (typeof window === 'undefined' || window.navigator == null) {
+    return false;
+  }
+  return (
+    window.navigator['userAgentData']?.brands.some((brand: {brand: string, version: string}) => re.test(brand.brand))
```
Comment (devongovett) [inline packages/@react-aria/utils/src/platform.ts:18]: Note: `userAgentData` only is only supported in HTTPS? https://developer.mozilla.org/en-US/docs/Web/API/Navigator/userAgentData

Comment (snowystinger) [reply packages/@react-aria/utils/src/platform.ts:18]: isn't that fine? we prefer to use it, but fall back if not?

**Review by LFDanLu — APPROVED** [review]
LGTM
