### PR TITLE
Fix useViewportSize for SSR environment

### LINKED ISSUE #5057: ReferenceError: window is not defined while use useViewportSize
### Provide a general summary of the issue here

While use `useViewportSize` with SSR i get error `ReferenceError: window is not defined` at:

```ts
function getViewportSize(): ViewportSize {
  return {
    width: visualViewport?.width || window.innerWidth,
    //______________________________^
    height: visualViewport?.height || window.innerHeight,
    //________________________________^
  };
}
```

### 🤔 Expected Behavior?

Should use `useViewportSize` for SSR without errors

### 😯 Current Behavior

Get error for SSR

### 💁 Possible Solution

Maybe use fallback for getting zero values for SSR:

```ts
function getViewportSize(): ViewportSize {
  if (typeof window === 'undefined') {
    return { width: 0, height: 0 }
  }
  
  return {
    width: visualViewport?.width || window.innerWidth,
    height: visualViewport?.height || window.innerHeight,
  };
}
```

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/staging-shadow-t9ck6g (check console errors)

### Version

@react-aria/utils@3.15.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by yarastqt**
Closes #5057

Added `isSSR` check for `getViewportSize` at SSR mode.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/@react-aria/utils/src/useViewportSize.ts [hunk 1]
```diff
@@ -21,7 +22,8 @@ interface ViewportSize {
 let visualViewport = typeof document !== 'undefined' && window.visualViewport;
 
 export function useViewportSize(): ViewportSize {
-  let [size, setSize] = useState(() => getViewportSize());
+  let isSSR = useIsSSR();
+  let [size, setSize] = useState(() => isSSR ? {width: 0, height: 0} : getViewportSize());
```
Comment (yarastqt) [inline packages/@react-aria/utils/src/useViewportSize.ts:26]: I think to add `isSSR` check inside `getViewportSize`, but this function also used in `useEffect` hook (I would have to add extra deps to hook)

Comment (snowystinger) [reply packages/@react-aria/utils/src/useViewportSize.ts:26]: This seems fine, the `useEffect` won't run on the server anyways.

**Review by snowystinger — APPROVED** [review]
Thanks for the test!

**Review by reidbarber — APPROVED** [review]
LGTM, thanks!
