### PR TITLE
Prevent focusedKey from scrolling into view on click/press

### LINKED ISSUE #2285: CardView UX issues
# 🐛 Bug Report 

List of UX issues:
- the item scrolls into view when you click/tap it. Perhaps only do this when keyboard navigating, clicking/tapping the item should preserve the scroll position
  -  This is a larger issue that affects Menu/Table/collection components that use virtualizer
- ~~Removing an item doesn't show an animation~~ Fixed in previous PR
- disabled keys story, arrow key navigate to a disabled card, press space to select, it scrolls the view

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #2285

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-aria/virtualizer/src/Virtualizer.tsx [hunk 1]
```diff
@@ -124,12 +125,16 @@ export function useVirtualizer<T extends object, V, W>(props: VirtualizerOptions
...
   useEffect(() => {
     if (virtualizer.visibleRect.height === 0) {
       return;
     }
 
-    if (focusedKey !== lastFocusedKey.current) {
+    // Only scroll the focusedKey into view if the modality is not pointer to avoid jumps in position when clicking/pressing tall items.
+    // Exception made if focus isn't within the virtualizer (e.g. opening a picker via click should scroll the selected item into view)
+    let modality = getInteractionModality();
+    if (focusedKey !== lastFocusedKey.current && (modality !== 'pointer' || !isFocusWithin.current)) {
```
Comment (LFDanLu) [inline packages/@react-aria/virtualizer/src/Virtualizer.tsx:137]: An alternative to these Virtualizer changes would be to modify the following https://github.com/adobe/react-spectrum/blob/d764bb0570b011bca731b7da1e8f87e2f34b6e32/packages/%40react-spectrum/card/src/CardView.tsx#L106-L111
to have similar pointer modality checking logic to prevent `virtualizer.scrollToItem` from being called. This would then have to replicated in other places like ListBox where deemed necessary...

File: packages/@react-spectrum/card/src/CardView.tsx [hunk 2]
```diff
@@ -195,6 +196,20 @@ function InternalCard(props) {
...
 
+  // Prevent space key from scrolling the CardView if triggered on a disabled item or on a Card in a selectionMode="none" CardView.
+  let allowsInteraction = state.selectionManager.selectionMode !== 'none';
+  let isDisabled = !allowsInteraction || state.disabledKeys.has(item.key);
+
+  let onKeyDown = (e) => {
+    if (e.key === ' ' && isDisabled) {
+      e.preventDefault();
+    }
+  };
```
Comment (LFDanLu) [inline packages/@react-spectrum/card/src/CardView.tsx:207]: Could do a `usePress` call here instead similar to what TableRow does but felt unnecessary since we don't have a active state for the Card

File: packages/@react-spectrum/picker/test/Picker.test.js [hunk 3]
```diff
@@ -403,6 +403,33 @@ describe('Picker', function () {
 
       expect(document.activeElement).toBe(listbox);
     });
+
+    it.skip('scrolls the selected item into view on menu open', function () {
```
Comment (LFDanLu) [inline packages/@react-spectrum/picker/test/Picker.test.js:407]: Quite mystified as to why this test isn't working... will return to it later

File: packages/@react-spectrum/picker/test/Picker.test.js [hunk 4]
```diff
@@ -403,6 +404,36 @@ describe('Picker', function () {
 
       expect(document.activeElement).toBe(listbox);
     });
+
+    it('scrolls the selected item into view on menu open', function () {
+      let scrollToSpy = jest.fn();
+      let virtualizerMock = jest.spyOn(Virtualizer.prototype, 'scrollToItem').mockImplementationOnce(scrollToSpy);
```
Comment (LFDanLu) [inline packages/@react-spectrum/picker/test/Picker.test.js:410]: Best I could come up with, everything else I tried to make the Picker dropdown actually bring "Four" into view didn't quite work so instead I check that the scrollToSpy is being called with the correct key. Open to suggestions on how to actually make the Picker dropdown perform properly...

File: packages/@react-aria/virtualizer/src/Virtualizer.tsx (hunk 1 above)
Comment (ktabors) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:137]: I think the above logic of checking the focused item and the type of not pointer works. That is clearer for me to understand than your alternative.

File: packages/@react-spectrum/card/src/CardView.tsx (hunk 2 above)
Comment (ktabors) [reply packages/@react-spectrum/card/src/CardView.tsx:207]: Could this be in react-aria? This can't be moved to CardView can it? I'm asking if we care about preventing space from scrolling when a card isn't in a CardView. What prompted me to ask this is I was thinking we should already know if a card is "disabled", but within a CardView we'd have to ask the card (really CardView state which stores this info for the card.

File: packages/@react-spectrum/card/src/CardView.tsx [hunk 5]
```diff
@@ -195,6 +196,20 @@ function InternalCard(props) {
...
+
+  let rowProps = mergeProps(
```
Comment (ktabors) [inline packages/@react-spectrum/card/src/CardView.tsx:209]: rowProps seems like a weird name

File: packages/@react-spectrum/card/test/CardView.test.js [hunk 6]
```diff
@@ -1164,4 +1164,33 @@ describe('CardView', function () {
       expect(row.parentNode.style.height).toBe(`${mockHeight}px`);
     });
   });
+
+  // TODO: not testing waterfall layout because of aforementioned issue with the heights for each card being set to 0 for that layout
```
Comment (ktabors) [inline packages/@react-spectrum/card/test/CardView.test.js:1168]: Should this comment be changed to not say `todo`? Or a followup issue created?

File: packages/@react-spectrum/card/test/CardView.test.js [hunk 7]
```diff
@@ -1164,4 +1164,33 @@ describe('CardView', function () {
...
+  it.each`
+    Name                  | layout
+    ${'Grid layout'}      | ${GridLayout}
+    ${'Gallery layout'}   | ${GalleryLayout}
+  `('$Name CardView should only scroll an item into view when in keyboard modality', function ({layout}) {
```
Comment (ktabors) [inline packages/@react-spectrum/card/test/CardView.test.js:1173]: Second test to confirm no scroll with pointer event?

File: packages/@react-spectrum/picker/test/Picker.test.js (hunk 4 above)
Comment (ktabors) [reply packages/@react-spectrum/picker/test/Picker.test.js:410]: Would it be better to do a table test instead of a picker test?

**Review by ktabors — COMMENTED** [review]
I tested this with TableView, Picker, and cardView gallery and it worked. I couldn't get this to work with a Menu, I probably wasn't picking examples that used a virtualizer.

File: packages/@react-spectrum/card/src/CardView.tsx (hunk 2 above)
Comment (LFDanLu) [reply packages/@react-spectrum/card/src/CardView.tsx:207]: This could perhaps be moved into `useSelectableItem` to cover general selectable items and into `useCard` for the standalone card but I'll defer that until we feel like this is appropriate behavior for all selectable items and when we finalize standalone cards

File: packages/@react-spectrum/picker/test/Picker.test.js (hunk 4 above)
Comment (LFDanLu) [reply packages/@react-spectrum/picker/test/Picker.test.js:410]: I opted for a picker test since that was the component that caught the issue w/ the original approach.

File: packages/@react-spectrum/card/src/CardView.tsx (hunk 5 above)
Comment (LFDanLu) [reply packages/@react-spectrum/card/src/CardView.tsx:209]: open to suggestions, but felt like it was appropriate here since those props are merged into the "grid row" of the Card

File: packages/@react-spectrum/card/test/CardView.test.js (hunk 6 above)
Comment (LFDanLu) [reply packages/@react-spectrum/card/test/CardView.test.js:1168]: I can create a follow up issue for this

File: packages/@react-spectrum/card/test/CardView.test.js (hunk 7 above)
Comment (LFDanLu) [reply packages/@react-spectrum/card/test/CardView.test.js:1173]: good idea, will add

Comment (LFDanLu) [reply packages/@react-spectrum/card/test/CardView.test.js:1173]: Ah actually I do that in this test: https://github.com/adobe/react-spectrum/pull/2725/files/7b8c56678028193bb1bcf6e621aade9851289351#diff-3ef103560236269b49ca02cc46a7b9f7894b45739ce00c38da98ab4b385abe65R1181-R1186

**Comment by majornista** [comment]
@LFDanLu I've incorporated this PR into #2767 with https://github.com/adobe/react-spectrum/pull/2767/commits/1fa895b57a4880f5458c6dcc91c2417e7c4eedc2

**Review by majornista — DISMISSED** [review]

**Review by ktabors — APPROVED** [review]
Thanks for responding to me questions. LGTM

**Review by ktabors — APPROVED** [review]
LGTM

**Review by majornista — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
LGTM

just one note, i did at one point get into a state where I had to click twice to deselect a card, but I've been unable to reproduce it. It happened to me in chrome emulation mode, and it was always trying to deselect one that was partially scrolled out of view. But given I can't reproduce it, this looks good to me.

Edit: from testing it with Daniel, I can reproduce with some consistency, he cannot reproduce it at all. I used a mouse with a scroll wheel, and it happened most clicking just after scrolling, quickly (time between scroll and click), but not aggressively fast I felt.
