### PR TITLE
fix(#2761): FocusScope: with no tabbable element in scope, restore focus to first focusable element

### LINKED ISSUE #2761: FocusScope loses focus to document.body when focused element is removed from DOM
# 🐛 Bug Report 

There are use cases where an element with focus with a FocusScope gets removed from the DOM and focus becomes lost to the document.body. For example, if a clicking a link or button within a Dialog updates the contents of the Dialog without closing it, and the link or button within the Dialog is no longer present in the Dialog content, focus will be lost to the document.body instead of remaining contained within the FocusScope that contains the Dialog.

## 🤔 Expected Behavior

In most cases, when the element with focus gets removed from the DOM due to user interaction, a component will manage setting focus to the next appropriate element. For example, removing a Tag from a TagGroup should focus the next or previous Tag if one is available. However for cases like the FocusScope for a Dialog, where the appropriate element to receive focus may be difficult to discern should the entire content of the Dialog change, allowing the first "focusable" element within the FocusScope to receive focus when the current focus has been removed could be useful. In this case, focus would be set to the Dialog element itself, as happens by default when a Dialog opens with no other element receiving `autoFocus`.

## 😯 Current Behavior

Focus gets lost to the `document.body` when an element with focus is removed from a FocusScope without explicitly setting focus to another element when the contents of the FocusScope have updated.

## 💁 Possible Solution

Add the boolean prop `allowFocusableFirstInScope` to the FocusScope API, and use this prop to specify how the FocusScope within Dialog should restore focus when the content of the FocusScope changes.

Within `useFocusContainment`, `onBlur` to an element outside of the active scope not contained within the `document.body` should restore focus to the first _focusable_ element within the active scope.

## 🔦 Context

Relates to #728 / #1961 / #2749 / #2592 / #2594

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  @react-aria/focus v3.5.0
| Browser          |  Google Chrome v97.0.4692.71 
| Operating System | macOS 12.1 (21C52)

## 🧢 Your Company/Team

Adobe/Accessibility

## 🕷 Tracking Issue (optional)

#728 / #1961 / #2749 / #2592 / #2594

### PR DESCRIPTION
**Pull request by majornista**
Fallback to include focusable elements when identifying the first focusable element in scope, if not tabbable elements are available in scope.

This is relevant for components like a Dialog, where when the contents of the FocusScope changes, and focus gets lost, we want to restore focus to the Dialog itself, which is focusable but not tabbable.

Closes #2761 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding React Spectrum GitHub Issue #2761.
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test is meant to simulate a dialog whose contents change completely when an element within the dialog is clicked.

1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/da566aa6219c6f6a8cab0123b860b36957b869d0/storybook/index.html?path=/story/focusscope--focusable-first-in-scope
2. Move keyboard focus to "Go to Dialog 2" button and use <kbd>Space</kbd> to click it.
3. Content should update and focus should go to the first tabbable element within the scope, the "Go to Dialog 3" button.
4. Use <kbd>Space</kbd> to click the "Go to Dialog 3" button.
5. Dialog 3 has no tabbable elements in scope, so focus will be set to the first focusable element in scope, the dialog itself.

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

File: packages/@react-aria/focus/src/FocusScope.tsx [hunk 1]
```diff
@@ -288,8 +295,12 @@ function useFocusContainment(scopeRef: RefObject<HTMLElement[]>, contain: boolea
         // Use document.activeElement instead of e.relatedTarget so we can tell if user clicked into iframe
         if (scopeRef === activeScope && !isElementInChildScope(document.activeElement, scopeRef)) {
           activeScope = scopeRef;
-          focusedNode.current = e.target;
-          focusedNode.current.focus();
+          if (document.body.contains(e.target)) {
+            focusedNode.current = e.target;
+            focusedNode.current.focus();
+          } else if (activeScope) {
+            focusFirstInScope(activeScope.current, !allowFocusableFirstInScope);
```
Comment (LFDanLu) [inline packages/@react-aria/focus/src/FocusScope.tsx:302]: In the case of the Dialog (and perhaps other components that have the same kind of issue occur), should an effort be made to focus any tabbable content first and then fall back to any focusable but non tabbable content? I would've been confused as to where focus went in the [test example](https://reactspectrum.blob.core.windows.net/reactspectrum/b76123c5765d9482965ba48288496733ff2a8a39/storybook/index.html?path=/story/focusscope--allow-focusable-first-in-scope) if it didn't have a focus outline, something which our RSP Dialogs don't have I think.

I'm not sure what the expected behavior should be here, mainly speaking from a UX perspective so feel free to correct me if the current behavior is correct. I can see why we may want to do this (i.e. allows the Dialog aria-labelledby to be announced) so I'm fine with the behavior as is as well

Comment (majornista) [reply packages/@react-aria/focus/src/FocusScope.tsx:302]: If we just call `focusFirstInScope(activeScope.current)` the first tabbable element within scope would get focus, and we wouldn't necessarily need an API change adding `allowFocusableFirstInScope`. I added the prop, so the Dialog, which has `tabIndex="-1"` would be able to accept focus, like [the default behavior when the Dialog opens](https://github.com/adobe/react-spectrum/blob/7e8a7f69685139b3574453b424a5ad4c8fa4e808/packages/%40react-aria/dialog/src/useDialog.ts#L35-L54),  when the contents of the FocusScope are replaced. I think focusing the Dialog itself is in some ways preferable to focusing the first tabbable descendant, but for most use cases, a FocusScope should probably prioritize the first tabbable to receive focus.

Comment (majornista) [reply packages/@react-aria/focus/src/FocusScope.tsx:302]: I can make it so that the default behavior of `focusFirstInScope` is to first try tabbables, and if the walker finds no next node within the scope, move on to focusables.

Comment (majornista) [reply packages/@react-aria/focus/src/FocusScope.tsx:302]: @LFDanLu See https://github.com/adobe/react-spectrum/commit/c69858c2b3b64d70957b1984b7c9a4e2a5fdf3d8

**Review by LFDanLu — COMMENTED** [review]
Verified the behavior and confirmed that it is working as described, we should bring this new prop up with the team.

**Comment by majornista** [comment]
@LFDanLu I've simplified this to remove the need for the additional `allowFocusableFirstInScope` prop.

File: packages/@react-aria/focus/test/FocusScope.test.js [hunk 2]
```diff
@@ -1251,4 +1251,46 @@ describe('FocusScope', function () {
...
+        </div>
+      );
+
+      function Item(props) {
+        let focusManager = useFocusManager();
+        let onClick = e => {
+          focusManager.focusNext();
+          act(() => e.target.remove());
+        };
+        return <button {...props} tabIndex={-1} onClick={onClick} />;
```
Comment (LFDanLu) [inline packages/@react-aria/focus/test/FocusScope.test.js:1275]: Is the tabIndex here supposed be before the props spread? Correct me if I'm wrong but I think you were trying to test that clicking "tabbable1" would move focus to "item1" since it is the only tabbable element in the scope?

**Review by LFDanLu — COMMENTED** [review]
Behavior and code looks good to me, just one question about the test

File: packages/@react-aria/focus/test/FocusScope.test.js [hunk 3]
```diff
@@ -1251,4 +1251,46 @@ describe('FocusScope', function () {
...
+      }
+      let focusable = getByTestId('focusable');
+      let tabbable1 = getByTestId('tabbable1');
+      let item1 = getByTestId('item1');
+      let item2 = getByTestId('item2');
+      act(() => tabbable1.focus());
+      expect(document.activeElement).toBe(tabbable1);
+      fireEvent.click(tabbable1);
+      expect(tabbable1).not.toBeInTheDocument();
+      waitFor(() => expect(document.activeElement).toBe(focusable));
```
Comment (LFDanLu) [inline packages/@react-aria/focus/test/FocusScope.test.js:1285]: So I had expected this to fail since the FocusScope logic should have moved focus to "item1" instead of to the dialog since it prioritizes tabbable elements over focusable ones. Did some digging, reproduced the expected behavior in the browser but the test doesn't seem to fire a blur even when the button is removed on click.

Tried to resolve it locally by making the requestAnimationFrame mock async with a setTimeout + jest.fakeTimers and manually firing a blur before the e.target.remove but it breaks the test with `Cannot read property 'createEvent' of null` error on react dom. Will need to dig more. 

If we can't get the test to mimic the browser behavior, I feel like we should drop this test or rewrite it (if possible, dunno if the same error is gonna happen)

Comment (majornista) [reply packages/@react-aria/focus/test/FocusScope.test.js]: @LFDanLu I think I have managed to fix the test with https://github.com/adobe/react-spectrum/pull/2763/commits/a6e485fc4fd2fae38bbd8e1e159e287f678bf943.

File: packages/@react-aria/focus/test/FocusScope.test.js [hunk 4]
```diff
@@ -595,6 +595,57 @@ describe('FocusScope', function () {
...
+        function Item(props) {
+          let focusManager = useFocusManager();
+          let onClick = e => {
+            focusManager.focusNext();
+            act(() => {
+              // remove fails to fire blur event in jest-dom
+              e.target.blur();
+              e.target.remove();
+              jest.runAllTimers();
+            });
```
Comment (LFDanLu) [inline packages/@react-aria/focus/test/FocusScope.test.js:629]: Hrm, using `focusManager.focusNext` means the test is manually focusing the correct button rather than relying on FocusScope's `onBlur` calling `focusFirstInScope` right? 

Don't wanna be too nitpicky with the test and this does test that `focusFirstInScope` gets called onBlur when item2 gets removed so I'm fine with its current state but it would be nice to verify that `focusFirstInScope` prioritizes the tabbable elements in a test. No need to spend too long on it if it is difficult to mock jest-dom in just the right way, can punt for later

**Review by LFDanLu — DISMISSED** [review]
Approving for now if the test turns out too hard to fix

File: packages/@react-aria/focus/test/FocusScope.test.js (hunk 4 above)
Comment (majornista) [reply packages/@react-aria/focus/test/FocusScope.test.js:629]: Without the `focusManager.focusNext`, the focus goes to the `document.body` in the testing environment. I've updated the Storybook story to better demonstrate that removing the last tabbable descendant from the FocusScope will focus the first focusable descendant within the scope.

**Review by LFDanLu — DISMISSED** [review]
LGTM, thanks for updating the story

**Comment by ktabors** [comment]
I was testing something else and I found an issue that I'm not sure if it is related. This PR still has the issue so I'm leaning towards what I found being a different issue, but I wanted to confirm. See below for how to test.

```
Goto "ListView -> Selection -> onAction *" stories.
Click into a folder.
Click on "Root" of the Breadcrumb to go back to the main list.
When you keyboard navigate ListView items, the "Root" of the breadcrumb keeps focus too.
```

**Review by devongovett — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
thanks!
