### PR TITLE
runAfterTransition will call setupGlobalEvents when document is ready

### LINKED ISSUE #1048: runAfterTransition calls setupGlobalEvents before document is ready
# 🐛 Bug Report 

I'm using the `useButton` hook in a project and experienced an error when the bundled javascript is included in the head of the page. 

> Uncaught TypeError: can't access property "addEventListener", document.body is null

## 🤔 Expected Behavior

Event setup side-effects happen when the component / hook is used.

## 😯 Current Behavior

Including `useButton` in the bundle leads to [`setupGlobalEvents`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/runAfterTransition.ts#L74) being called, whether or not the component depending on `useButton` is active on the page. 

```
Uncaught TypeError: can't access property "addEventListener", document.body is null
    $b3e8d5c5f32fa26afa6df1b81f09b6b8$var$setupGlobalEvents module.js:634
    node_modules 13-19d749bd3766408a4b8d.chunk.js:123131
    Webpack 28
module.js:634
    $b3e8d5c5f32fa26afa6df1b81f09b6b8$var$setupGlobalEvents module.js:634
    js module.js:638
    Webpack 29
```

## 💁 Possible Solution

Either call [`setupGlobalEvents`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/utils/src/runAfterTransition.ts#L74) when `runAfterTransition` is invoked, or update `setupGlobalEvents` to confirm the document is interactive (`document.readyState === 'interactive') or wait until `DOMContentLoaded` is fired. 

```ts
if (document.readyState !== 'loading') {
  setupGlobalEvents();
} else {
  document.addEventListener('DOMContentLoaded', setupGlobalEvents);
}
```

## 🔦 Context

I'm trying to building an accessible component to act like a button for an internal design system for my company. `@react-aria/button` looked like a great solution for including all the attributes and behaviors to accomplish this task.

See "Possible Solution" section. 

My current fix for the app is to defer the script for the bundle, but I still see this as a potential [footgun](https://en.wiktionary.org/wiki/footgun) for folks getting started with this project. 

## 💻 Code Sample

https://gist.github.com/HipsterBrown/6480f7cc89afd083fb4aa827d6a89699

## 🌍 Your Environment

Rails 5.1 + Webpacker 4.0.2 + React 16.9.0

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.2.1
| Browser          | Firefox Developer Edition
| Operating System | Macos 10.15.6

### PR DESCRIPTION
**Pull request by HipsterBrown**
Closes #1048

## ✅ Pull Request Checklist:

- [X] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [X] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Link updated package to the example app setup (https://gist.github.com/HipsterBrown/6480f7cc89afd083fb4aa827d6a89699), run `npm start` to start the dev server and make sure the example component renders correctly with no errors in the console.

## 🧢 Your Project:

Betterment / internal design system components.

### CODE REVIEW

**Comment by dannify** [comment]
Thanks @HipsterBrown, this is looking good. We need to make sure our components support SSR so you will probably need to check for the presence of document before using it.

**Comment by matamatanot** [comment]
An error occurred when using OverlayContainer and Next.js in combination. Of course, I also use SSRProvider.


```
Unhandled error during request: ReferenceError: document is not defined
at OverlayContainer (/vercel/4bfb0cda/node_modules/@react-aria/overlays/dist/main.js:672:43)
at d (/vercel/4bfb0cda/node_modules/react-dom/cjs/react-dom-server.node.production.min.js:36:498)
...
```
The following seems to be the cause.
https://github.com/adobe/react-spectrum/blob/9d3b925ee5bbea9d63db95a53a32d03e9a1a686e/packages/%40react-aria/overlays/src/useModal.tsx#L118

File: packages/@react-aria/utils/src/runAfterTransition.ts [hunk 1]
```diff
@@ -71,7 +71,11 @@ function setupGlobalEvents() {
   document.body.addEventListener('transitionend', onTransitionEnd);
 }
 
-setupGlobalEvents();
+if (document?.readyState !== 'loading') {
```
Comment (HipsterBrown) [inline packages/@react-aria/utils/src/runAfterTransition.ts:74]: I'm not sure what version of TypeScript this project is using, but I opted for optional chaining for the first approach.

**Review by devongovett — APPROVED** [review]
