### PR TITLE
fix(#4160): NumberField: screen reader fails to announce negative values with currencySign: 'accounting'

### LINKED ISSUE #4160: NumberField: screen reader fails to announce negative values with currencySign: 'accounting'
# 🐛 Bug Report 

When incrementing or decrementing a NumberField with the value formatted using `currencySign: 'accounting'`, e.g. using parentheses to indicate a negative value, like "($57.00)", screen readers fail to distinguish between a negative value or a positive value when the value changes.

## 🤔 Expected Behavior

NumberField should announce a value like "($57.00)" as "−$57.00" or "negative $57.00."

## 😯 Current Behavior

NumberField fails to distinguish between positive and negative values using `currencySign: 'accounting'` .

## 💁 Possible Solution

Similar to how we replace the hyphen-minus with a true minus symbol at: 
https://github.com/adobe/react-spectrum/blob/9eb87968cf943a94676221729c4b7b8c7e80f26e/packages/%40react-aria/spinbutton/src/useSpinButton.ts#L127-L131

Replace formatting using parentheses with a minus sign as well:

```jsx
  // Replace Unicode hyphen-minus (U+002D) with minus sign (U+2212).
  // This ensures that macOS VoiceOver announces it as "minus" even with other characters between the minus sign
  // and the number (e.g. currency symbol). Otherwise it announces nothing because it assumes the character is a hyphen.
  // In addition, replace the empty string with the word "Empty" so that iOS VoiceOver does not read "50%" for an empty field.
  textValue = 
    textValue === '' ? 
    stringFormatter.format('Empty') : 
    (textValue || `${value}`)
    .trim()
    .replace('-', '\u2212')
    // Replace negative value formatted using currencySign: 'accounting' 
    // with a value that can be announced using a minus sign.
    .replace(/^\((.+)\)$/, '\u2212$1');
```

## 🔦 Context

NumberField Accessibility Audit FY23

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  [@adobe/react-spectrum@3.25.0](https://github.com/adobe/react-spectrum/releases/tag/%40adobe%2Freact-spectrum%403.25.0)
| Browser          |  Chrome Version 110.0.5481.177 (Official Build) (arm64)
| Operating System | macOS Ventura 13.2.1 (22D68)

## 🧢 Your Company/Team

Adobe/Accessibility

## 🕷 Tracking Issue (optional)

A11Y-5852

### PR DESCRIPTION
**Pull request by majornista**
Closes #4160 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/3e5388ac6912b0f3bff0811f6196dd7bfdb58ad1/storybook/index.html?path=/story/numberfield--currency-switcher&providerSwitcher-express=false
2. Select Currency Sign: Accounting from the dropdown
3. With a screen reader running, decrement the NumberInput until negative accounting values are reached.
4. Screen reader should announce "negative" or "minus" before negative accounting value.

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

File: packages/@react-aria/spinbutton/src/useSpinButton.ts [hunk 1]
```diff
@@ -128,7 +128,15 @@ export function useSpinButton(
...
-  textValue = textValue === '' ? stringFormatter.format('Empty') : (textValue || `${value}`).replace('-', '\u2212');
+  textValue =
+    textValue === '' ?
+    stringFormatter.format('Empty') :
+    (textValue || `${value}`)
+    .trim()
+    .replace('-', '\u2212')
+    // Replace negative value formatted using currencySign: 'accounting'
+    // with a value that can be announced using a minus sign.
+    .replace(/^\((.+)\)$/, '\u2212$1');
```
Comment (snowystinger) [inline packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: I can't quite remember, but is there any case where the currency is outside the parenthesis?
like AUD (50.00) or is it always (AUD 50.00) there's also symbol and name

Comment (majornista) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: I checked through each of our locales. There are a number of cases where `currencySign: 'accounting'` does not render using parentheses, but in all the cases that use parentheses, the currency symbol is contained within the parentheses.

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: yeah, if i recall, that's the case with the locales. if there was an issue, it'd be in the English locale but with a different currency and/or numbering system

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: maybe try it with JPY? i remember that one having an accounting currencySign

Comment (devongovett) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: Also this is assuming anything in parenthesis is a negative number, but this hook isn't specific to number field. Maybe we should move this logic into number field instead.

We could also just use a different formatter for the aria value than what we use for the input value, eg without accounting mode enabled. Might be easier and more resilient than regex replacement.

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:139]: that's a much better idea I think, 👍🏻

File: packages/@react-aria/numberfield/src/useNumberField.ts [hunk 2]
```diff
@@ -99,6 +100,16 @@ export function useNumberField(props: AriaNumberFieldProps, state: NumberFieldSt
...
   });
 
+  let numberFormatter = useNumberFormatter(formatOptions);
+  let intlOptions = useMemo(() => numberFormatter.resolvedOptions(), [numberFormatter]);
+
+  // Replace negative textValue formatted using currencySign: 'accounting'
+  // with a textValue that can be announced using a minus sign.
+  let textValue =
+    intlOptions.style = 'currency' && intlOptions.currencySign === 'accounting' ?
+    inputValue.replace(/^\((.+)\)$/, '\u2212$1') :
```
Comment (devongovett) [inline packages/@react-aria/numberfield/src/useNumberField.ts:110]: You could create a separate formatter for the `textValue` that doesn't use accounting and then you wouldn't need this regex. That might be more resilient if for some reason some locales use different formatting for accounting notation.

```js
let textValueFormatter = useNumberFormatter({...formatOptions, currencySign: undefined});
let textValue = useMemo(() => isNaN(state.numberValue) ? '' : textValueFormatter.format(state.numberValue), [textValueFormatter, state.numberValue]);
```

File: packages/@react-aria/spinbutton/src/useSpinButton.ts [hunk 3]
```diff
@@ -128,15 +128,7 @@ export function useSpinButton(
...
-  textValue =
-    textValue === '' ?
-    stringFormatter.format('Empty') :
-    (textValue || `${value}`)
-    .trim()
-    .replace('-', '\u2212')
-    // Replace negative value formatted using currencySign: 'accounting'
-    // with a value that can be announced using a minus sign.
-    .replace(/^\((.+)\)$/, '\u2212$1');
+  textValue = textValue === '' ? stringFormatter.format('Empty') : (textValue || `${value}`).replace('-', '\u2212');
```
Comment (snowystinger) [inline packages/@react-aria/spinbutton/src/useSpinButton.ts:131]: This should also be moved up to useNumberField, because then we can grab the minusSign character and out of `formatToParts`

Comment (devongovett) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:131]: I think the problem was that it _is_ coming from the number formatter, but the screen reader doesn't announce that character right.

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:131]: right, but there may be other minus sign symbols, if we moved it up, we could always replace whatever symbol with the one that we know the screen reader can announce?

Comment (majornista) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:131]: Shouldn't `useSpinButton` handle announcement of the minus sign and "Empty" at this lower level? I can understand moving the currency formatting up, the useNumberField, because that's where we accept `formatOptions`, but it seems to make sense to keep the logic to announce 'minus' here. Are you saying there are three Unicode symbols for the minus sign that screen readers can announce, or three locales that use different symbols for the minus sign, that might have to be replaced with a more robust regex?

Comment (snowystinger) [reply packages/@react-aria/spinbutton/src/useSpinButton.ts:131]: There are around 3 different locale specific minus signs, if I recall correctly.
But now I feel like I'm expanding the scope of this.
So let's keep useSpinButton as it was, and handle the currency negative up in useNumberField as you were doing.

**Review by devongovett — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]

**Comment by devongovett** [comment]
@majornista in testing we noticed a couple issues:

1. NVDA reads e.g. "3 euros, minus 3 euros". I assume it is reading the actual input value (in accounting notation) plus our custom announcement.
2. Talkback announces negative accounting values as "minus Euro 2"

I noticed in the number field code we override the spin button role and all of the associated attributes to work around a VoiceOver issue (according to the comment): https://github.com/adobe/react-spectrum/blob/574a27dbae4f758bc31c969f125eefa9f9ceaf73/packages/%40react-aria/numberfield/src/useNumberField.ts#L216-L223

Maybe we should make this happen only on Apple platforms so that NVDA treats this as a spin button and announces the `aria-valuetext` (which should be set to the non-accounting notation) rather than the input value?
