### PR TITLE
Expose offset and crossOffset in TooltipTrigger

### LINKED ISSUE #941: Tooltip should be placed slightly further from its target
# 🐛 Bug Report 

There should be more space between target and tooltip as seen here https://spectrum.adobe.com/page/tooltip/

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by solimant**
Closes #941

## ✅ Pull Request Checklist:

- [X] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [X] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [X] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:
1. Go to the storybook
2. Select **TooltipTrigger** > _placement: top_
3. Inspect gap between tooltip and button. If the gap is wide enough, the test passes.
4. Select _placement: top with offset_
5. Inspect gap between tooltip and button. If the gap is large (about 50px), the test passes.
6. Select _placement: bottom with crossOffset_
7. Verify that the tooltip is anchored at the bottom right corner of the button.

## 🧢 Your Project:
RSP

### CODE REVIEW

File: packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx [hunk 1]
```diff
@@ -56,6 +59,8 @@ function TooltipTrigger(props: TooltipTriggerProps, ref: DOMRef<HTMLElement>) {
     placement: props.placement || 'right',
     targetRef: tooltipTriggerRef,
     overlayRef,
+    offset: props.offset || DEFAULT_OFFSET,
```
Comment (snowystinger) [inline packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx:62]: We should probably add offset/crossOffset directly to TooltipTriggerProps so that we can annotate them with the default values
Would you mind doing that?

Comment (solimant) [reply packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx:62]: You got it 👍

Comment (solimant) [reply packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx]: @snowystinger - Done. Please have a 👀

File: packages/@react-types/tooltip/src/index.d.ts [hunk 2]
```diff
@@ -16,7 +16,9 @@ import {PositionProps} from '@react-types/overlays';
 
 export interface TooltipTriggerProps extends PositionProps {
   children: ReactElement[],
+  crossOffset?: number,
```
Comment (snowystinger) [inline packages/@react-types/tooltip/src/index.d.ts:19]:
```suggestion
  /**
   * The additional offset applied along the cross axis between the element and its
   * anchor element.
   * @default 0
   */
  crossOffset?: number,
```

File: packages/@react-types/tooltip/src/index.d.ts [hunk 3]
```diff
@@ -16,7 +16,9 @@ import {PositionProps} from '@react-types/overlays';
...
   isDisabled?: boolean,
+  offset?: number,
```
Comment (snowystinger) [inline packages/@react-types/tooltip/src/index.d.ts:21]:
```suggestion
  /**
   * The additional offset applied along the main axis between the element and its
   * anchor element.
   * @default 7
   */
  offset?: number,
```

**Comment by solimant** [comment]
> Made some suggestions just so we don't forget :)

Oops, sorry, my bad. Skipped my mind cuz others weren't documented. Will add them.

**Review by snowystinger — DISMISSED** [review]

**Review by dannify — APPROVED** [review]

File: packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx [hunk 4]
```diff
@@ -21,6 +21,9 @@ import {useOverlayPosition} from '@react-aria/overlays';
 import {useTooltipTrigger} from '@react-aria/tooltip';
 import {useTooltipTriggerState} from '@react-stately/tooltip';
 
+const DEFAULT_OFFSET = 7;
```
Comment (dannify) [inline packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx:24]: where did this 7 come from?

Comment (solimant) [reply packages/@react-spectrum/tooltip/src/TooltipTrigger.tsx:24]: Looks like a magic number :) It was the closest offset that visually matches Spectrum's mocks.

**Review by snowystinger — APPROVED** [review]
