### PR TITLE
Focus first element in scope if nodeToRestore does not exist

### LINKED ISSUE #3128: useDialog autoFocus behavior fails in Storybook example for Modal unmounting trigger example.
# 🐛 Bug Report 

This bug was identified when testing #2445. 

Focus gets lost to the hidden underlying content when a secondary modal opens from a popover that closes when the trigger is clicked.

1. Open chrome://settings/accessibility and enable "Show a quick highlight on the focused object."
2. Open https://reactspectrum.blob.core.windows.net/reactspectrum/76d1f51110088049f05a0eb15d941ce2368d0cb2/storybook/index.html?path=/story/modal--unmounting-trigger
3. Tab to focus the Open Popover button within the Storybook example.
4. Press Space key to open the Popover
5. Chrome's focus highlight should render around the Popover dialog itself.
6. Tab to focus the Open modal button within the Popover.
7. Press Space key to open the Modal
8. The Popover will close in the background.

## 🤔 Expected Behavior

9. Chrome's focus highlight should render around the modal Dialog that opens to replace the Popover when the Dialog receives focus.

## 😯 Current Behavior

9. Chrome's focus highlight does not render around the modal Dialog that opens to replace the Popover, because focus is lost to the document.body.

## 💁 Possible Solution

Replace https://github.com/adobe/react-spectrum/blob/9186a10898028b90a3cd4d48c3b0f96f77982fca/packages/%40react-aria/dialog/src/useDialog.ts#L44

with: 

```tsx
        if (document.activeElement === ref.current || !ref.current.contains(document.activeElement)) {
```

So that if the `ref.current` still does not contain have focus after the `setTimeout` duration, the `useDialog` hook will try to focus it safely.

## 🔦 Context

I identified this as a problem while working on a fix for #2444 in #2445.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  @react-aria/overlays@3.8.2
| Browser          | Google Chrome Version 101.0.4951.54 (Official Build) (arm64)
| Operating System | macOS 12.3.1 (21E258)

## 🧢 Your Company/Team

Adobe/Accessibility

### PR DESCRIPTION
**Pull request by devongovett**
In collaboration with @snowystinger. Builds on #3323.

Closes #3171. Closes #3128.

This fixes a few related issues:

1. In cases like the Modal unmounting trigger story, focus would not move into a Dialog within a DialogContainer. The underlying reason is that DialogContainer is not a child of the Popover in the JSX tree, so the Popover's FocusScope was containing focus within it when the dialog opened ([here](https://github.com/adobe/react-spectrum/blob/9498c7d858b08e03b4c36fac491b9e4434453da0/packages/%40react-aria/focus/src/FocusScope.tsx#L277)). This is fixed by using the currently active scope (i.e. the popover) as the parent scope rather than the parent in the JSX tree, but only if the JSX parent is not already inside the active scope. This way, the focus scope within the dialog appears to be nested within the popover, and focus is allowed to move into it.
2. In cases where the node to restore is deleted from the DOM, and there's no parent focus scope to walk back up to. For example, if you delete a row from a table in the CRUD story, or in the ActionBar examples, focus is lost to the body. This is fixed by wrapping collection components such as Table in a FocusScope, and walking up the scope tree from the dialog until we find a scope that still exists (the table), and then focusing the first item within that scope.
3. In a similar case to (2), the ActionGroup in the CRUD story removes its delete button when nothing is selected, so when restoring focus from the delete dialog, focus should go back to the plus button instead. The fix is the same (wrapping ActionGroup in a FocusScope), but this also required tracking the active scope when both contain and restore are false.

Also related to #3039: focus now goes to the collection element when an item is removed rather than lost to the body, but still would be good to focus a more adjacent row at some point.

To do:

- [x] Add FocusScope around all collection components where items may be deleted
- [ ] Figure out what to do about React Aria examples
- [x] Tests

### CODE REVIEW

**Comment by majornista** [comment]
This seems to resolve #3128, closing #3171, but #2451 to fix focus restoration from the ActionBar to the TableView in [this ActionBar Example](https://reactspectrum.blob.core.windows.net/reactspectrum/b41fe1f79462882433951855ba4b41cf8f77b54a/storybook/index.html?path=/story/actionbar--default&providerSwitcher-toastPosition=bottom), still fails intermittently to scroll the element to which focus should be restored within the TableView back into view when restoring focus from the Close/Cancel button within the ActionBar.

**Comment by devongovett** [comment]
@majornista I think this was fixed by merging in main, which includes https://github.com/adobe/react-spectrum/pull/3168. That will now keep the focused row in the DOM even when scrolled out of view, instead of shifting focus to the collection. I believe what was happening before was that row element was reused when scrolled out of view, and focus was restored back to that instead.

**Comment by majornista** [comment]
> @majornista I think this was fixed by merging in main, which includes #3168. That will now keep the focused row in the DOM even when scrolled out of view, instead of shifting focus to the collection. I believe what was happening before was that row element was reused when scrolled out of view, and focus was restored back to that instead.

Seems to be working as expected now.

**Review by majornista — DISMISSED** [review]

File: packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx [hunk 1]
```diff
@@ -202,29 +203,31 @@ function Breadcrumbs<T>(props: SpectrumBreadcrumbsProps<T>, ref: DOMRef) {
...
-              'spectrum-Breadcrumbs--showRoot': showRoot,
-              'is-disabled': isDisabled
-            },
-            styleProps.className
-          )
-        }>
-        {breadcrumbItems}
-      </ul>
-    </nav>
+    <FocusScope>
```
Comment (devongovett) [inline packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx:206]: is this necessary for breadcrumbs? you can't really launch a dialog from there...

File: packages/@react-spectrum/listbox/src/ListBoxBase.tsx [hunk 2]
```diff
@@ -105,66 +106,69 @@ function ListBoxBase<T>(props: ListBoxBaseProps<T>, ref: RefObject<HTMLDivElemen
...
-                  size="S"
-                  aria-label={state.collection.size > 0 ? stringFormatter.format('loadingMore') : stringFormatter.format('loading')}
-                  UNSAFE_className={classNames(styles, 'spectrum-Dropdown-progressCircle')} />
-              </div>
-            );
-          } else if (type === 'placeholder') {
-            let emptyState = props.renderEmptyState ? props.renderEmptyState() : null;
-            if (emptyState == null) {
-              return null;
-            }
```
Comment (devongovett) [inline packages/@react-spectrum/listbox/src/ListBoxBase.tsx:109]:
```suggestion
```

File: packages/@react-spectrum/tabs/src/Tabs.tsx [hunk 3]
```diff
@@ -116,18 +116,20 @@ function Tabs<T extends object>(props: SpectrumTabsProps<T>, ref: DOMRef<HTMLDiv
...
-        ref={domRef}
-        className={classNames(
-          styles,
-          'spectrum-TabsPanel',
-          `spectrum-TabsPanel--${orientation}`,
-          styleProps.className
-        )}>
-        {props.children}
-      </div>
+      <FocusScope>
```
Comment (devongovett) [inline packages/@react-spectrum/tabs/src/Tabs.tsx:119]: same with this one.

File: packages/@react-spectrum/tag/src/TagGroup.tsx [hunk 4]
```diff
@@ -74,33 +75,35 @@ function TagGroup<T extends object>(props: SpectrumTagGroupProps<T>, ref: DOMRef
...
-          item={item}
-          state={state}
-          isDisabled={isDisabled || state.disabledKeys.has(item?.childNodes[0]?.key)}
-          isRemovable={isRemovable}
-          onRemove={onRemove}>
-          {item.childNodes[0].rendered}
-        </Tag>
-        ))}
-    </div>
+    <FocusScope>
```
Comment (devongovett) [inline packages/@react-spectrum/tag/src/TagGroup.tsx:78]: and this

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 5]
```diff
@@ -353,16 +353,16 @@ export function useSelectableCollection(options: AriaSelectableCollectionOptions
...
+    // If not virtualized, scroll the focused element into view when the focusedKey changes.
+    // When virtualized, Virtualizer handles this internally.
     if (!isVirtualized && manager.focusedKey && scrollRef?.current) {
       let element = scrollRef.current.querySelector(`[data-key="${manager.focusedKey}"]`) as HTMLElement;
       if (element) {
         scrollIntoView(scrollRef.current, element);
       }
     }
-  }, [isVirtualized, scrollRef, manager.focusedKey]);
+  }, [isVirtualized, scrollRef, manager, delegate, selectOnFocus]);
```
Comment (LFDanLu) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:365]: what is this change specifically for?

File: packages/@react-aria/focus/src/FocusScope.tsx [hunk 6]
```diff
@@ -85,8 +85,12 @@ export function FocusScope(props: FocusScopeProps) {
...
   let scopeRef = useRef<Element[]>([]);
   let ctx = useContext(FocusContext);
-  // if there is no scopeRef on the context, then the parent is the focusScopeTree's root, represented by null
-  let parentScope = ctx?.scopeRef ?? null;
+
+  // The parent scope is based on the JSX tree, using context.
+  // However, if a new scope mounts outside the active scope (e.g. DialogContainer launched from a menu),
+  // we want the parent scope to be the active scope instead.
+  let ctxParent = ctx?.scopeRef ?? null;
+  let parentScope = useMemo(() => activeScope && focusScopeTree.getTreeNode(activeScope) && !isAncestorScope(activeScope, ctxParent) ? activeScope : ctxParent, [ctxParent]);
```
Comment (LFDanLu) [inline packages/@react-aria/focus/src/FocusScope.tsx:93]: Trying to understand the logic here:
- for DialogContainer from menu case, the DialogContainer's FocusScope ctxParent would be null since it is outside the Menu's JSX tree. The parent scope is thus set to the active scope, aka the Menu's FocusScope
- for a nested DialogTrigger case, a nested Dialog's FocusScope ctxParent is its parent Dialog since it is a child in the JSX tree. The activeScope is equal to the ctxParent (aka both are the parent Dialog) and thus we set the parentScope as the activeScope since isAncestorScope still resolves as false
- for a newly mounted FocusScope, activeScope is null so we set parentScope to null

What about when a sibling focus scope mounts when the first sibling scope is active? Wouldn't this evaluate in such a way that parentScope of the second sibling is set to the first sibling scope?

**Review by LFDanLu — COMMENTED** [review]
Seems to work well enough for the various cases I tested (ActionBar, modal unmounting trigger, DialogContainer, nested Dialogs). Got some questions about the some of the code changes/logic

File: packages/@react-aria/focus/src/FocusScope.tsx (hunk 6 above)
Comment (devongovett) [reply packages/@react-aria/focus/src/FocusScope.tsx:93]: It would, yes. This is essentially the DialogContainer + Menu case. For our purposes, I think this is ok. The user would expect focus to return to the previously active scope when the new one unmounts.

Actually, in most cases, the parent should really be the active scope at the time the new scope mounts. The case where this is not true is if multiple nested scopes mount at the same time.

File: packages/@react-aria/selection/src/useSelectableCollection.ts (hunk 5 above)
Comment (devongovett) [reply packages/@react-aria/selection/src/useSelectableCollection.ts:365]: hmm not sure, this seems wrong. Maybe rob remembers. But looks like maybe a merge issue... let me try reverting

File: packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx (hunk 1 above)
Comment (LFDanLu) [reply packages/@react-spectrum/breadcrumbs/src/Breadcrumbs.tsx:206]: Perhaps the intention was to make each of these components send focus back to the collection when the focused element is removed from the DOM (albeit these FocusScopes don't have `restoreFocus` provided to them...)

**Review by LFDanLu — DISMISSED** [review]
approving for testing, we can handle the question regarding the extra FocusScopes as followup

**Review by dannify — DISMISSED** [review]

**Review by dannify — APPROVED** [review]

File: packages/@react-aria/selection/src/useSelectableCollection.ts (hunk 5 above)
Comment (snowystinger) [reply packages/@react-aria/selection/src/useSelectableCollection.ts]: i do not remember, unfortunately, looks like a merge issue though given that those are not values used in the effect

looks like you were able to revert it successfully
