### PR TITLE
fix(#1999): refactor to use SearchAutocomplete and v3 of AlgoliaSearch API

### LINKED ISSUE #1999: Would like to be able to search the docs
# 🙋 Documentation Request
Would like to be able to search the docs

## 🧢 Your Company/Team
Adobe/RSP

### PR DESCRIPTION
**Pull request by majornista**
Closes #1999 replacing #2016 

**From 3/20/23 Testing session:**
- [x] Adds Algolia logo to the ListBox examples on the docs page for ListBox. Appears to be that it adds to the first ListBox on the page. When it does this, it closes the popover and continues to close it on every keystroke. (RS)
- [x] Cannot access the Algolia link via keyboard. Cannot access the Algolia link via VO with keyboard. (RS)
- [x] VO reads "T ableView" if you search "T" and go to the first result, because of the highlighted letter (DG)
- [ ] VO hierarchy not present, so if two pages have the same title, both are read the same way with no indication that they are two separate pages. Might be able to read off the Item description as well. (RS) type in 'example' and navigate the results.
  - Note: Don't have access to descriptions. VO reads both words off (i.e. "Example" then "Radio Group") so should be ok.

Algolia configuration fixes for later:
- [ ] I don't like that a search for "useDialog" shows the hook after a bunch of other pages. Shouldn't the page that matches the search result show before a page that the term is in? (KT)
- [ ] Search logic should be updated to support fuzzy logic. "useComboBox" should be a result if you search "combobox" (RB)
- [ ] There are a bunch of search results edge cases that get weirdness, for example "Content" picks up the section header as well as the component. Devon suggested the keywords aren't being factored in. (KT)

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 1999](https://github.com/adobe/react-spectrum/issues/1999).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test documentation search functionality using https://reactspectrum.blob.core.windows.net/reactspectrum/d5aed9e2838b40d54ba7e7ba7a7a77f8fec212c6/docs/index.html.

## 🧢 Your Project:

RSP

### CODE REVIEW

**Review by solimant — DISMISSED** [review]

File: packages/dev/docs/src/client.js [hunk 1]
```diff
@@ -183,8 +185,100 @@ function Hamburger() {
...
+  let onSubmit = (value, key) => {
+    if (key) {
+      let prediction = predictions.find(prediction => key === prediction.objectID);
+      let url = prediction.url;
+      if (
+        url.includes('https://react-spectrum.adobe.com') &&
+        window.location.hostname === 'localhost') {
+        url = url.replace('https://react-spectrum.adobe.com', window.location.origin);
+      }
+      window.location.href = url;
```
Comment (reidbarber) [inline packages/dev/docs/src/client.js:259]: I think you can simplify this to something like this:
```js
window.location.href = `../${url}`;
```
and links should work across domains

File: packages/dev/docs/src/client.js [hunk 2]
```diff
@@ -183,8 +185,100 @@ function Hamburger() {
...
+          {
+            prediction.content &&
+            <Text slot="description">
+              <span dangerouslySetInnerHTML={{__html: prediction._snippetResult.content.value}} />
+            </Text>
+          }
+        </Item>
+      );
+    });
+    let suggestions = sections.map((section, index) => <Section key={`${index}-lvl0-${section.title}`} title={section.title}>{section.items}</Section>);
```
Comment (reidbarber) [inline packages/dev/docs/src/client.js:232]: Currently, I just see a `<Section>` for "Documentation". It might be nice to have sections that match the site's sections, like React Spectrum, React Aria, React Stately, Releases, Blog, etc. so its organized a bit (if that isn't too difficult to do with this setup)

**Review by reidbarber — COMMENTED** [review]
Just a couple initial comments. This is going to be great to have.

File: packages/dev/docs/src/client.js (hunk 2 above)
Comment (majornista) [reply packages/dev/docs/src/client.js:232]: I think that is something that can be managed through the AlgoliaSearch index setup. I just went with what had been set up already, but I can try to refine the categories.

File: packages/dev/docs/src/client.js [hunk 3]
```diff
@@ -183,8 +185,95 @@ function Hamburger() {
...
+          textValue.push(hierarchy[`lvl${i}`]);
+        }
+      }
+      section.items.push(
+        <Item key={objectID} textValue={textValue.join(' | ')}>
+          <Text><span dangerouslySetInnerHTML={{__html: text.join(' | ')}} /></Text>
+          {
+            prediction.content &&
+            <Text slot="description">
+              <span dangerouslySetInnerHTML={{__html: prediction._snippetResult.content.value}} />
```
Comment (snowystinger) [inline packages/dev/docs/src/client.js:226]: we should really be running this through Purify or something. Just in case Algolia is compromised ever

File: packages/dev/docs/src/client.js [hunk 4]
```diff
@@ -183,8 +185,95 @@ function Hamburger() {
...
+  let onSubmit = (value, key) => {
+    if (key) {
+      let prediction = predictions.find(prediction => key === prediction.objectID);
+      let url = prediction.url;
+      window.location.href = `${window.location.hostname === 'reactspectrum.blob.core.windows.net' ? window.location.href.replace(/(.+\/docs\/)(.+)/, '$1') : '/'}${url.replace('https://react-spectrum.adobe.com/', '')}`;
+    }
+  };
+
+  return (
+    <Provider theme={defaultTheme} role="search">
```
Comment (snowystinger) [inline packages/dev/docs/src/client.js:259]: why do we need this provider? I don't see one for Hamburger

Comment (majornista) [reply packages/dev/docs/src/client.js:259]: `SearchAutocomplete` is a React-Spectrum component it throws an error when `useProvider` props like `scale` are unavailable.

Comment (snowystinger) [reply packages/dev/docs/src/client.js:260]: but Hamburger uses ActionButton? so that should have the same issue right?

Comment (majornista) [reply packages/dev/docs/src/client.js:260]: `ActionButton` does not [call `useListBoxLayout`](https://github.com/adobe/react-spectrum/blob/425afd51e8e2117be37d83cdca15bbe8d869d60d/packages/%40react-spectrum/autocomplete/src/SearchAutocomplete.tsx#L89), which in turn [requires a `Provider`](https://github.com/adobe/react-spectrum/blob/425afd51e8e2117be37d83cdca15bbe8d869d60d/packages/%40react-spectrum/listbox/src/ListBoxBase.tsx#L51).

File: packages/dev/docs/src/client.js [hunk 5]
```diff
@@ -183,8 +186,95 @@ function Hamburger() {
...
+        if (hierarchy[`lvl${i}`]) {
+          text.push(prediction._highlightResult.hierarchy[`lvl${i}`].value);
+          textValue.push(hierarchy[`lvl${i}`]);
+        }
+      }
+      section.items.push(
+        <Item key={objectID} textValue={textValue.join(' | ')}>
+          <Text><span dangerouslySetInnerHTML={{__html: DOMPurify.sanitize(text.join(' | '))}} /></Text>
+          {
+            prediction.content &&
```
Comment (devongovett) [inline packages/dev/docs/src/client.js:225]: Should this be `prediction._snippetResult.content`? I don't see a description displayed, and some of the results seem to be duplicated. Maybe because they are different parts of the same page that are meant to be highlighted?

Screen Shot 2022-08-30 at 4 37 42 PM

File: packages/dev/docs/src/client.js [hunk 6]
```diff
@@ -183,8 +186,95 @@ function Hamburger() {
...
+      let url = prediction.url;
+      window.location.href = `${window.location.hostname === 'reactspectrum.blob.core.windows.net' ? window.location.href.replace(/(.+\/docs\/)(.+)/, '$1') : '/'}${url.replace('https://react-spectrum.adobe.com/', '')}`;
+    }
+  };
+
+  return (
+    <Provider theme={defaultTheme} role="search">
+      <SearchAutocomplete
+        aria-label="Search"
+        placeholder="Search"
```
Comment (devongovett) [inline packages/dev/docs/src/client.js:263]: Do we want this? It doesn't pass contrast, and there is a console warning.

File: packages/dev/docs/src/client.js (hunk 2 above)
Comment (majornista) [reply packages/dev/docs/src/client.js]: See 42e258bf524db9531272964579e9564c22a8ff47

File: packages/dev/docs/src/client.js (hunk 5 above)
Comment (majornista) [reply packages/dev/docs/src/client.js:249]: See 42e258bf524db9531272964579e9564c22a8ff47

Comment (devongovett) [reply packages/dev/docs/src/client.js:249]: I'm still not seeing a description. I see above you check for `prediction.content` but below use `prediction._snippetResult.content`. Should these match?

Comment (majornista) [reply packages/dev/docs/src/client.js:249]: `prediction.content` is the unformatted content string, for hits without a description `prediction.content` is `null` and `prediction._snippetResult.content` will not exist. Some hits will not include a description, like for example when the query is returned as part of a heading at any level. When the hit is returned from body content, it will include `prediction.content` and `prediction._snippetResult.content.value` will contain the content formatted as an html string, including the `mark` tag that highlights the query in context.

Comment (majornista) [reply packages/dev/docs/src/client.js:249]: Example of JSON returned for "DateRangePicker" `H1` hit, which has `"content": null`:
```json
    {
      "version": "",
      "tags": [],
      "url": "https://react-spectrum.adobe.com/react-spectrum/DateRangePicker.html#daterangepicker",
      "url_without_variables": "https://react-spectrum.adobe.com/react-spectrum/DateRangePicker.html#daterangepicker",
      "url_without_anchor": "https://react-spectrum.adobe.com/react-spectrum/DateRangePicker.html",
      "anchor": "daterangepicker",
      "content": null,
      "content_camel": null,
      "lang": "en-US",
      "language": "en-US",
      "type": "lvl1",
      "no_variables": false,
      "weight": {
        "pageRank": "0",
        "level": 90,
        "position": 0
      },
      "hierarchy": {
        "lvl0": "Documentation",
        "lvl1": "DateRangePicker",
        "lvl2": null,
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "recordVersion": "v2",
      "hierarchy_radio": {
        "lvl0": null,
        "lvl1": "DateRangePicker",
        "lvl2": null,
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "hierarchy_camel": [
        {
          "lvl0": "Documentation",
          "lvl1": "DateRangePicker",
          "lvl2": null,
          "lvl3": null,
          "lvl4": null,
          "lvl5": null,
          "lvl6": null
        }
      ],
      "hierarchy_radio_camel": {
        "lvl0": null,
        "lvl1": "DateRangePicker",
        "lvl2": null,
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "objectID": "0-https://react-spectrum.adobe.com/react-spectrum/DateRangePicker.html",
      "_snippetResult": {
        "version": {
          "value": "",
          "matchLevel": "none"
        },
        "url": {
          "value": "https://react-spectrum.adobe.com/react-spectrum/<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker.html#<mark class="algolia-docsearch-suggestion--highlight">date</mark>rangepicker",
          "matchLevel": "full"
        },
        "url_without_variables": {
          "value": "https://react-spectrum.adobe.com/react-spectrum/<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker.html#<mark class="algolia-docsearch-suggestion--highlight">date</mark>rangepicker",
          "matchLevel": "full"
        },
        "url_without_anchor": {
          "value": "https://react-spectrum.adobe.com/react-spectrum/<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker.html",
          "matchLevel": "full"
        },
        "anchor": {
          "value": "<mark class="algolia-docsearch-suggestion--highlight">date</mark>rangepicker",
          "matchLevel": "full"
        },
        "lang": {
          "value": "en-US",
          "matchLevel": "none"
        },
        "language": {
          "value": "en-US",
          "matchLevel": "none"
        },
        "type": {
          "value": "lvl1",
          "matchLevel": "none"
        },
        "weight": {
          "pageRank": {
            "value": "0",
            "matchLevel": "none"
          },
          "level": {
            "value": "90",
            "matchLevel": "none"
          },
          "position": {
            "value": "0",
            "matchLevel": "none"
          }
        },
        "hierarchy": {
          "lvl0": {
            "value": "Documentation",
            "matchLevel": "none"
          },
          "lvl1": {
            "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
            "matchLevel": "full"
          }
        },
        "recordVersion": {
          "value": "v2",
          "matchLevel": "none"
        },
        "hierarchy_radio": {
          "lvl1": {
            "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
            "matchLevel": "full"
          }
        },
        "hierarchy_camel": [
          {
            "lvl0": {
              "value": "Documentation",
              "matchLevel": "none"
            },
            "lvl1": {
              "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
              "matchLevel": "full"
            }
          }
        ],
        "hierarchy_radio_camel": {
          "lvl1": {
            "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
            "matchLevel": "full"
          }
        }
      },
      "_highlightResult": {
        "hierarchy": {
          "lvl0": {
            "value": "Documentation",
            "matchLevel": "none",
            "matchedWords": []
          },
          "lvl1": {
            "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
            "matchLevel": "full",
            "fullyHighlighted": false,
            "matchedWords": [
              "date"
            ]
          }
        },
        "hierarchy_camel": [
          {
            "lvl0": {
              "value": "Documentation",
              "matchLevel": "none",
              "matchedWords": []
            },
            "lvl1": {
              "value": "<mark class="algolia-docsearch-suggestion--highlight">Date</mark>RangePicker",
              "matchLevel": "full",
              "fullyHighlighted": false,
              "matchedWords": [
                "date"
              ]
            }
          }
        ]
      },
      "_rankingInfo": {
        "nbTypos": 0,
        "firstMatchedWord": 4000,
        "proximityDistance": 0,
        "userScore": 6336,
        "geoDistance": 0,
        "geoPrecision": 1,
        "nbExactWords": 0,
        "words": 1,
        "filters": 0
      }
    }
```

Comment (majornista) [reply packages/dev/docs/src/client.js:249]: And here is the example JSON for "useTimeField > Anatomy", which includes `content`:

```json
    {
      "version": "",
      "tags": [],
      "url": "https://react-spectrum.adobe.com/react-aria/useTimeField.html#anatomy",
      "url_without_variables": "https://react-spectrum.adobe.com/react-aria/useTimeField.html#anatomy",
      "url_without_anchor": "https://react-spectrum.adobe.com/react-aria/useTimeField.html",
      "anchor": "anatomy",
      "content": "useDateSegment returns props for an individual time segment:",
      "content_camel": "useDateSegment returns props for an individual time segment:",
      "lang": "en-US",
      "language": "en-US",
      "type": "content",
      "no_variables": false,
      "weight": {
        "pageRank": "0",
        "level": 0,
        "position": 15
      },
      "hierarchy": {
        "lvl0": "Documentation",
        "lvl1": "useTimeField",
        "lvl2": "Anatomy",
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "recordVersion": "v2",
      "hierarchy_radio": {
        "lvl0": null,
        "lvl1": null,
        "lvl2": null,
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "hierarchy_camel": [
        {
          "lvl0": "Documentation",
          "lvl1": "useTimeField",
          "lvl2": "Anatomy",
          "lvl3": null,
          "lvl4": null,
          "lvl5": null,
          "lvl6": null
        }
      ],
      "hierarchy_radio_camel": {
        "lvl0": null,
        "lvl1": null,
        "lvl2": null,
        "lvl3": null,
        "lvl4": null,
        "lvl5": null,
        "lvl6": null
      },
      "objectID": "15-https://react-spectrum.adobe.com/react-aria/useTimeField.html",
      "_snippetResult": {
        "version": {
          "value": "",
          "matchLevel": "none"
        },
        "url": {
          "value": "https://react-spectrum.adobe.com/react-aria/useTimeField.html#anatomy",
          "matchLevel": "none"
        },
        "url_without_variables": {
          "value": "https://react-spectrum.adobe.com/react-aria/useTimeField.html#anatomy",
          "matchLevel": "none"
        },
        "url_without_anchor": {
          "value": "https://react-spectrum.adobe.com/react-aria/useTimeField.html",
          "matchLevel": "none"
        },
        "anchor": {
          "value": "anatomy",
          "matchLevel": "none"
        },
        "content": {
          "value": "use<mark class="algolia-docsearch-suggestion--highlight">Date</mark>Segment returns props for an individual time segment:",
          "matchLevel": "full"
        },
        "content_camel": {
          "value": "useDateSegment returns props for an individual time segment:",
          "matchLevel": "none"
        },
        "lang": {
          "value": "en-US",
          "matchLevel": "none"
        },
        "language": {
          "value": "en-US",
          "matchLevel": "none"
        },
        "type": {
          "value": "content",
          "matchLevel": "none"
        },
        "weight": {
          "pageRank": {
            "value": "0",
            "matchLevel": "none"
          },
          "level": {
            "value": "0",
            "matchLevel": "none"
          },
          "position": {
            "value": "15",
            "matchLevel": "none"
          }
        },
        "hierarchy": {
          "lvl0": {
            "value": "Documentation",
            "matchLevel": "none"
          },
          "lvl1": {
            "value": "useTimeField",
            "matchLevel": "none"
          },
          "lvl2": {
            "value": "Anatomy",
            "matchLevel": "none"
          }
        },
        "recordVersion": {
          "value": "v2",
          "matchLevel": "none"
        },
        "hierarchy_camel": [
          {
            "lvl0": {
              "value": "Documentation",
              "matchLevel": "none"
            },
            "lvl1": {
              "value": "useTimeField",
              "matchLevel": "none"
            },
            "lvl2": {
              "value": "Anatomy",
              "matchLevel": "none"
            }
          }
        ]
      },
      "_highlightResult": {
        "content": {
          "value": "use<mark class="algolia-docsearch-suggestion--highlight">Date</mark>Segment returns props for an individual time segment:",
          "matchLevel": "full",
          "fullyHighlighted": false,
          "matchedWords": [
            "date"
          ]
        },
        "hierarchy": {
          "lvl0": {
            "value": "Documentation",
            "matchLevel": "none",
            "matchedWords": []
          },
          "lvl1": {
            "value": "useTimeField",
            "matchLevel": "none",
            "matchedWords": []
          },
          "lvl2": {
            "value": "Anatomy",
            "matchLevel": "none",
            "matchedWords": []
          }
        },
        "hierarchy_camel": [
          {
            "lvl0": {
              "value": "Documentation",
              "matchLevel": "none",
              "matchedWords": []
            },
            "lvl1": {
              "value": "useTimeField",
              "matchLevel": "none",
              "matchedWords": []
            },
            "lvl2": {
              "value": "Anatomy",
              "matchLevel": "none",
              "matchedWords": []
            }
          }
        ]
      },
      "_rankingInfo": {
        "nbTypos": 0,
        "firstMatchedWord": 28001,
        "proximityDistance": 0,
        "userScore": 2293,
        "geoDistance": 0,
        "geoPrecision": 1,
        "nbExactWords": 0,
        "words": 1,
        "filters": 0
      }
    }
```

Comment (majornista) [reply packages/dev/docs/src/client.js:249]: If you open https://reactspectrum.blob.core.windows.net/reactspectrum/138527ee8b97ab7a7c26afe042ccd6cc8a2dd1f7/docs/index.html and search for a term that is less commonly used in headings, like for example "correct", DocSearch will return more results that include `content`.

File: packages/dev/docs/src/client.js [hunk 7]
```diff
@@ -183,8 +186,121 @@ function Hamburger() {
...
+            prediction.content &&
+            <Text slot="description">
+              <span dangerouslySetInnerHTML={{__html: DOMPurify.sanitize(prediction._snippetResult.content.value)}} />
+            </Text>
+          }
+        </Item>
+      );
+    });
+    let titles = Object.values(sectionTitles);
+    sections.forEach((section, index) => console.log(index, section.title, titles.indexOf(section.title)));
```
Comment (reidbarber) [inline packages/dev/docs/src/client.js:258]: `console.log` can be removed here

**Review by reidbarber — COMMENTED** [review]
Screen Shot 2022-09-07 at 5 40 15 PM

Dark mode isn't working. Not sure if we have a solution for this yet.

File: packages/dev/docs/src/client.js (hunk 5 above)
Comment (devongovett) [reply packages/dev/docs/src/client.js:249]: oh ok. I still haven't managed to find one but I believe you. Got no results for "correct".

**Comment by devongovett** [comment]
In Safari, there's some weird padding on the bottom, and the field is offset. When you start typing, it shifts down. 
image

Also a bit weird that the search field overlaps the content of the page when you scroll down. I guess we could either put a bar up there across the whole page, or move the search field into the sidebar like the spectrum site. That's less convenient on mobile/small screens though since you'd have to go into the hamburger menu first.

File: packages/dev/docs/src/client.js (hunk 5 above)
Comment (majornista) [reply packages/dev/docs/src/client.js:249]: > oh ok. I still haven't managed to find one but I believe you. Got no results for "correct".

Press down arrow to expand the menu and you should see results with "correct" highlighted in the description. I'm not exactly sure why the results hide after entering longer strings, like "correct".

File: packages/dev/docs/src/client.js (hunk 4 above)
Comment (majornista) [reply packages/dev/docs/src/client.js:287]: Ah, ok. I should use `ThemeProvider` from `ThemeSwitcher.js` instead.

**Comment by majornista** [comment]
> In Safari, there's some weird padding on the bottom, and the field is offset. When you start typing, it shifts down. image
> 
> Also a bit weird that the search field overlaps the content of the page when you scroll down. I guess we could either put a bar up there across the whole page, or move the search field into the sidebar like the spectrum site. That's less convenient on mobile/small screens though since you'd have to go into the hamburger menu first.

See a53f8496bfec2dfb161dac36866876eb16f491a1 and test with https://reactspectrum.blob.core.windows.net/reactspectrum/a53f8496bfec2dfb161dac36866876eb16f491a1/docs/index.html

I think `main` content should scroll rather than the `document.body`, this way we won't have cases where focused content, like an anchor, hidden underneath the page header when the page is scrolled.

**Review by reidbarber — DISMISSED** [review]

**Comment by devongovett** [comment]
Maybe there's something we can do in the way the site is scraped to avoid this repetition. For example, searching for a term shows both it and all of its sub-headings:

image

File: packages/dev/docs/src/docs.css [hunk 8]
```diff
@@ -71,6 +71,9 @@
 html, body {
   margin: 0;
   text-size-adjust: none;
+  height: 100vh;
```
Comment (devongovett) [inline packages/dev/docs/src/docs.css:74]: This breaks the mobile layout. 100vh in iOS safari includes the top and bottom toolbars.

**Review by snowystinger — COMMENTED** [review]
two things I think

1. we really need to reduce the number of results. searching for button should not bring up every single sub section on button. maybe some rules around this are, if the search is in the page title, then we only show the result for the page. otherwise we show the subsection

for example, searching for "but" would show React Aria useButton, useToggleButton, React Spectrum ActionButton, Button, ButtonGroup..., and it would not bring up any of the subsections at all

searching for "AriaButton" would bring up React Aria useButton | API, and it would not bring up React Aria useButton

2. The first letter I type on a page refresh doesn't seem to do a search, also sometimes if I type quickly, it won't search at all. I'm not sure what's going on there?

File: packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx [hunk 9]
```diff
@@ -165,7 +165,7 @@ function _SearchAutocompleteBase<T extends object>(props: SpectrumSearchAutocomp
           isLoading={loadingState === 'loadingMore'}
           onLoadMore={onLoadMore}
           renderEmptyState={() => isAsync && (
-            <span>
+            <span className={classNames(searchAutocompleteStyles, 'no-results')}>
```
Comment (snowystinger) [inline packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx:168]: are we still using this classname?

**Review by snowystinger — COMMENTED** [review]
In general, looks good
Though realized we'll need to release the changes to Autocomplete before we can merge the docs changes

File: packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx (hunk 9 above)
Comment (majornista) [reply packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx:168]: I think we are. This was added after I saw misalignment of the no results message when in the Search Autocomplete results. https://github.com/adobe/react-spectrum/pull/3383/commits/67b389878a8c87bf076598b3f2f9a972134a6426

File: packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx [hunk 10]
```diff
@@ -227,7 +227,7 @@ const SearchAutocompleteButton = React.forwardRef(function SearchAutocompleteBut
 
   return (
     <div
-      {...mergeProps(hoverProps, focusProps, buttonProps)}
+      {...mergeProps(buttonProps, focusProps, hoverProps)}
```
Comment (snowystinger) [inline packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx:230]: this got fixed in https://github.com/adobe/react-spectrum/pull/3801
please revert this file

File: packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx (hunk 9 above)
Comment (snowystinger) [reply packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx:168]: then this needs to be in a separate PR so that it gets released and then the docs can make use of it. How bad is the search without this change? bad enough to wait for it? or not noticeable really?
lets get it in before our next release which is coming up soon

File: packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx [hunk 11]
```diff
@@ -165,7 +165,7 @@ function _SearchAutocompleteBase<T extends object>(props: SpectrumSearchAutocomp
           isLoading={loadingState === 'loadingMore'}
           onLoadMore={onLoadMore}
           renderEmptyState={() => isAsync && (
-            <span className={classNames(searchAutocompleteStyles, 'no-results')}>
+            <span>
```
Comment (majornista) [inline packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx]: I think we need this so that `.no-results` is properly styled.

Comment (majornista) [reply packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx]: Unless those changes are part of SearchAutocomplete fixes to be merged before DocSearch.

Comment (reidbarber) [reply packages/@react-spectrum/autocomplete/src/SearchAutocomplete.tsx]: Moved them here: https://github.com/adobe/react-spectrum/pull/4252

File: packages/dev/docs/src/DocSearch.js [hunk 12]
```diff
@@ -0,0 +1,349 @@
...
+      .search(
+        query,
+        searchOptions
+      )
+      .then(updatePredictions);
+  };
+
+  let onSubmit = (value, key) => {
+    if (key === 'algolia-footer-logo') {
+      window.open('https://www.algolia.com/ref/docsearch/?utm_source=react-spectrum.adobe.com&amp;utm_medium=referral&amp;utm_content=powered_by&amp;utm_campaign=docsearch', '_blank');
```
Comment (LFDanLu) [inline packages/dev/docs/src/DocSearch.js:166]: mega nit: mind reseting the input value here so "algolia" doesn't persist as the input text?

```suggestion
    if (key === 'algolia-footer-logo') {
      window.open('https://www.algolia.com/ref/docsearch/?utm_source=react-spectrum.adobe.com&amp;utm_medium=referral&amp;utm_content=powered_by&amp;utm_campaign=docsearch', '_blank');
      setSearchValue('');
```

**Review by LFDanLu — APPROVED** [review]
I'm fine w/ the current state, scrolling seems to work well on desktop + mobile

File: packages/dev/docs/src/docs.css [hunk 13]
```diff
@@ -730,6 +831,24 @@ h2.sectionHeader {
   }
 }
 
+@media (max-width: 375px) {
+  .docSearchBoxThemeProvider {
+    .docSearchBox {
+      max-width: unset;
+      > div,
+      > div > div {
+        min-width: calc(
```
Comment (snowystinger) [inline packages/dev/docs/src/docs.css:840]: i want to revisit these in the future with comments because I have no idea what this or the other calcs in this PR are doing

**Review by snowystinger — APPROVED** [review]
Same comment as @LFDanLu about resetting value.

File: packages/dev/docs/src/DocSearch.js (hunk 12 above)
Comment (reidbarber) [reply packages/dev/docs/src/DocSearch.js:166]: I think onSubmit fires before the input is filled so I'll have to use a different method.

Comment (LFDanLu) [reply packages/dev/docs/src/DocSearch.js:166]: It looks like the above only works when hitting enter to select Algolia but not when clicking on the option, strange

Comment (reidbarber) [reply packages/dev/docs/src/DocSearch.js:166]: Weird that the field clears on clicking it, even without the code you suggested above. Definitely seems like a SearchAutocomplete bug. 

The only solution I can think of now is to refresh the page with `location.reload()`, but that seems like overkill.

Comment (LFDanLu) [reply packages/dev/docs/src/DocSearch.js:166]: Yeah, I've been doing some digging but haven't come up with a good alternative. Kinda feels like there is something broken in useComboBoxState with resetInputValue conflicting with the user's call of setSearchValue, but also I think SearchAutocomplete should perhaps do away with the concept of tracking the selectedKey since selecting an option would perform some kind of operation (maybe it should control the selectedKey to `null` instead of setting it to undef). For now the current experience is fine

**Review by LFDanLu — DISMISSED** [review]

File: packages/dev/docs/src/DocSearch.js (hunk 12 above)
Comment (reidbarber) [reply packages/dev/docs/src/DocSearch.js:166]: Actually, this feels a little better as a hack:
`searchAutocompleteRef.current.UNSAFE_getDOMNode().querySelector('[role="button"]').click();`

Comment (LFDanLu) [reply packages/dev/docs/src/DocSearch.js:166]: pretty gross haha but I'm fine with it for now.

**Review by LFDanLu — APPROVED** [review]

File: packages/dev/docs/src/attachToToC.js [hunk 14]
```diff
@@ -13,6 +13,7 @@
 import sideNavStyles from '@adobe/spectrum-css-temp/components/sidenav/vars.css';
 
 export function attachToToC() {
+  let main = document.getElementsByTagName('main')[0];
```
Comment (devongovett) [inline packages/dev/docs/src/attachToToC.js:16]: I think this is broken now...

**Review by snowystinger — APPROVED** [review]

**Review by devongovett — APPROVED** [review]

**Comment by solimant** [comment]
Just a heads-up -- this is what it looks like on mobile:
image

When you type:
image
