### PR TITLE
RAC: Fix Group render props and focus-visible behavior with text input children

### LINKED ISSUE #4430: React Aria Components: Group does not set `isTextInput` on `useFocusVisible`
_Originally reported here: https://twitter.com/devcassa/status/1650285734513852418_

# 🐛 Bug Report 

The `Group` component exposes a `data-focus-visible` state using `useFocusRing`. However, it does not set the `isTextInput` option automatically, and does not expose this as a prop to the user. This means the behavior is incorrect - the focus ring appears when typing normal letters rather than only when tabbing.

## 🤔 Expected Behavior

Either we need to expose `isTextInput` as a prop of the `Group` component, or automatically detect that the focused element is a text input here: https://github.com/adobe/react-spectrum/blob/ba727bdc0c4a57626131e84d9c9b661d0b65b754/packages/%40react-aria/interactions/src/useFocusVisible.ts#L203-L205

I prefer if we can make this automatic, and see about exposing the prop later if still needed.

## 😯 Current Behavior

`Group` sets `data-focus-visible` at incorrect times when an input is contained within it.

## 💁 Possible Solution

See above.

### PR DESCRIPTION
**Pull request by reidbarber**
Fixes:
- Group now works with render props, no longer errors with `"Warning: Functions are not valid as a React child."`
- Group's focus ring will render correctly with text input children. Closes #4430

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Check new tests.

### CODE REVIEW

File: packages/@react-aria/interactions/src/useFocusVisible.ts [hunk 1]
```diff
@@ -201,7 +201,8 @@ export function useInteractionModality(): Modality | null {
  * focus visible style can be properly set.
  */
 function isKeyboardFocusEvent(isTextInput: boolean, modality: Modality, e: HandlerEvent) {
-  return !(isTextInput && modality === 'keyboard' && e instanceof KeyboardEvent && !FOCUS_VISIBLE_INPUT_KEYS[e.key]);
+  let elementType = (e?.target as HTMLInputElement)?.type;
+  return !((isTextInput || elementType === 'text' || elementType === 'textarea') && modality === 'keyboard' && e instanceof KeyboardEvent && !FOCUS_VISIBLE_INPUT_KEYS[e.key]);
```
Comment (devongovett) [inline packages/@react-aria/interactions/src/useFocusVisible.ts:205]: wouldn't textarea be the tagName rather than the `type` attribute? There are also other input types that accept text input, like number, password, etc. I think we basically want the `willOpenKeyboard` function and input type list from `usePreventScroll`? I guess I'd just copy it here.

**Review by devongovett — APPROVED** [review]

File: packages/react-aria-components/test/Group.test.js [hunk 2]
```diff
@@ -0,0 +1,127 @@
...
+    expect(group).toHaveClass('disabled');
+  });
+
+  it('should support render props', () => {
+    let {getByRole} = render(<Group>{({isHovered}) => isHovered ? 'Hovered' : 'Group'}</Group>);
+    let group = getByRole('group');
+
+    expect(group).toHaveTextContent('Group');
+
+    fireEvent.mouseOver(group);
```
Comment (snowystinger) [inline packages/react-aria-components/test/Group.test.js]: can use `user.hover` and `user.unhover`

**Review by snowystinger — COMMENTED** [review]
I noticed that we are missing the PURE annotation for Group

```
const _Group = /*#__PURE__*/ (forwardRef as forwardRefType)(Group);
```

**Review by LFDanLu — APPROVED** [review]
approving for testing

**Review by snowystinger — APPROVED** [review]
