### PR TITLE
fix: S2 Prevented Tooltip text overflowing by default

### LINKED ISSUE #8514: Tooltip - Text Overflows
### Provide a general summary of the issue here

For long non-breaking text placed inside the tooltip, the text overflows past the tooltip container by default.

### 🤔 Expected Behavior?

Text could be wrapped or tooltip container could be extended

### 😯 Current Behavior

Text goes past the tooltip container

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/devbox/solitary-feather-nfw26x?file=%2Fapp%2Fpage.tsx%3A27%2C1

### Version

0.9.2

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS 14.4.1

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by samuelo-ensemble**
Closes #8514

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

Create a Tooltip with long non-breaking text

### Before:
image

### After:
image

### CODE REVIEW

File: packages/@react-spectrum/s2/src/Tooltip.tsx [hunk 1]
```diff
@@ -167,7 +167,7 @@ export const Tooltip = forwardRef(function Tooltip(props: TooltipProps, ref: DOM
       placement={placement}
       shouldFlip={shouldFlip}
       ref={tooltipRef}
-      style={UNSAFE_style}
+      style={{overflowWrap: 'break-word', ...UNSAFE_style}}
```
Comment (snowystinger) [inline packages/@react-spectrum/s2/src/Tooltip.tsx]: you'll want to add this style to the `tooltip` style (classname one line below is where that is used, it's a style macro), not to the inline style for the element

See https://react-spectrum.adobe.com/s2/index.html?path=/docs/style-macro--docs for more info on style macros

Comment (samuelo-ensemble) [reply packages/@react-spectrum/s2/src/Tooltip.tsx]: I considered that, but currently there isn't support there for `overflowWrap` in React Spectrum v3 and S2. Is this an addition we want to add support for here, and would that require additional documentation changes etc?

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-spectrum/s2/style/spectrum-theme.ts#L798

Comment (snowystinger) [reply packages/@react-spectrum/s2/src/Tooltip.tsx]: yeah, looks like the comment suggests we should add it

File: packages/@react-spectrum/s2/style/properties.json [hunk 2]
```diff
@@ -166,7 +166,8 @@
     "touchAction": "__X",
     "translate": "__Y",
     "wordBreak": "__Z",
-    "--fs": "__0"
+    "overflowWrap": "__0",
+    "--fs": "__1"
```
Comment (snowystinger) [inline packages/@react-spectrum/s2/style/properties.json]:
```suggestion
    "--fs": "__0",
    "overflowWrap": "__1"
```

@devongovett i think this has to be like this to keep it stable across versions?

Comment (samuelo-ensemble) [reply packages/@react-spectrum/s2/style/properties.json]: Should we just swap the value as you suggested @snowystinger to be safe, and move on?

Comment (snowystinger) [reply packages/@react-spectrum/s2/style/properties.json]: I think @devongovett typically generates this file with some script, so i do still want him to weigh in as i don't think it's meant to be manually updated

Comment (snowystinger) [reply packages/@react-spectrum/s2/style/properties.json]: Sorry for the long delay, turns out we the properties.json is an optimisation, we can just remove it from there for now.

Comment (samuelo-ensemble) [reply packages/@react-spectrum/s2/style/properties.json]: Oh cool, so we can just remove all the changes made to this file?

Comment (snowystinger) [reply packages/@react-spectrum/s2/style/properties.json]: yep, that should be fine, thank you

**Review by yihuiliao — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
