### PR TITLE
ListView drag preview follow-ups

### LINKED ISSUE #3067: ListView drag preview follow-ups
- Set height of preview to row height
- Make sure preview gets correct RTL styles. Icon padding is on wrong side. Stack should go in opposite direction.
- Round drag preview corners (if not a browser restriction)

# 🐛 Bug Report 

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #3067

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test in storybook at [ListView -> draggable rows](https://reactspectrum.blob.core.windows.net/reactspectrum/c53f68d98f4e863e3707c60ea2d83e543a622e12/storybook/index.html?path=/story/listview--draggable-rows)
- Drag preview height should match row height
- Styles in drag preview for RTL should be correct (match item's)
- Corners of drag preview should be rounded

### CODE REVIEW

File: packages/@react-spectrum/list/src/DragPreview.tsx [hunk 1]
```diff
@@ -30,41 +31,44 @@ export function DragPreview(props: DragPreviewProps) {
...
-            }}>
-            {typeof item.rendered === 'string' ? <Content>{item.rendered}</Content> : item.rendered}
-            {isDraggingMultiple &&
-              <div className={classNames(listStyles, 'react-spectrum-ListViewItem-badge')}>{itemCount}</div>
-            }
-          </SlotProvider>
-        </Grid>
-      </div>
-    </Provider>
+    <div dir={direction}>
```
Comment (reidbarber) [inline packages/@react-spectrum/list/src/DragPreview.tsx:42]: Ugly diff here: 
- added a wrapper div with `dir={direction}` to get proper RTL styles.

- added `background: 'none'` to provider style to get proper rounded corners 

- added fixed height to listviewitem div

Comment (reidbarber) [reply packages/@react-spectrum/list/src/DragPreview.tsx:42]: Just noticed that adding the div with a different direction gives this warning:

`Language directions cannot be nested. ltr inside rtl.`

Anyone know how to give Provider RTL direction here? Not sure why it would be incorrect

**Review by snowystinger — APPROVED** [review]
Tested in chrome, no longer see extra background, stack is correct direction for both locale directions, padding is correct

**Review by LFDanLu — APPROVED** [review]
LGTM, noticed that the space in the drag preview when dragging item b seems a bit more cramped in RTL but thats fine for now

**Comment by reidbarber** [comment]
> LGTM, noticed that the space in the drag preview when dragging item b seems a bit more cramped in RTL but thats fine for now

Investigated a bit and it actually looks like it has to do with the type kerning on RTL being smaller. Doesn't look like it is an issue with the drag preview itself since it is doing that in the listview item. May be a bug, (unless kerning is supposed to be different for RTL).
