### PR TITLE
Fix SearchWithin aria-label and aria-labelledby

### LINKED ISSUE #2174: Searchwithin aria-label and aria-labelledby
# 🐛 Bug Report 

Searchwithin should better handle giving correct `aria-label` and `aria-labelledby` attributes to the picker, searchfield, and group if no `label` is provided.

## 🤔 Expected Behavior

@majornista has listed some recommendations in https://github.com/adobe/react-spectrum/pull/2062#discussion_r678374202:
> I think DatePicker may be instructive on this point.
> - We use useLabels hook to retrieve the aria-label and aria-labelledby props: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/datepicker/src/useDatePicker.ts#L46-L47.
aria-label for the group should probably default to Search if no aria-label or aria-labelledby prop is provided.
> - The id, aria-label and aria-labelledby props returned by useLabels are applied to the group: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/datepicker/src/useDatePicker.ts#L89.
> - The aria-labelledby prop returned by useLabels, which will reference either the group or external element(s) by IDREF, is then applied to the input fields: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/datepicker/src/useDatePicker.ts#L101.
> - The Picker will then have a unique id, an aria-label like "Search within", and aria-labelledby concatenating the aria-labelledby prop returned by useLabels and the button id: https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/datepicker/src/useDatePicker.ts#L107-L108

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #2174

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

- Check id, aria-label, and aria-labelledby of group, input, and picker on 'Default', 'No Visible Label', and 'No Label' stories. 
- Check SearchWithin tests that test labels. Verify that it matches desired functionality mentioned in #2174.

Label combinations should look something like this:
```
<SearchWithin label=foo
searchwithin group is labelledby the label
input is labelled by searchwithin group
picker is labelled by searchwithin group + itself + dropdown label

<SearchWithin aria-label=foo
searchwithin group has aria-label foo
input is labelled by searchwithin group
picker is labelled by searchwithin group + itself + dropdown label

<SearchWithin
searchwithin group has aria-label w/default value of  "Search"
input is labelled by searchwithin group
picker is labelled by searchwithin group + itself + dropdown label
```

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 1]
```diff
@@ -62,20 +64,30 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
   let pickerClassName = classNames(styles, 'spectrum-SearchWithin-picker');
+
   let slots = {
-    searchfield: {UNSAFE_className: searchFieldClassName, ...fieldProps, ...defaultSlotValues},
-    picker: {UNSAFE_className: pickerClassName, menuWidth, align: 'end', ...defaultSlotValues}
+    searchfield: {
+      ...defaultSlotValues,
+      UNSAFE_className: searchFieldClassName,
+      'aria-labelledby': labelledBy,
+      ...fieldProps
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:78]: Should the order of this two be switched?

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 2]
```diff
@@ -62,20 +64,30 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
+    },
+    picker: {
+      ...defaultSlotValues,
+      id: pickerId,
+      UNSAFE_className: pickerClassName,
+      menuWidth,
+      align: 'end',
+      'aria-label': 'Search within',
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:86]: Is or should 'Search within' be an i18n value?

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 3]
```diff
@@ -16,23 +16,25 @@ import {FocusableRef} from '@react-types/shared';
...
     children,
     isDisabled,
     isRequired,
-    label,
-    'aria-label': ariaLabel,
-    'aria-labelledby': ariaLabelledby
+    label
   } = props;
+  let {styleProps} = useStyleProps(props);
+  let labels = useLabels(props, 'Search');
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:34]: Is or should 'Search' be an i18n value?

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 4]
```diff
@@ -166,6 +166,6 @@ describe('SearchWithin', function () {
     let group = getByRole('group');
 
     expect(searchfield).toHaveAttribute('aria-label', 'Aria Label');
-    expect(group).toHaveAttribute('aria-labelledby', 'Aria Label');
+    expect(group).toHaveAttribute('aria-labelledby', searchfield.id);
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:169]: Should the tests also check the default value for `aria-label`?

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 2 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:86]: Could not find any existing translations for search either, but I think we should add them. This might need to be a follow-up.

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 3 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:34]: Same as above, I'm not sure we have any at the moment, but it looks like we need them.

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 4 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:169]: Good idea, I'll add

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 1 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx]: Yes, those should be switched. Just pushed a fix.

**Review by ktabors — APPROVED** [review]
LGTM

**Review by ktabors — APPROVED** [review]

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 5]
```diff
@@ -152,20 +152,45 @@ describe('SearchWithin', function () {
...
+
+    expect(group).toHaveAttribute('aria-label', 'Search');
+    expect(searchfield).toHaveAttribute('aria-label', 'Search');
+    expect(picker).toHaveAttribute('aria-label', 'Search within');
+
+    expect(group).not.toHaveAttribute('aria-labelledby');
+    expect(searchfield).toHaveAttribute('aria-labelledby');
+    expect(picker).toHaveAttribute('aria-labelledby', `${group.id} ${picker.id} ${picker.childNodes[0].id}`);
+
+    expect(consoleWarnSpy).toHaveBeenLastCalledWith('If you do not provide a visible label, you must specify an aria-label or aria-labelledby attribute for accessibility');
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:194]: i'm a bit confused, why is this being called? it looks like everything has a default label?

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 6]
```diff
@@ -53,9 +53,9 @@ describe('SearchWithin', function () {
   });
 
   it('renders correctly', function () {
-    let {getAllByText, getByRole, getByLabelText} = renderSearchWithin();
+    let {getAllByText, getByRole, getByPlaceholderText} = renderSearchWithin();
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:56]: out of curiosity, why were these all moved to getByPlaceholderText? i think eventually we want to get rid of placeholder text, so it's more future proof if we get it by the label text, if possible

**Review by snowystinger — COMMENTED** [review]
it's close, i know this has been a complicated change
can you provide (in the description for the PR) a list of all the combinations? something like the below? I'm having trouble reading this out of the tests, which is another great place for something like this
```
// 3 elements that can be labeled
// searchwithin group
// input
// picker
// is that all of them?

<SearchWithin
searchwithin group has aria-label w/default value
input is labelled by searchwithin group + itself
picker is labelled by searchwithin group + itself

<SearchWithin aria-label=foo
searchwithin group has aria-label foo
input is labelled by searchwithin group + itself
picker is labelled by searchwithin group + itself

<SearchWithin label=foo
searchwithin group is labelledby the label
input is labelled by searchwithin group + itself
picker is labelled by searchwithin group + itself

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 7]
```diff
@@ -86,8 +98,9 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
         'spectrum-SearchWithin-container'
       )}>
       <div
+        {...labels}
+        aria-labelledby={labelProps.id || fieldProps.id}
```
[the remark this answers is not in the document]
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx]: There was no 'or' needed here actually, this has been fixed.

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 6 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:56]: That query was failing for some reason after a change. So I decided to use the placeholder one since it would work for those and also the ones without a label. I think you're right though, I'll see if I can replace that.

Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:56]: `getByRole('searchbox')` works, so I'll use that instead. Thanks!

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 5 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:194]: This happens because useLabel doesn't have a default label when it's called, and I don't think we want this. I think this can be fixed by doing something like this:
```jsx
let labels = useLabels(props, formatMessage('search'));
let {labelProps, fieldProps} = useLabel({
  ...props,
  ...labels
});
```
Thanks! Pushing a fix.

**Review by snowystinger — APPROVED** [review]
lgtm, tested in mac chrome/ff/safari

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 8]
```diff
@@ -60,20 +71,35 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
   let slots = {
-    searchfield: {UNSAFE_className: searchFieldClassName, ...fieldProps, ...defaultSlotValues},
-    picker: {UNSAFE_className: pickerClassName, menuWidth, align: 'end', ...defaultSlotValues}
+    searchfield: {
+      ...defaultSlotValues,
+      ...fieldProps,
+      UNSAFE_className: searchFieldClassName,
+      'aria-labelledby': labelledBy,
+      'aria-label': labels['aria-label']
+    },
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:91]: I'm digging right now as to why but it seems like the searchfield has the same id as the group id and ends up self referencing itself via `aria-labelledby`: 
image
Note that the id of the `group` is the same as the searchfield div in the screenshot.
Correct me if I'm wrong but I believe the id of the searchfield should be a unique value here. Making it a different value from the group id will then have VoiceOver properly announce the label + aria label of the searchfield

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx [hunk 9]
```diff
@@ -119,7 +119,9 @@ CustomWidth30.storyName = 'Custom width: 30';
 export const LabelPositionSide = () => render({labelPosition: 'side'});
 LabelPositionSide.storyName = 'labelPosition: side';
 
-export const NoLabel = () => render({label: undefined, 'aria-label': 'Aria Label'});
+export const NoVisibleLabel = () => render({label: undefined, 'aria-label': 'Search'});
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:122]: Nit: For this story and the default render story, it maybe better to have the aria-label/label be something different than "Search" just to make it easier to distinguish between the `aria-label="Search"` that gets applied to the SearchField automatically and the one provided by the user. Right now VoiceOver states "Search search" when focusing the SearchField portion of the SearchWithin component which is kinda confusing.

**Review by LFDanLu — CHANGES_REQUESTED** [review]

**Comment by LFDanLu** [comment]
@reidbarber played around with the code and did this small refactor: https://github.com/adobe/react-spectrum/commit/1a578e0092c71adddd7ab5f94b7c487167b2d180. The group now has an updated `aria-labelledby` that points to the the label id and itself if an `aria-label` is provided. The search input uses the same group `aria-labelledby` or `id` depending on if there is an external label (not entirely sure if it should only point to the group id at all times instead). The picker button does the same and appends its own id + the span id (perhaps the picker's `aria-labelledby` it should only be `label id + button id + dropdown span id` instead of `label id + group id + dropdown button id + dropdown span id` if `label id` exists since it will have an extra "search" added in the announcement)

What do you think? I tried to follow what was described [here](https://github.com/adobe/react-spectrum/issues/2174) with some tweaks to make sure things announced alright but lemme know if there were prior discussions that altered the approach taken here.

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 10]
```diff
@@ -13,25 +13,43 @@
...
     isRequired,
-    label,
-    'aria-label': ariaLabel,
-    'aria-labelledby': ariaLabelledby
+    label
   } = props;
 
+  let defaultAriaLabel = formatMessage('search');
+  // Get label and group props (aka fieldProps)
+  let {labelProps, fieldProps} = useLabel(props);
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:41]: we'll need to have some way to suppress the console warning from useLabel, that was why we'd reversed the order, so now we're getting that console warning again
given that we have a default aria label, lets add it to the props object we pass to useLabel if there isn't already a label or aria-label on the props object, is that enough?

Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:41]: I think that should do it. Something like this should work:
```jsx
  if (!props['aria-label'] && !props['aria-labelledby']) {
    props['aria-label'] = defaultAriaLabel;
  }
```
I'll push a fix.

Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:44]: Ah I see, good call @snowystinger. In that case I think we can do away with the `useLabels` call below entirely right? Will have to replace instances of `groupProps` with `fieldProps`

Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:44]: @LFDanLu good catch, just removed

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 11]
```diff
@@ -60,20 +81,34 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
+      'aria-labelledby': labelledBy
+    },
+    picker: {
+      ...defaultSlotValues,
+      id: pickerId,
+      UNSAFE_className: pickerClassName,
+      menuWidth,
+      align: 'end',
+      'aria-label': formatMessage('searchWithin'),
+      'aria-labelledby': `${labelledBy} ${pickerId}`
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:103]: I still wonder if this should be `${labelledBy} ${pickerId}` or it should point to the `label id + pickerId` instead if an external label exists. As it is right now it feels like it doubles up on `formatMessage('searchWithin')` and `formatMessage('search')` due to `labelledBy` containing the id of the label and the id of the group (due to the group's self reference for its `aria-label`). See the screenshot below for the `label` case
image

and the `no label` case:
image

It makes sense to do `${labelledBy} ${pickerId}` if a custom `aria-label` is provided though like in the `no visible label case`:
image
 
Thoughts?

cc @majornista

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx [hunk 12]
```diff
@@ -119,7 +119,9 @@ CustomWidth30.storyName = 'Custom width: 30';
 export const LabelPositionSide = () => render({labelPosition: 'side'});
 LabelPositionSide.storyName = 'labelPosition: side';
 
-export const NoLabel = () => render({label: undefined, 'aria-label': 'Aria Label'});
+export const NoVisibleLabel = () => render({label: undefined, 'aria-label': 'blahhaw'});
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:122]: Ah lol, sorry bout this scuffed aria-label
```suggestion
export const NoVisibleLabel = () => render({label: undefined, 'aria-label': 'Test aria label'});
```

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx [hunk 13]
```diff
@@ -41,7 +41,7 @@ function render(props: Omit<SpectrumSearchWithinProps, 'children'> = {}, searchF
 
 function renderReverse(props: Omit<SpectrumSearchWithinProps, 'children'> = {}, searchFieldProps: SearchFieldProps = {}, pickerProps: Omit<SpectrumPickerProps<object>, 'children'> = {}) {
   return (
-    <SearchWithin label="Search" {...props}>
+    <SearchWithin label="Search within" {...props}>
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:44]: Nit:
Sorry about these iffy labels from my test branch, perhaps change them to "Test label" or something easily distinguishable/realistic
```suggestion
    <SearchWithin label="Search within" {...props}>
```

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 14]
```diff
@@ -94,34 +94,34 @@ describe('SearchWithin', function () {
...
     triggerPress(picker);
 
     let listbox = getByRole('listbox');
     let label = getAllByText('Test')[0];
-    expect(listbox).toHaveAttribute('aria-labelledby', label.id);
-    expect(searchfield).toHaveAttribute('aria-labelledby', label.id);
-    expect(group).toHaveAttribute('aria-labelledby', label.id);
+    expect(listbox).toHaveAttribute('aria-labelledby', `${label.id} ${group.id} ${picker.id}`);
+    expect(searchfield).toHaveAttribute('aria-labelledby', `${label.id} ${group.id}`);
+    expect(group).toHaveAttribute('aria-labelledby', `${label.id} ${group.id}`);
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:108]: See my previous concern about these above.

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 15]
```diff
@@ -94,34 +94,34 @@ describe('SearchWithin', function () {
...
     let picker = getByRole('button');
     let group = getByRole('group');
     triggerPress(picker);
 
     let listbox = getByRole('listbox');
     let label = getAllByText('Test')[0];
-    expect(listbox).toHaveAttribute('aria-labelledby', label.id);
-    expect(searchfield).toHaveAttribute('aria-labelledby', label.id);
-    expect(group).toHaveAttribute('aria-labelledby', label.id);
+    expect(listbox).toHaveAttribute('aria-labelledby', `${label.id} ${group.id} ${picker.id}`);
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:106]: why doesn't this have the `picker.childNodes[0].id` like below?

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 16]
```diff
@@ -152,20 +152,40 @@ describe('SearchWithin', function () {
...
+    let searchfield = getByRole('searchbox');
+    let picker = getByRole('button');
+
+    expect(group).toHaveAttribute('aria-label', 'Search');
+    expect(picker).toHaveAttribute('aria-label', 'Search within');
 
-    expect(searchfield).toHaveAttribute('aria-label', 'Aria Label');
-    expect(group).toHaveAttribute('aria-labelledby', 'Aria Label');
+    expect(group).not.toHaveAttribute('aria-labelledby');
+    expect(searchfield).toHaveAttribute('aria-labelledby');
```
Comment (ktabors) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:188]: Why don't these have `group.id`?

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 11 above)
Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:103]: The reason why the `aria-labelledby` for the picker includes the `pickerId` is to have the announcement combine the content of the `aria-label` with the other stuff `aria-labelledby` points to. If the `pickerId` isn't included in the list of `aria-labelledby`, the `aria-label` on the picker won't be announced at all since `aria-labelledby` overrides all other name sources for an element

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 15 above)
Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:106]: The `picker.childNodes[0].id` is referencing the span of the picker button that contains the text of the current selected picker option. For the picker menu, I believe it doesn't need to announce the selected picker item since that info is available on the picker button itself (all of this follows the behavior of a standalone picker)

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 17]
```diff
@@ -60,20 +76,34 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
+    }
   };
 
-  if (!label && !ariaLabel && !ariaLabelledby) {
-    console.warn('If you do not provide a `label` prop, you must specify an aria-label or aria-labelledby attribute for accessibility');
-  }
-
```
[the remark this answers is not in the document]
Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:76]: Think this is caught by useLabel instead

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 18]
```diff
@@ -60,20 +76,34 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
...
+      // Apply aria-labelledby of group or the group id to searchfield. No need to pass the group id (we want a new one) and aria-label (aria-labelledby will suffice)
+      'aria-labelledby': labelledBy
+    },
+    picker: {
+      ...defaultSlotValues,
+      id: pickerId,
+      UNSAFE_className: pickerClassName,
+      menuWidth,
+      align: 'end',
+      'aria-label': formatMessage('searchWithin'),
```
[the remark this answers is not in the document]
Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:102]: Think the intention here is that the user provides an `aria-label` for the component as a whole and that gets concatenated with the label for the individual parts of the SearchWithin element (picker + search field). Not sure we want to allow the user to specify the label for every sub component within the SearchWithin since they each serve a specific function

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 16 above)
Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:188]: Think you are right, maybe it should be:
```suggestion
    expect(group).not.toHaveAttribute('aria-labelledby');
    expect(searchfield).toHaveAttribute('aria-labelledby',  group.id);
```
cc @reidbarber

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 15 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:106]: Yeah, this is basically because of how Picker does labelling. Related:

https://github.com/adobe/react-spectrum/blob/1e635d5e6540927a001f552194c30d8b3b48d8e8/packages/%40react-spectrum/picker/test/Picker.test.js#L812-L816

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 18 above)
[the remark this answers is not in the document]
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:102]: Yep, I think having it defined is what we want. if this is something we need to change it could be a follow-up

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 16 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:188]: Good catch, pushing a fix.

File: packages/@react-aria/select/src/useSelect.ts [hunk 19]
```diff
@@ -121,7 +121,7 @@ export function useSelect<T>(props: AriaSelectOptions<T>, state: SelectState<T>,
   let domProps = filterDOMProps(props, {labelable: true});
   let triggerProps = mergeProps(typeSelectProps, menuTriggerProps, fieldProps);
 
-  let valueId = useId();
+  let valueId = `${triggerProps.id}-value`;
```
Comment (snowystinger) [inline packages/@react-aria/select/src/useSelect.ts:124]: lets add a comment: used to make predictable id's based on the trigger which is already generated, this aids us in testing

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 20]
```diff
@@ -152,40 +152,87 @@ describe('SearchWithin', function () {
...
 
     expect(searchfield.classList.contains('is-quiet')).toBeFalsy();
     expect(picker.classList.contains('spectrum-Dropdown--quiet')).toBeFalsy();
   });
+});
 
-  it('Should handle aria-labels without visible label', function () {
-    let {getByRole} = renderSearchWithin({label: undefined, 'aria-label': 'Aria Label'});
+describe('SearchWithin labeling', function () {
+  it('Searchwithin (no label); SearchField no aria-label; Picker no aria-label', function () {
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:164]: I don't think we need to specify anything beyond no label, lets add a comment to SearchWithin's slots context and just say we don't allow aria-label on SearchField or Picker
```suggestion
  it('no label - default', function () {
```

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 21]
```diff
@@ -152,40 +152,87 @@ describe('SearchWithin', function () {
...
     expect(group).not.toHaveAttribute('aria-labelledby');
-    expect(searchfield).toHaveAttribute('aria-labelledby', group.id);
-    expect(picker).toHaveAttribute('aria-labelledby', `${group.id} ${picker.id} ${picker.childNodes[0].id}`);
+    expect(searchfield).toHaveAttribute('aria-labelledby', `${picker.id} ${picker.childNodes[0].id}`);
+    expect(picker).toHaveAttribute('aria-labelledby', `${picker.id} ${picker.childNodes[0].id}`);
   });
 
-  it('Should use default aria-labels if no aria-label provided', function () {
-    let {getByRole} = renderSearchWithin({label: undefined});
+  it('SearchWithin label = foo; SearchField no aria-label, no placeholder; Picker no aria-label', function () {
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:178]:
```suggestion
  it('label = foo', function () {
```

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 22]
```diff
@@ -152,40 +152,87 @@ describe('SearchWithin', function () {
...
+    expect(group).not.toHaveAttribute('aria-label');
+
+    expect(group).toHaveAttribute('aria-labelledby', label.id);
+    expect(searchfield).toHaveAttribute('aria-labelledby', `${label.id} ${picker.id} ${picker.childNodes[0].id}`);
+    expect(picker).toHaveAttribute('aria-labelledby', `${label.id} ${picker.id} ${picker.childNodes[0].id}`);
+
+    expect(label).toHaveAttribute('for', searchfield.id);
+  });
+
+  it('SearchWithin aria-label = bar; SearchField no aria-label, no placeholder; Picker no aria-label', function () {
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:195]:
```suggestion
  it('aria-label = bar', function () {
```

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js [hunk 23]
```diff
@@ -152,40 +152,87 @@ describe('SearchWithin', function () {
...
+
+    expect(group).toHaveAttribute('aria-label', 'bar');
 
     expect(group).not.toHaveAttribute('aria-labelledby');
-    expect(searchfield).toHaveAttribute('aria-labelledby', group.id);
+    expect(searchfield).toHaveAttribute('aria-labelledby', `${group.id} ${picker.id} ${picker.childNodes[0].id}`);
     expect(picker).toHaveAttribute('aria-labelledby', `${group.id} ${picker.id} ${picker.childNodes[0].id}`);
   });
+
+  it('SearchWithin aria-labelledby = {id}; SearchField no aria-label, no placeholder; Picker no aria-label', function () {
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/test/SearchWithin.test.js:209]:
```suggestion
  it('aria-labelledby = {id}', function () {
```

File: packages/@react-aria/select/src/useSelect.ts (hunk 19 above)
Comment (reidbarber) [reply packages/@react-aria/select/src/useSelect.ts:125]: Great idea, pushed a fix

File: packages/@react-spectrum/searchwithin/test/SearchWithin.test.js (hunk 20 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/test/SearchWithin.test.js]: Fixed these, thanks!

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx [hunk 24]
```diff
@@ -61,18 +77,39 @@ function SearchWithin(props: SpectrumSearchWithinProps, ref: FocusableRef<HTMLEl
     isRequired,
     label: null,
     isQuiet: false,
-    'aria-labelledby': labelProps.id || ariaLabel,
-    validationState: null
+    validationState: null,
+    description: null,
+    errorMessage: null,
+    descriptionProps: null,
+    errorMessageProps: null
```
Comment (snowystinger) [inline packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:84]: do we need this?
```
'aria-label': null
```
I know picker sets its own, but searchfield should probably null it? or have a name we set?

Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx:84]: I think we should probably set to null, since it is basically "covered" by the group and we also don't want users to provider their own. Matches the behavior of visual labels here

Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx]: pushed this change; if anyone disagrees, feel free to leave a comment

**Review by snowystinger — APPROVED** [review]
Looks good, tested on Safari / Chrome

**Review by majornista — DISMISSED** [review]
The labelling of input, picker and group seems good now.

Note for further updates in future PRs:
1. "input validationState: invalid" and "picker validationState: invalid" do not seem to demonstrate any behavior change.
2. Reverse Children Order does not seem to do anything.

File: packages/@react-spectrum/searchwithin/src/SearchWithin.tsx (hunk 8 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/src/SearchWithin.tsx]: Fixed by latest commits

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx [hunk 25]
```diff
@@ -119,7 +119,9 @@ CustomWidth30.storyName = 'Custom width: 30';
 export const LabelPositionSide = () => render({labelPosition: 'side'});
 LabelPositionSide.storyName = 'labelPosition: side';
 
-export const NoLabel = () => render({label: undefined, 'aria-label': 'Aria Label'});
+export const NoVisibleLabel = () => render({label: undefined, 'aria-label': 'Test aria label'});
+
+export const NoLabels = () => render({label: undefined});
```
Comment (LFDanLu) [inline packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:124]: This is from the "No Label" story, should the input `aria-labelledby` have the group id in its list? Maybe it's fine since the group's "Search" `aria-label` doesn't add much and the picker button `aria-label` and value provide enough information

image

**Review by LFDanLu — APPROVED** [review]
One question and a story ask, fine with this being in a follow up PR

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx [hunk 26]
```diff
@@ -119,7 +119,9 @@ CustomWidth30.storyName = 'Custom width: 30';
...
```
[the remark this answers is not in the document]
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:125]: Good idea, just added

File: packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx (hunk 25 above)
Comment (reidbarber) [reply packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:124]: Yeah, I don't think that is necessary here. We added a comment here:

https://github.com/adobe/react-spectrum/blob/48e8650680fc9a2276496fb2c478b9cb97294f0b/packages/%40react-spectrum/searchwithin/src/SearchWithin.tsx#L95-L96

Comment (LFDanLu) [reply packages/@react-spectrum/searchwithin/stories/SearchWithin.stories.tsx:124]: Hrm, I read that as we don't need to pass the group's `id` to the SearchField's `aria-labelledby' cuz the group's `aria-labelledby` was sufficient in most cases but here in the "No Label" case we don't actually have an `aria-labelledby` to pass. Probably a non-issue though as noted before, just something I was scratching my head over

**Review by LFDanLu — APPROVED** [review]
LGTM, new external label story seems to announce properly

**Review by snowystinger — APPROVED** [review]
