### PR TITLE
fix(@react-aria/select): avoid empty option in hidden select markup

### LINKED ISSUE #8085: Select markup includes an empty option element, which fails W3C validation
### Provide a general summary of the issue here

As stated in title, when using the component seen here

[https://react-spectrum.adobe.com/react-aria/examples/status-select.html](https://react-spectrum.adobe.com/react-aria/examples/status-select.html)

the resultant markup includes a <select> element whose first child is an empty <option> element.

This is an error according to the W3 validator ([https://validator.w3.org/](https://validator.w3.org/)):

> Element option without attribute label must not be empty.

### 🤔 Expected Behavior?

Component passes W3 validation

### 😯 Current Behavior

Component fails W3 validation

### 💁 Possible Solution

Empty <option> element should be removed or given a valid "label" attribute

### 🔦 Context

Pass W3 validation

### 🖥️ Steps to Reproduce

Use component
Test URL that contains component using W3 validator
Get error "Element option without attribute label must not be empty"

### Version

1.7.1 (react-aria-components)

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Mac

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by sonsu-lee**
Closes #8085

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

1. Run `yarn jest packages/@react-aria/select` — two new tests should pass:
  - `should include a non-empty placeholder option for native select markup`
  - `should submit an empty string when no value is selected`
2. In a Select story with no default value, inspect the hidden `<select>` and verify the first `<option>` is `<option value="" label="\u00A0">` (no longer empty)
## 🧢 Your Project:

- Personal

### CODE REVIEW

File: packages/@react-aria/select/src/HiddenSelect.tsx [hunk 1]
```diff
@@ -157,7 +157,7 @@ export function HiddenSelect<T, M extends SelectionMode = 'single'>(props: Hidde
         <label>
           {label}
           <select {...selectProps} ref={selectRef}>
-            <option />
+            <option value="" label={'\u00A0'}>{'\u00A0'}</option>
```
Comment (devongovett) [inline packages/@react-aria/select/src/HiddenSelect.tsx:160]: Probably unnecessary to have both label and children?
