### PR TITLE
ComboBox bug fixes

### LINKED ISSUE #1443: Combobox bugs
- [x] onOpenChange shouldn't be called if there are no items
- [x] Pressing enter in `allowsCustomValue` story should close menu
- [x] Read only mobile combobox shouldn't be open when focused/clicked
- [x] Menu remains open when selecting an already selected item with mouse
         To reproduce: Select an item, open it back up with the mouse, click on the selected item with the mouse, onSelectionChange is called and the dropdown stays open. 
- [x] Input not updating when reselecting after input change 
         To reproduce: Select "Item Three", then ctrl + A and type "three". Arrow down and press enter. The input text is not updated to "Item Three" again.
- [ ] Talkback on Firefox doesn't announce if a combobox option is disabled
- [ ] isOpen and defaultOpen stories have a bunch of room in between each item

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #1443

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

**Comment by LFDanLu** [comment]
Contains fixes for each bug mentioned in the issue barring the talkback firefox accessibility issue and the isOpen/defaultOpen story issue:
- Firefox talkback issue I've made minimum repro codesandboxes that don't rely on our RSP implementation
- still debugging isOpen/defaultOpen issue (looks like a race condition? still digging)

File: packages/@react-stately/combobox/src/useComboBoxState.ts [hunk 1]
```diff
@@ -153,7 +183,15 @@ export function useComboBoxState<T extends object>(props: ComboBoxStateProps<T>)
     } else {
       lastSelectedKey.current = null;
       setSelectedKey(null);
-      shouldClose = selectedKey === null;
+
```
Comment (LFDanLu) [inline packages/@react-stately/combobox/src/useComboBoxState.ts:186]: https://github.com/adobe/react-spectrum/pull/1449/files#diff-52d3ae5861fe9f80aaec78778d0a666b2b9d10dbf2aac7133bd6d3d70cade0faR180-R182

Just noticed that it won't close when clicking out of the combobox, perhaps this should be
```
 if (!allowsCustomValue) {
      resetInputValue();
      // Also close if the reset input value is empty
      shouldClose = inputValue === lastValue.current || lastValue.current === '';
```
or perhaps blur should always close the menu

Comment (snowystinger) [reply packages/@react-stately/combobox/src/useComboBoxState.ts:186]: When would blur not close the menu?

File: packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx [hunk 2]
```diff
@@ -178,7 +178,7 @@ storiesOf('ComboBox', module)
   )
   .add(
     'isOpen',
-    () => <ControlledOpenCombobox isOpen />,
+    () => <ControlledOpenCombobox isOpen allowsCustomValue defaultSelectedKey="two" />,
```
[the remark this answers is not in the document]
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx:181]: yep that is the last bug mentioned here: https://github.com/adobe/react-spectrum/issues/1443#issue-780033176. Looks to be a race condition maybe, was still trying to debug

File: packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx [hunk 3]
```diff
@@ -602,7 +608,7 @@ let ControlledOpenCombobox = (props) => {
   return (
     <Flex direction="column">
       <TextField label="Email" />
-      <ComboBox label="Combobox" isOpen={isOpen} {...actions} onOpenChange={setOpen}>
+      <ComboBox label="Combobox" {...props} isOpen={isOpen} {...actions} onOpenChange={setOpen}>
```
[the remark this answers is not in the document]
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx:611]: that should be fine, will do

File: packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx [hunk 4]
```diff
@@ -627,11 +633,11 @@ function AllControlledOpenComboBox(props) {
   });
 
   let onSelectionChange = (key: React.Key) => {
-    setFieldState({
+    setFieldState(prevState => ({
```
[the remark this answers is not in the document]
Comment (LFDanLu) [reply packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx:636]: Needed for the `inputValue` logic below where we have different behavior if the combobox `allowsCustomValue` or not. If it doesn't allow custom values, we clear the input field. If it does allow custom values, we wanna keep the current inputValue aka prevState.inputValue

File: packages/@react-stately/combobox/src/useComboBoxState.ts (hunk 1 above)
Comment (LFDanLu) [reply packages/@react-stately/combobox/src/useComboBoxState.ts:186]: yep, I couldn't think of a scenario where blur wouldn't close the menu so I made the above change

File: packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx (hunk 2 above)
[the remark this answers is not in the document]
Comment (snowystinger) [reply packages/@react-spectrum/combobox/stories/ComboBox.stories.tsx:181]: oo, i read that a little differently i think, because it's only the one item and it happens even when it's alone for some reason, carry on

File: packages/@react-stately/combobox/src/useComboBoxState.ts [hunk 5]
```diff
@@ -153,7 +183,15 @@ export function useComboBoxState<T extends object>(props: ComboBoxStateProps<T>)
...
+      // If previous key was already null, need to manually call onSelectionChange since it won't be triggered by a setSelectedKey call
+      // This allows the application to control whether or not to close the menu on custom value commit
+      if (selectedKey === null && props.onSelectionChange) {
+        props.onSelectionChange(null);
+      }
+
+      // Should close menu ourselves if component open state or selected key is uncontrolled and therefore won't be closed by a user defined event handler
+      shouldClose = props.isOpen == null || props.selectedKey === undefined;
```
Comment (LFDanLu) [inline packages/@react-stately/combobox/src/useComboBoxState.ts:194]: Try removing props.isOpen == null here and see if the menu closes when user goes from no selected key to still no selected key via
Combobox (open state is not controlled, selected key is controlled and thus has a onSelectionChange handler)
1. type in field, menu opens
2. hit enter to submit custom value
3. menu closes?

Comment (LFDanLu) [reply packages/@react-stately/combobox/src/useComboBoxState.ts]: Yep, did some testing again, still need the isOpen here

File: packages/@react-stately/combobox/src/useComboBoxState.ts [hunk 6]
```diff
@@ -75,7 +100,7 @@ export function useComboBoxState<T extends object>(props: ComboBoxStateProps<T>)
   };
 
   let isInitialRender = useRef(true);
-  let lastSelectedKey = useRef(null);
+  let lastSelectedKey = useRef(props.selectedKey || props.defaultSelectedKey || null);
```
Comment (LFDanLu) [inline packages/@react-stately/combobox/src/useComboBoxState.ts:103]: Regarding the question concerning this line and 
```
    if (isInitialRender.current && (props.inputValue === undefined && props.defaultInputValue === undefined)) {
      resetInputValue();
    }
```
This change fixes two bugs. 
1. The first bug is that ComboBox with `isOpen: true` and `selectedKey/defaultSelectedKey: some key` calls `isOpenChange(false)` on initial render. If `lastSelectedKey = useRef(null)`, the useEffect calls `triggerState.close()` due to this block of code:
```
    // Close when an item is selected, if open state or selectedKey is uncontrolled.
    if (
      selectedKey != null &&
      selectedKey !== lastSelectedKey.current &&
      (props.isOpen === undefined || props.selectedKey === undefined)
    ) {
      triggerState.close();
    }
```
hence the change to `let lastSelectedKey = useRef(props.selectedKey || props.defaultSelectedKey || null);`

2. The second bug occurs due to the above change where now ComboBoxes that have `selectedKey/defaultSelectedKey` render with empty input fields on initial render. This used to work when `lastSelectedKey` was initialized to `null` because it would hit this block of code in the useEffect, calling `resetInputValue`:
```
    if (
      selectedKey !== lastSelectedKey.current &&
      (props.inputValue === undefined || props.selectedKey === undefined) &&
      !(isInitialRender.current && props.defaultInputValue !== undefined)
    ) {
      resetInputValue();
    } else {
      lastValue.current = inputValue;
    }
```
To compensate for the fact that `lastSelectedKey` now initializes as `defaultSelectedKey/selectedKey` if provided, I added
```
    // If it is the intial render and inputValue isn't controlled nor has an intial value, set input to match current selected key if any
    if (isInitialRender.current && (props.inputValue === undefined && props.defaultInputValue === undefined)) {
      resetInputValue();
    }
```

File: packages/@react-stately/combobox/src/useComboBoxState.ts [hunk 7]
```diff
@@ -147,15 +177,19 @@ export function useComboBoxState<T extends object>(props: ComboBoxStateProps<T>)
...
+    setSelectedKey(null);
+
+    // If previous key was already null, need to manually call onSelectionChange since it won't be triggered by a setSelectedKey call
+    // This allows the application to control whether or not to close the menu on custom value commit
+    if (selectedKey === null && props.onSelectionChange) {
+      props.onSelectionChange(null);
     }
 
+    // Should close menu ourselves if component open state or selected key is uncontrolled and therefore won't be closed by a user defined event handler
+    shouldClose = props.isOpen == null || props.selectedKey === undefined;
```
Comment (LFDanLu) [inline packages/@react-stately/combobox/src/useComboBoxState.ts:190]: Regarding the question for why `props.isOpen` is required here, this is so we close the menu when submitting a custom value when isOpen is uncontrolled. `commitCustomValue` sets `lastSelectedKey.current` to `null` and calls `setSelectedKey(null)`, making it so that the useEffect's block that handles closing the menu on selected key change doesn't fire since `lastSelectedKey = selectedKey`.

File: packages/@react-stately/combobox/src/useComboBoxState.ts (hunk 6 above)
Comment (devongovett) [reply packages/@react-stately/combobox/src/useComboBoxState.ts:103]: ok makes sense. should we do this instead to account for falsey keys?

```suggestion
  let lastSelectedKey = useRef(props.selectedKey ?? props.defaultSelectedKey ?? null);
```

File: packages/@react-stately/combobox/src/useComboBoxState.ts [hunk 8]
```diff
@@ -120,6 +145,11 @@ export function useComboBoxState<T extends object>(props: ComboBoxStateProps<T>)
       }
     }
 
+    // If it is the intial render and inputValue isn't controlled nor has an intial value, set input to match current selected key if any
+    if (isInitialRender.current && (props.inputValue === undefined && props.defaultInputValue === undefined)) {
+      resetInputValue();
+    }
```
Comment (devongovett) [inline packages/@react-stately/combobox/src/useComboBoxState.ts:151]: It's possible that the condition on line 160 can be removed now?

File: packages/@react-aria/overlays/src/ariaHideOutside.ts [hunk 9]
```diff
@@ -85,7 +85,7 @@ export function ariaHideOutside(targets: HTMLElement[], root = document.body) {
 
       // If the parent element of the added nodes is not within one of the targets,
       // and not already inside a hidden node, hide all of the new children.
-      if (![...visibleNodes, ...hiddenNodes].some(node => node.contains(change.target))) {
+      if (![...visibleNodes, ...hiddenNodes].filter(node => !!node).some(node => node.contains(change.target))) {
```
Comment (LFDanLu) [inline packages/@react-aria/overlays/src/ariaHideOutside.ts:88]: This line + the change to the Popover `isOpen` logic in ComboBox fix the intermittent item sizing issue when ComboBox is `defaultOpen/isOpen = true`. Fix suggested by @razvanip, looks reasonable to me, open to other opinions.

File: packages/@react-spectrum/combobox/src/ComboBox.tsx [hunk 10]
```diff
@@ -149,7 +149,7 @@ const ComboBoxBase = React.forwardRef(function ComboBoxBase<T extends object>(pr
           triggerRef={buttonRef} />
       </Field>
       <Popover
-        isOpen={state.isOpen}
+        isOpen={state.isOpen && !!menuWidth}
```
Comment (LFDanLu) [inline packages/@react-spectrum/combobox/src/ComboBox.tsx:152]: See https://github.com/adobe/react-spectrum/pull/1449/files#r564852870

File: packages/@react-aria/overlays/src/ariaHideOutside.ts (hunk 9 above)
Comment (devongovett) [reply packages/@react-aria/overlays/src/ariaHideOutside.ts:88]: hmm why would there be null nodes in there? where are they added?

**Review by devongovett — APPROVED** [review]

File: packages/@react-aria/overlays/src/ariaHideOutside.ts (hunk 9 above)
Comment (razvanip) [reply packages/@react-aria/overlays/src/ariaHideOutside.ts]: i guess it must be due tot the `cond` rendering

checked a little the code, i think it's due to this effect in `useCombobox` 
```
ariaHideOutside([inputRef.current, popoverRef.current]
```

since we use it internally in `ComboBox` and we don't render the `PopOver` until we get the `width` calculated the ref for the `popover` will be null, and will be passed in `ariaHideOutside` 

i can have a deeper look if we need to.

Comment (razvanip) [reply packages/@react-aria/overlays/src/ariaHideOutside.ts]: i still think it's best not to render the `popover` until we have the `width` calculated, the first render when applying `styling` on the `popover` container  `width` `height` is `null`

Comment (LFDanLu) [reply packages/@react-aria/overlays/src/ariaHideOutside.ts]: @razvanip We'll revisit via https://github.com/adobe/react-spectrum/issues/1485, hoping that the fix within the drag and drop pull will fix it.

File: packages/@react-spectrum/combobox/src/MobileComboBox.tsx [hunk 11]
```diff
@@ -477,7 +478,7 @@ function ComboBoxTray(props: ComboBoxTrayProps) {
           onScroll={onScroll}
           onLoadMore={onLoadMore}
           isLoading={loadingState === 'loading' || loadingState === 'loadingMore'} />
-        <DismissButton onDismiss={() => state.commit()} />
+        <DismissButton onDismiss={chain(state.commit, state.close)} />
```
Comment (razvanip) [inline packages/@react-spectrum/combobox/src/MobileComboBox.tsx:481]: @LFDanLu since u are online i have a question regarding `chain`.(might be dumb) 

Might we have situations when `close` should be called after `commit` finishes, what i mean will we encounter situations when `commit` might be `async` resulting in `close` removing a `component` from the screen and `commit` did not finish ?

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:481]: Hm, I can't think of a scenario where this would be an issue. [`commit`](https://github.com/adobe/react-spectrum/blob/main/packages/@react-stately/combobox/src/useComboBoxState.ts#L199-L212) updates the input value/selected key, don't think `close` would interfere with it

Comment (razvanip) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:481]: i was thinking on a situation where `commit` does some `setState` and then `close` comes in and `unmounts` the `component`,  should get an error in that situation

Comment (LFDanLu) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:481]: The tray would be unmounted, but the MobileCombobox itself would remain.

Comment (razvanip) [reply packages/@react-spectrum/combobox/src/MobileComboBox.tsx:481]: 👍
