### PR TITLE
fix: controlled tooltips are not close properly

### LINKED ISSUE #6233: When multiple tooltips are open controlled, the first tooltip would not close after the cursor hovers on the second tooltip.
### Provide a general summary of the issue here

When multiple tooltips are open controlled, the first tooltip would not close after the cursor hovers on the second tooltip.

### 🤔 Expected Behavior?

The first tooltip would close after the cursor hovers on the second tooltip.

### 😯 Current Behavior

http://localhost:9003/?path=/story/tooltiptrigger--controlled-multiple-tooltips&providerSwitcher-express=false&strict=true

https://github.com/adobe/react-spectrum/assets/8994590/3e45b13d-f286-4b77-b684-2824c21272a5

### 💁 Possible Solution

1. It seems the `closeOpenTooltips` function in `packages/@react-stately/tooltip/src/useTooltipTriggerState.ts` is not working properly when the `isOpen` prop is controlled, when the close handler is called, the currentValue(open) in `useControlledState` is still false thus not trigger the `onOpenChange` handler in the Tooltip.
```
  let closeOpenTooltips = () => {
    for (let hideTooltipId in tooltips) {
      if (hideTooltipId !== id) {
        tooltips[hideTooltipId](true);
        delete tooltips[hideTooltipId];
      }
    }
  };
```

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

1. The story in the react-spectrum repo can reproduce this issue: http://localhost:9003/?path=/story/tooltiptrigger--controlled-multiple-tooltips&providerSwitcher-express=false&strict=true

### Version

3.32.1

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by igorman007**
Closes #6233

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

You can check this fix at storybook page.
http://localhost:9003/?path=/story/tooltiptrigger--controlled-multiple-tooltips&providerSwitcher-express=false&strict=true

before: the first tooltip doesn't close, when the second opens
after: the first tooltip closes, when the second opens

### CODE REVIEW

File: packages/@react-stately/tooltip/src/useTooltipTriggerState.ts [hunk 1]
```diff
@@ -81,11 +82,11 @@ export function useTooltipTriggerState(props: TooltipTriggerProps = {}): Tooltip
     if (immediate || closeDelay <= 0) {
       clearTimeout(closeTimeout.current);
       closeTimeout.current = null;
-      close();
+      closeCallback.current();
     } else if (!closeTimeout.current) {
       closeTimeout.current = setTimeout(() => {
         closeTimeout.current = null;
-        close();
+        closeCallback.current();
```
Comment (igorman007) [inline packages/@react-stately/tooltip/src/useTooltipTriggerState.ts:89]: no need to change this line of code (it has no bug), but changed it for consistency.
**use close callback only from ref**

**Comment by yihuiliao** [comment]
Thanks for the PR! Mind signing the Adobe CLA?

**Comment by igorman007** [comment]
> Thanks for the PR! Mind signing the Adobe CLA?

Done

File: packages/@react-stately/tooltip/src/useTooltipTriggerState.ts [hunk 2]
```diff
@@ -119,6 +120,10 @@ export function useTooltipTriggerState(props: TooltipTriggerProps = {}): Tooltip
     }
   };
 
+  useEffect(() => {
```
Comment (snowystinger) [inline packages/@react-stately/tooltip/src/useTooltipTriggerState.ts:123]: we can use `useEffectEvent` instead of managing this ref ourselves

**Review by snowystinger — COMMENTED** [review]
Thanks for the PR!

**Comment by snowystinger** [comment]
Also, if it's not too hard, would you mind adding a unit test?

File: packages/@react-stately/tooltip/src/useTooltipTriggerState.ts (hunk 2 above)
Comment (igorman007) [reply packages/@react-stately/tooltip/src/useTooltipTriggerState.ts:123]: Are you sure, that's a good idea?
From the doc
```
Effect Events are very limited in how you can use them:

**Only call them from inside Effects.**
Never pass them to other components or Hooks.
```
we call 'close' not inside effect

File: packages/@react-stately/tooltip/test/useTooltipTriggerState.test.js [hunk 3]
```diff
@@ -196,4 +213,45 @@ describe('useTooltipTriggerState', function () {
       expect(onOpenChange).toHaveBeenCalledWith(false);
     });
   });
+
+  describe('multiple controlled tooltips', () => {
+    it('closes previus tooltip when opening a new one', () => {
```
Comment (igorman007) [inline packages/@react-stately/tooltip/test/useTooltipTriggerState.test.js:218]: this test fails without fix and passes after fix

File: packages/@react-stately/tooltip/src/useTooltipTriggerState.ts (hunk 2 above)
Comment (snowystinger) [reply packages/@react-stately/tooltip/src/useTooltipTriggerState.ts:123]: we have one from before those limitations were involved and because we have to support it all the way back to react 16, https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/useEffectEvent.ts which I think is doing the same thing as you've done here

but no worries, can replace later

**Review by snowystinger — APPROVED** [review]
Thanks so much for writing the test!

**Comment by LFDanLu** [comment]
GET_BUILD

**Review by LFDanLu — APPROVED** [review]
Verified the behavior before and after the fix, LGTM thanks!

**Comment by GuoXiaoyang** [comment]
That's great! May I ask when this fix will be published?

**Comment by snowystinger** [comment]
It'll be in our next release. Sometime in the next couple weeks most likely
