### PR TITLE
Fix controlled <Slider /> value updates (multiple thumbs)

### LINKED ISSUE #5644: Multiple thumbs slider with controlled value doesn't update correctly thumb state
### Provide a general summary of the issue here

When using multiple thumbs with the `<Slider />` component imported from `react-aria-components`, updating the controlled value causes non-updated thumbs to revert to their original values upon the next slider interaction.

https://github.com/adobe/react-spectrum/assets/54606780/ea2a152b-c529-4a2d-a04e-95a1432113aa

### 🤔 Expected Behavior?

The expected behavior is that when the value prop of the slider `<Slider value={MULTIPLE_NUMBER} />` is updated programmatically, all thumbs should reflect the new values accurately and maintain these values during subsequent interactions with the slider.

### 😯 Current Behavior

Currently, when the slider's controlled value is updated, and the slider is interacted with again, the non-updated thumbs revert to their original values instead of maintaining the updated state.

### 💁 Possible Solution

I guess Slider thumbs state that control in the component doesn't update correctly state with using `state.setThumbValue()` because this behavior will be fixed to catch updated value and use `state.setThumbValue()` .

This behavior can be fixed by this hack implementation.

```tsx
export default function App() {
  const [value, setValue] = React.useState([0, 100]);

  return (
    <>
      <Slider value={value} onChange={setValue} minValue={0} maxValue={100}>
        <SliderOutput
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-end",
          }}
        >
          {({ state }) => (
            <>
              <p>Current values: {state.values.join(" – ")}</p>
              <Button
                onClick={() => {
                  // 👇 update thumb value directly.
                  state.setThumbValue(0, 0);
                  state.setThumbValue(1, 100);
                }}
              >
                Reset
              </Button>
            </>
          )}
        </SliderOutput>
        <SliderTrack>
          <SliderThumb index={0} />
          <SliderThumb index={1} />
        </SliderTrack>
      </Slider>
    </>
  );
}
```

### 🔦 Context

I'm trying to update values to reset value. 

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/react-aria-components-slider-multiple-thumb-issue-xlvxmg?file=%2Fsrc%2FApp.js

### Version

react-aria-components@1.0.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Mac OS 14.1.1

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by sookmax**
Closes #5644

Hello, this PR fixes the issue above by re-syncing `valuesRef.current` in an effect whenever `values` changes.

As @snowystinger suggested in [the comment](https://github.com/adobe/react-spectrum/issues/5644#issuecomment-1875677050), I first tried to put `valuesRef.current = values;` inside `updateValue()` right before `let newValues = replaceIndex(valuesRef.current, index, value);`.

i.e., 
```diff
function updateValue(index: number, value: number) {
    if (isDisabled || !isThumbEditable(index)) {
      return;
    }
    const thisMin = getThumbMinValue(index);
    const thisMax = getThumbMaxValue(index);

    // Round value to multiple of step, clamp value between min and max
    value = snapValueToStep(value, thisMin, thisMax, step);
+   valuesRef.current = values; 
    let newValues = replaceIndex(valuesRef.current, index, value);
    setValues(newValues);
  }
```

It worked fine and passed the test I wrote so I was ready to submit the above fix.. until I realized it tragically started to cause a particular test in `packages/@react-spectrum/slider/test/RangeSlider.test.tsx` to fail (`'supports form reset'` test).

And well since re-syncing `valuesRef.current` in `useEffect()` seems to pass all the tests, that's what this PR contains for now.

I feel like there should be a better way yet. I'd appreciate you guys' opinions on this.

(Oh and I added a reset button to the story `SliderExample`.)

Thanks!

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### storybook
- http://localhost:9003/?path=/story/react-aria-components--slider-example&providerSwitcher-express=false&strict=true

### CODE REVIEW

**Comment by sookmax** [comment]
I think the reason the following change breaks the test `'supports form reset'` in `RangeSlider.test.tsx` is that
```diff
function updateValue(index: number, value: number) {
    if (isDisabled || !isThumbEditable(index)) {
      return;
    }
    const thisMin = getThumbMinValue(index);
    const thisMax = getThumbMaxValue(index);

    // Round value to multiple of step, clamp value between min and max
    value = snapValueToStep(value, thisMin, thisMax, step);
+   valuesRef.current = values; 
    let newValues = replaceIndex(valuesRef.current, index, value);
    setValues(newValues);
  }
```
the requested state changes that are supposed to go from `[30, 60]` to `[10, 40]` are interfered by `valuesRef.current = values`, resulting in following state update sequence: `[30, 60]` -> `[10, 60]` (`values` is `[30, 60]`) -> `[30, 40]` (`values` is still `[30, 60]` since the hook has not been re-rendered yet.) and so the test fails.

#### the 'supports form reset' test
```tsx
it('supports form reset', async () => {
    function Test() {
      let [value, setValue] = React.useState({start: 10, end: 40});
      return (
        <Provider theme={theme}>
          <form>
            <RangeSlider label="Value" value={value} onChange={setValue} />
            <input type="reset" data-testid="reset" />
          </form>
        </Provider>
      );
    }

    let {getByTestId, getAllByRole} = render(<Test />);
    let inputs = getAllByRole('slider');

    expect(inputs[0]).toHaveValue('10');
    expect(inputs[1]).toHaveValue('40');
    fireEvent.change(inputs[0], {target: {value: '30'}});
    fireEvent.change(inputs[1], {target: {value: '60'}});
    expect(inputs[0]).toHaveValue('30');
    expect(inputs[1]).toHaveValue('60');

    let button = getByTestId('reset');
    await user.click(button);
    expect(inputs[0]).toHaveValue('10');
    expect(inputs[1]).toHaveValue('40');
  });
```

I guess putting `valuesRef.current = values;` inside `useEffect()` works because it updates `valuesRef.current` after the hook re-renders with the new `values`.

This stuff is pretty confusing 🤯.

**Comment by snowystinger** [comment]
Apologies for the delay, I have not forgotten about this. Thank you very much for checking on the other route. I'll try to get some time to review this soon.

**Comment by sookmax** [comment]
I've also found that updating `valuesRef.current` in `updateValue()` works if we use [flushSync](https://react.dev/reference/react-dom/flushSync) like below:

```diff
function updateValue(index: number, value: number) {
    if (isDisabled || !isThumbEditable(index)) {
      return;
    }
    const thisMin = getThumbMinValue(index);
    const thisMax = getThumbMaxValue(index);

    // Round value to multiple of step, clamp value between min and max
    value = snapValueToStep(value, thisMin, thisMax, step);
+   valuesRef.current = values; 
    let newValues = replaceIndex(valuesRef.current, index, value);
-   setValues(newValues);
+   flushSync(() => setValues(newValues));   
  }
```

But.. `react-dom` is not a `dependency` or `peerDependency` of `@react-stately/slider` which contains `useSliderState()` so I'm not sure if we can use `flushSync()` like above.

I hope this helps a little!

File: packages/@react-stately/slider/src/useSliderState.ts [hunk 1]
```diff
@@ -244,6 +245,9 @@ export function useSliderState<T extends number | number[]>(props: SliderStateOp
     if (isDisabled || !isThumbEditable(index)) {
       return;
     }
+    if (dragging) {
```
Comment (snowystinger) [inline packages/@react-stately/slider/src/useSliderState.ts:248]: when dragging flipped to false, it was setting it with a stale value

**Comment by snowystinger** [comment]
GET_BUILD

File: packages/@react-stately/slider/src/useSliderState.ts (hunk 1 above)
Comment (sookmax) [reply packages/@react-stately/slider/src/useSliderState.ts:248]: This is great! 

I was too fixated on updating `valuesRef.current` in `upateValue()` since all the thumb interactions must eventually arrive at `updateValue()`. Nice to know that there _is_ another place to put `valuesRef.current = values`!

**Review by reidbarber — APPROVED** [review]
LGTM
