### PR TITLE
fix: Improve behavior of modals on iOS 26

### LINKED ISSUE #5926: iOS keyboard covers inputs when using useDialog/useModalOverlay
Additional information: https://github.com/adobe/react-spectrum/issues/6405 shows that this is not only limited to full screen dialogs, but modal experiences in general.

### Provide a general summary of the issue here

we noticed that using the example from https://react-spectrum.adobe.com/react-aria/useDialog.html causes issues when creating a full screen dialog where an input is at the bottom of the dialog, it's impossible to see the input, the keyboard covers it, it only happens on iOS, old and new safari versions. we tried using radix dialog and it works properly so it seems some internal logic of react-aria.

https://github.com/adobe/react-spectrum/assets/77207702/9e493c13-bc9d-499a-af16-5a5817f3f71c

### 🤔 Expected Behavior?

the dialog should leave the browser to focus the input and "fix" by itself the keyboard covering.

### 😯 Current Behavior

the keyboard covers the input and it's impossible to scroll down, the dialog scrolls up when trying it. 

### 💁 Possible Solution

no sure

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

1. Open this [codesandbox](https://codesandbox.io/p/github/JRS-Developer/testing-dialogs/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clsxs3ow500073d5tx2jr1ii8%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clsxs3ow500023d5tvzqvngt1%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clsxs3ow500043d5tos3c04kt%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clsxs3ow500063d5tsdxj7c0g%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clsxs3ow500023d5tvzqvngt1%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxs3ow400013d5tag68uvix%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%255D%252C%2522id%2522%253A%2522clsxs3ow500023d5tvzqvngt1%2522%252C%2522activeTabId%2522%253A%2522clsxs3ow400013d5tag68uvix%2522%257D%252C%2522clsxs3ow500063d5tsdxj7c0g%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxs3ow500053d5t4sjwoe1w%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522id%2522%253A%2522clsxs3ow500063d5tsdxj7c0g%2522%252C%2522activeTabId%2522%253A%2522clsxs3ow500053d5t4sjwoe1w%2522%257D%252C%2522clsxs3ow500043d5tos3c04kt%2522%253A%257B%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clsxs3ow500033d5ts6uhp2bi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%255D%252C%2522id%2522%253A%2522clsxs3ow500043d5tos3c04kt%2522%252C%2522activeTabId%2522%253A%2522clsxs3ow500033d5ts6uhp2bi%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D), it uses react aria and radix, same styling.
2. Click on Open React aria dialog and select input at the bottom of the dialog and the keyboard will cover the input and it won't zoom correctly.
3. Try the same with Radix and it won't happen

### Version

3.32.1

### What browsers are you seeing the problem on?

Safari

### If other, please specify.

_No response_

### What operating system are you using?

iOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### LINKED ISSUE #7902: Issues with modal scrolling + focus on Safari
### Provide a general summary of the issue here

Forms in modal dialogs on iOS Safari continue to be a source of great pain. 😅 

### 🤔 Expected Behavior?

When focusing inputs, the dialog should be scrolled to center the input, and the modal overlay should be positioned correctly.

### 😯 Current Behavior

When focusing inputs, the focus jumps immediately, and the input being focused is not being centered; rather, it seems to scroll to the point where the top of the input is at the top of the dialog scroll container. Additionally, focusing inputs further down in the dialog seems to shift the modal overlay:

Image

See the attached video, this was done on the official React Aria site.

https://github.com/user-attachments/assets/8b4e6034-12a0-4af3-823f-7dbda6eadaf9

### 💁 Possible Solution

_No response_

### 🔦 Context

These issues make forms in dialogs a terrible experience for mobile Safari users.

### 🖥️ Steps to Reproduce

On the React Aria homepage, the `+` icon opens a dialog with a form. Tap on various fields to move the form around.

### Version

Latest as running on the official site

### What browsers are you seeing the problem on?

Safari

### If other, please specify.

_No response_

### What operating system are you using?

iOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### LINKED ISSUE #7972: iOS keyboard obscures input when focusing within a modal
### Provide a general summary of the issue here

https://github.com/user-attachments/assets/50b639f6-edbe-427a-90b7-abee968d48ac

### 🤔 Expected Behavior?

It should scroll city input into view similar to default iOS behavior.

### 😯 Current Behavior

It obscures city input.

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

- Goto https://react-spectrum.adobe.com/react-spectrum/Dialog.html.
- Focus the city input.
- Close the keyboard by tapping outside.
- Focus the input back.

### Version

Latest

### What browsers are you seeing the problem on?

Safari

### If other, please specify.

_No response_

### What operating system are you using?

iOS 18.3.2

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #7902, fixes #7972, fixes #5926

## iOS 26 viewport changes

iOS Safari 26 significantly changes how the visual viewport works due to the controls that now overlay on top of the page. `position: fixed` elements are clipped to the viewport below the status bar and above the address bar, but other content continues to scroll behind them. This means that the modal backdrop will not fill the entire visible viewport, which looks strange.

React Aria

To fix this, we can use `position: absolute` for the backdrop instead of `fixed`, and make it cover the entire page instead of just the visual viewport. The actual modal is still sized within the visual viewport. For trays, we add additional padding that extends behind the address bar so it looks seamless.

I also made `useViewportSize` update during the `blur` event instead of waiting for the `resize` event, which occurs after the keyboard animation is complete. This makes it feel a bit faster.

## usePreventScroll improvements

The usePreventScroll logic on iOS sometimes causes flickering when tapping on an input as we temporarily applied a transform to trick safari into not scrolling. Turns out we can avoid this by preemptively calling `relatedTarget.focus({preventScroll: true})` during the `blur` event, and then scrolling ourselves.

In iOS 26, we can also no longer apply `overscroll-behavior: contain` during the `touchstart` event, it must be applied before that. So now we inject a small `<style>` element to ensure this is applied everywhere while `usePreventScroll` is active.

I also improved the scroll into view logic so that it centers the input within the viewport, and smoothly animates into view just like the native implementation does (just without scrolling the entire page).

https://github.com/user-attachments/assets/fda6221a-78ba-47f1-ac32-0de4051cf7ee

### CODE REVIEW

File: packages/@react-spectrum/overlays/src/Underlay.tsx [hunk 1]
```diff
@@ -21,6 +21,14 @@ interface UnderlayProps {
 
 export function Underlay({isOpen, isTransparent, ...otherProps}: UnderlayProps): JSX.Element {
   return (
-    <div data-testid="underlay" {...otherProps} className={classNames(underlayStyles, 'spectrum-Underlay', {'is-open': isOpen, 'spectrum-Underlay--transparent': isTransparent})} />
+    <div
+      data-testid="underlay"
+      {...otherProps}
+      // Cover the entire document so iOS 26 Safari doesn't clip the underlay to the inner viewport.
+      style={{height: isOpen && typeof document !== 'undefined' ? document.body.clientHeight : undefined}}
```
Comment (devongovett) [inline packages/@react-spectrum/overlays/src/Underlay.tsx:28]: Assumes the clientHeight won't change much while a modal/tray is open. Otherwise we have to put a resize observer I guess, and that would be unfortunate...

File: packages/@react-spectrum/s2/src/Dialog.tsx [hunk 2]
```diff
@@ -57,10 +57,13 @@ const header = style({
...
   flexGrow: 1,
+  flexShrink: {
+    [`@container (height < ${500 / 16}rem)`]: 0
+  },
   overflowY: {
     default: 'auto',
-    // Make the whole dialog scroll rather than only the content when the height it small.
-    [`@media (height < ${400 / 16}rem)`]: 'visible'
+    // Make the whole dialog scroll rather than only the content when the height is small.
+    [`@container (height < ${500 / 16}rem)`]: 'visible'
```
Comment (devongovett) [inline packages/@react-spectrum/s2/src/Dialog.tsx:66]: Using container queries for this because when the keyboard opens the visual viewport resizes but the media query doesn't update.

File: packages/dev/s2-docs/src/Layout.tsx [hunk 3]
```diff
@@ -87,91 +87,98 @@ export function Layout(props: PageProps & {children: ReactElement<any>}) {
...
-                lg: '[calc(100vh - 72px)]'
-              },
-              overflow: {
-                lg: 'auto'
-              }
-            })}>
-            <article
+        <div
+          className={style({
+            isolation: 'isolate',
```
Comment (devongovett) [inline packages/dev/s2-docs/src/Layout.tsx:99]: new div to add isolation: isolate. This makes the sticky header appear behind dialogs.

File: packages/react-aria-components/docs/Modal.mdx [hunk 4]
```diff
@@ -101,12 +98,18 @@ import {DialogTrigger, Modal, Dialog, Button, Heading, TextField, Label, Input}
 }
 
 .react-aria-Modal {
+  position: fixed;
+  max-height: var(--visual-viewport-height);
+  top: calc(var(--visual-viewport-height) / 2);
+  left: 50%;
+  translate: -50% -50%;
```
Comment (devongovett) [inline packages/react-aria-components/docs/Modal.mdx:105]: Kind of a weird hack to center the modal without adding an extra div wrapper to the example...

File: packages/@adobe/spectrum-css-temp/components/tray/index.css [hunk 5]
```diff
@@ -20,14 +20,13 @@
 
 .spectrum-Tray-wrapper {
   inset-inline-start: 0;
-  /* Positioned at the top of the window */
-  position: fixed;
+  position: absolute;
```
Comment (snowystinger) [inline packages/@adobe/spectrum-css-temp/components/tray/index.css:23]: I guess people using the Portal Provider will need to update as they may have an offset parent

good thing we called it UNSAFE

File: packages/@react-aria/overlays/src/usePreventScroll.ts [hunk 6]
```diff
@@ -100,32 +87,32 @@ function preventScrollStandard() {
...
-    if (scrollable instanceof HTMLElement && window.getComputedStyle(scrollable).overscrollBehavior === 'auto') {
-      restoreScrollableStyles = setStyle(scrollable, 'overscrollBehavior', 'contain');
-    }
   };
 
+  // Prevent scrolling up when at the top and scrolling down when at the bottom
+  // of a nested scrollable area, otherwise mobile Safari will start scrolling
+  // the window instead.
+  // This must be applied before the touchstart event as of iOS 26, so inject it as a <style> element.
+  let style = document.createElement('style');
```
Comment (snowystinger) [inline packages/@react-aria/overlays/src/usePreventScroll.ts:107]: this can only exist once? or should we check for its preexistence before adding it? could add an id to find it

**Review by snowystinger — COMMENTED** [review]
I'm running into some buggy problems in https://reactspectrum.blob.core.windows.net/reactspectrum/4971777a6c845fb8eeadce7a21a96ac76eac44f8/docs/react-aria/index.html

Particularly when i tap in the Date Planted then try to open the date picker inside the create new dialog. Or try to use any of the other controls. I'm unsure what is an iOS 26 bug vs ours. Like the text cursor definitely seems like a Safari problem...

It's all so... floaty and see through, sometimes it just looks like a bug when it's probably how it's supposed to be... like that url bar that floats so high above the keyboard....

Image
Image

**Comment by jeffijoe** [comment]
@devongovett I tested it out on iOS 18.6.2, looks like there's still the issue with the overscrolling.


https://github.com/user-attachments/assets/ea1fee4e-50f2-4bfd-a0a3-1b6ca0dd972c

Thanks for working on this by the way! 🙏

File: packages/@react-aria/overlays/src/usePreventScroll.ts (hunk 6 above)
Comment (devongovett) [reply packages/@react-aria/overlays/src/usePreventScroll.ts:107]: we remove it in the cleanup function below.

**Comment by devongovett** [comment]
Thanks for testing.

@snowystinger yeah, the issue with the small address bar on top of the modal seems to be a Safari issue. It occurs specifically with inputs that have `autocorrect="off"`, which is why it doesn't happen for the "Scientific Name" field but does for the ComboBox and DatePicker. Safari seems to be calculating the position as if the autocorrect bar above the keyboard was there, and after the animation firing a second visual viewport resize (which is why it jumps a little). And the address bar just remains mis-positioned. Guessing that's why the cursor is also mis-positioned. Not sure there's much we can do there unfortunately. I'll see if a webkit bug got reported yet.

@jeffijoe looks like maybe the over scrolling happens when tapping on the whitespace in the date picker? If you tap on a segment itself it seems ok. I guess that's due to programmatic focus rather than the browser default tap behavior. I'll see if there's anything I can do about that.

**Comment by jeffijoe** [comment]
@devongovett the over-scrolling also happens for me in the current build when focusing any element (e.g.  just a regular input) that is near the bottom, if that helps.

File: packages/@adobe/spectrum-css-temp/components/tray/index.css (hunk 5 above)
Comment (devongovett) [reply packages/@adobe/spectrum-css-temp/components/tray/index.css:23]: hmm yeah. Not sure how we could handle that... I guess it would have been broken before as well if they had a containing block as a parent though.

**Comment by devongovett** [comment]
@jeffijoe Thanks. I added a commit to clamp the scroll position which should prevent that. I also tried to fix the programmatic scrolling issue when tapping the date field.

**Comment by jeffijoe** [comment]
@devongovett just tried the latest build and the modal example on the main site is so much better now! 🙏

**Comment by devongovett** [comment]
Ah, I found a way to fix the mis-positioned address bar issue too! Just needed to copy all the attributes that might affect the height of the keyboard (e.g. `autocorrect`, `inputMode`, etc.) over to the temporary input.

**Comment by devongovett** [comment]
I think I managed to remove the hidden input hack entirely? Turns out if you preemptively focus the real input with`{preventScroll: true}` it will disable Safari's default behavior. Does anyone still have iOS 18 or earlier versions to test this version?

**Comment by jeffijoe** [comment]
@devongovett I do! Here's a recording of the current behavior from the latest build. Looks like the scroll behavior has been fixed. The only issues I see:

* The image don't seem to allow navigating from the 2nd input to the 3rd dropdown
* The popovers (e.g. the calendar) are slower to adjust their positioning than the modal itself

I'm just happy the scroll and focus issues are resolved! 🙏  When do you think this will be released? 👀 

https://github.com/user-attachments/assets/d5cf5278-8795-4034-b182-c85c72805d6a

**Comment by devongovett** [comment]
Thanks! Yeah the up/down arrows only work with native inputs, not with our Select. We have a hidden input in there but seems like Safari requires it to be visible. Not sure there's much we can do about that unfortunately.

**Review by snowystinger — APPROVED** [review]
That is so much better!

**Review by LFDanLu — APPROVED** [review]
Behavior seems good on Android Chrome and desktop, approving for deeper testing on Monday. The Chromatic caught some strange behaviors that I'm actually unable to reproduce locally so I'd be fine accepting those as the new baselines if we discover that those are truly just chromatic specific.

**Comment by snowystinger** [comment]
Looks like there was an update or something, the cursor positioning issues I was seeing have been resolved. I also tested with some other Safari options and I did find another issue. Users can place the search bar at the top of the page from their Safari settings. So here's what that can look like on our docs site :-/

IMG_1967

IMG_1966

**Comment by jeffijoe** [comment]
That reminds me, how does it behave in embedded browsers like webviews in full-screen mobile apps?

**Comment by devongovett** [comment]
@snowystinger that doesn't seem to be a problem with modals? more of a docs issue.

**Comment by snowystinger** [comment]
> @snowystinger that doesn't seem to be a problem with modals? more of a docs issue.

yeah, I left it as approved for that reason

**Comment by jeffijoe** [comment]
@devongovett wanted to ask just in case you had any idea, but when embedding Stripe elements for credit cards, is there something I can do to make the calculations more accurate?


https://github.com/user-attachments/assets/1cb76eeb-c08c-4ad5-88c3-7b0a8edd7511

Sometimes it even gets as bad as this:

image

**Comment by devongovett** [comment]
With or without the changes? Did you try a nightly build for example?

**Comment by jeffijoe** [comment]
This is with the nightly build - forms with regular inputs work, it seems to happen only when focusing the Stripe elements
