### PR TITLE
fix(s2-docs): auto-scroll and expand section for group selected nav link

### LINKED ISSUE #9663: S2-docs: Internationalized section does not expand on its nested group link page load
### 🙋 Documentation Request

Hi, great library, thanks for all your work! I use `@internationalized/date` package a lot in my project and I bookmarked this page from the docs in my browser to have all the reference at hand: https://react-aria.adobe.com/internationalized/date/ZonedDateTime

However, each time I open that link, the sidebar scroll position stays at the very top, and to access other links nested below `Internationalized`, I have to scroll down + expand it each time, which is a bit inconvenient.

I found a quick fix I could implement for this, which I'll link a PR to shortly, and hopefully this will be a useful addition.

### 🧢 Your Company/Team

Habitrack

### PR DESCRIPTION
**Pull request by domhhv**
Closes #9663

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

Current behaviour (prod):

https://github.com/user-attachments/assets/081f72a7-f269-4978-b36f-44f19b0d1d1c

Ideal behaviour (this changeset):

https://github.com/user-attachments/assets/237d1b2b-758a-491f-ae1f-b4bf02bb8a6b

Summary of changes needed for this in `packages/dev/s2-docs/src/Nav.tsx`:
  1. Auto-expand disclosure when the current page's group, not only section, matches the nav section name                    
  2. Auto-scroll the selected SideNavLink into view on mount
  3. Add scrollMarginTop to prevent the link from being hidden behind the fixed header
  4. Add type annotation to linkRef to pass TypeScript checks

## 🧢 Your Project:

https://github.com/domhhv/habitrack

### CODE REVIEW

File: packages/dev/s2-docs/src/Nav.tsx [hunk 1]
```diff
@@ -255,10 +255,18 @@ export function SideNavItem(props) {
...
   let selected = useContext(SideNavContext);
   let {isExternal, ...linkProps} = props;
-  
+
+  useEffect(() => {
+    if (!linkRef.current || props.isSelected !== true) {
+      return;
+    }
+
+    linkRef.current.scrollIntoView({block: 'start', behavior: 'smooth'});
```
Comment (snowystinger) [inline packages/dev/s2-docs/src/Nav.tsx]: I think we'll want to use our `scrollIntoViewport` from `@react-aria/utils`

This way it'll only scroll into view if it's currently out of view and it'll fix some issues across browsers.

**Review by snowystinger — COMMENTED** [review]
Thanks for the PR, just a minor note

**Comment by snowystinger** [comment]
You'll also need to sign the CLA https://github.com/adobe/react-spectrum/blob/main/CONTRIBUTING.md#contributor-license-agreement

File: packages/dev/s2-docs/src/Nav.tsx (hunk 1 above)
Comment (domhhv) [reply packages/dev/s2-docs/src/Nav.tsx]: Makes sense, used that method, and added two non-required options to it in order to propagate the scrolling behavior and preserve the distance between the bottom edge of the screen and the link after scrolling, the way it behaves in the initial demo from this PR description.

I added sensible defaults everywhere to make these changes as non-intrusive as possible, but if needed, I can remove those opts and use the method as is, passing only the linkRef as the first arg.

File: packages/@react-aria/utils/src/scrollIntoView.ts [hunk 2]
```diff
@@ -32,7 +38,7 @@ interface ScrollIntoViewportOpts {
  * but doesn't affect parents above `scrollView`.
  */
 export function scrollIntoView(scrollView: HTMLElement, element: HTMLElement, opts: ScrollIntoViewOpts = {}): void {
-  let {block = 'nearest', inline = 'nearest'} = opts;
+  let {block = 'nearest', inline = 'nearest', behavior = 'auto'} = opts;
```
Comment (domhhv) [inline packages/@react-aria/utils/src/scrollIntoView.ts]: As per [specs](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#behavior), the default value of `behavior` is `auto`

File: packages/@react-aria/utils/src/scrollIntoView.ts [hunk 3]
```diff
@@ -140,27 +147,27 @@ export function scrollIntoViewport(targetElement: Element | null, opts: ScrollIn
...
+        targetElement.scrollIntoView?.({block, behavior});
       }
     } else {
       let {left: originalLeft, top: originalTop} = targetElement.getBoundingClientRect();
 
       // If scrolling is prevented, we don't want to scroll the body since it might move the overlay partially offscreen and the user can't scroll it back into view.
       let scrollParents = getScrollParents(targetElement, true);
       for (let scrollParent of scrollParents) {
-        scrollIntoView(scrollParent as HTMLElement, targetElement as HTMLElement);
+        scrollIntoView(scrollParent as HTMLElement, targetElement as HTMLElement, {block: opts.block || 'start', behavior});
```
Comment (domhhv) [inline packages/@react-aria/utils/src/scrollIntoView.ts]: As per [specs](https://developer.mozilla.org/en-US/docs/Web/API/Element/scrollIntoView#behavior), the default value of `block` is `start`. Since this call didn't have `block`, I short-circuited the `opts` object directly instead of using the `nearest` default value from the destructuring at the beginning of this function. I needed to provide the `block` value here as well to preserve the bottom padding after scrolling finishes.

File: packages/@react-aria/utils/src/scrollIntoView.ts [hunk 4]
```diff
@@ -140,27 +147,27 @@ export function scrollIntoViewport(targetElement: Element | null, opts: ScrollIn
...
       }
       let {left: newLeft, top: newTop} = targetElement.getBoundingClientRect();
       // Account for sub pixel differences from rounding
       if ((Math.abs(originalLeft - newLeft) > 1) || (Math.abs(originalTop - newTop) > 1)) {
         scrollParents = containingElement ? getScrollParents(containingElement, true) : [];
         for (let scrollParent of scrollParents) {
-          scrollIntoView(scrollParent as HTMLElement, containingElement as HTMLElement, {block: 'center', inline: 'center'});
+          scrollIntoView(scrollParent as HTMLElement, containingElement as HTMLElement, {block: opts.block || 'center', inline: 'center', behavior});
```
Comment (domhhv) [inline packages/@react-aria/utils/src/scrollIntoView.ts]: Same decision on short-circuiting: if `opts.block` is not provided (existing logic), then it passes the `{block: center}`, thus not breaking any existing functionality that depends on calling this function.

**Review by domhhv — COMMENTED** [review]
Thanks for taking the time to look at my PR! I signed the CLA and left a few comments about my decisions on defaults. If needed, I can revert the changes to the `scrollIntoView` and `scrollIntoViewport` signatures.

**Comment by domhhv** [comment]
Hey @snowystinger, just a friendly bump – LMK if you want me to change anything in this PR before merging.

**Comment by LFDanLu** [comment]
@snowystinger I don't recall anything specific tbh, I would guess that it was behaving poorly in other browsers perhaps?

**Comment by domhhv** [comment]
@snowystinger @LFDanLu Hey guys, thanks for looking into my PR! I've removed the `behavior` option since it wasn't as nice to have as the `block`. Happy to fix anything else before this can be merged!

**Review by snowystinger — DISMISSED** [review]

**Comment by snowystinger** [comment]
Apologies for the back and forth, the team decided to go back to the native scrolling api. I've updated the PR for you.
