### PR TITLE
fix(#3800): MobileSearchAutocomplete: focused style persists on blur

### LINKED ISSUE #3800: MobileSearchAutocomplete: focused style persists on blur
# 🐛 Bug Report 
With the MobileSearchAutocomplete, the focused style persists on blur.

## 🤔 Expected Behavior

Focused style should be removed on blur.

## 😯 Current Behavior

With the MobileSearchAutocomplete, the focused style persists on blur.

## 💁 Possible Solution

Reorder `focusProps` so that it comes after `buttonProps` at https://github.com/adobe/react-spectrum/blob/b35d5c02fe900badccd0cf1a8f23bb593419f238/packages/%40react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx#L230

## 🔦 Context

Recognized as an issue working on #3383, but can be reproduced using Storybook examples and the Responsive Design feature within Developer Tools.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  @react-spectrum/autocomplete@3.0.0-alpha.12
| Browser          | Chrome
| Operating System | macOS

## 🧢 Your Company/Team

Adobe/Accessibility

### LINKED ISSUE #3861: [react-aria] useTextField returns onBlur null instead of undefined
# 🐛 Bug Report 

I do not know if this is intentional or not, but I think there is an issue with the `useTextField` hook in `react-aria`.
All event handlers returned are set to `undefined` when not defined except `onBlur` which is returned as `null`.

At first, it does not seem worrying, but when it comes to `mergeProps` things become a little more spicy.
In fact, when you try to merge props coming from `react-aria` with props coming for on another library (`react-number-format` in my case) then `mergeProps` results in `onBlur` defined as `null` so when activated, it prompts an error in console.

`onBlur is not a function`

I do not know if it is a constraint in the library code but it would be great if `onBlur` was returned as `undefined`. Plus it makes more sense considering all other handlers work like that.

## 💻 Code Sample

https://codesandbox.io/s/condescending-parm-s6wufv?file=/src/App.tsx

## 🌍 Your Environment

MacOs
React 18.2
With and without Vite 4.0.1

### PR DESCRIPTION
**Pull request by majornista**
Closes #3800, Closes #3861

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue #3800](https://github.com/adobe/react-spectrum/issues/3800).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open https://reactspectrum.blob.core.windows.net/reactspectrum/e6d26f6dcd1b1755c95ac2cd19ceb083d123dbc1/storybook/index.html?path=/story/searchautocomplete--static
2. Open Developer Tools in web browser, and using the Responsive Design tools, select a breakpoint or device width that will render the SearchAutocomplete using the MobileSearchAutocomplete.
3. Verify that using Tab key to set focus to the MobileSearchAutocomplete renders the focus-ring style.
4. Pressing Tab again to blur the MobileSearchAutocomplete should remove the focus-ring style.

### CODE REVIEW

**Review by reidbarber — DISMISSED** [review]
LGTM

File: packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx [hunk 1]
```diff
@@ -227,7 +227,7 @@ const SearchAutocompleteButton = React.forwardRef(function SearchAutocompleteBut
 
   return (
     <div
-      {...mergeProps(hoverProps, focusProps, buttonProps)}
+      {...mergeProps(buttonProps, focusProps, hoverProps)}
```
Comment (LFDanLu) [inline packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx:230]: a bit odd that the order here actually mattered, will dig to see why. Ideally it shouldn't rely on the props merge order

Comment (snowystinger) [reply packages/@react-spectrum/autocomplete/src/MobileSearchAutocomplete.tsx:230]: funny enough, it's due to this line here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/interactions/src/useFocus.ts#L78, it should be `undefined`
the reason the order mattered with it though is due to how mergeProps works with event handler merging, if you pass null as an event handler, it will remove ALL event handlers of that name

https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/mergeProps.ts#L45 typeof null is 'object' so we won't go down this path
instead, we'll fall through here https://github.com/adobe/react-spectrum/blob/main/packages/%40react-aria/utils/src/mergeProps.ts#L66 and overwrite everything

I'm going to push the change to this branch

**Review by reidbarber — APPROVED** [review]

**Review by snowystinger — APPROVED** [review]
