### PR TITLE
observe the trigger and update the popup size

### LINKED ISSUE #1213: Picker Popup not showing if it got attached in the DOM as part of a DOM-Tree with "display: hidden"
# 🐛 Bug Report 

Attaching an Picker who is contained in an DOM-Tree who is "display: hidden" when added to the DOM fails to open the Picker Popup.

## 🤔 Expected Behavior

It does matter if the tree is hidden or not and the Picker Popup just opens

## 😯 Current Behavior

The Popup does not open appropriately (one just sees a thin line)

Bildschirmfoto 2020-10-30 um 12 18 03

## 💻 Code Sample

```typescript
function Bug() {
  const [state, setState] = useState(0);

  return (<div>
    <div style={{display: state % 2 === 0 ? 'block' : 'none'}}>
      <Picker label="Choose A">
        <Item key="rarely">A1</Item>
        <Item key="sometimes">A2</Item>
        <Item key="always">A3</Item>
      </Picker>
    </div>
    <div style={{display: /* state === 0 ||*/ state % 2 === 1 ? 'block' : 'none'}}>
      <Picker label="Choose B">
        <Item key="rarely">B1</Item>
        <Item key="sometimes">B2</Item>
        <Item key="always">B3</Item>
      </Picker>
    </div>
    <ActionButton onPress={() => setState(state + 1)}>Toggle</ActionButton>
  </div>);
}
```

Click Toggle and you should see something like shown in the screenshot above

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | master
| Browser          | FF / Chrome
| Operating System | OS-X

### PR DESCRIPTION
**Pull request by tomsontom**
Closes #1213

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Running the snippet in #1213 works - something I found a bit odd is that I had to memoize the dom-ref myself because `unwrapDOMRef` always returns a new instance. Would it make sense to provide an `useUnwrapDOMRef` in `@react-aria/utils`.

### CODE REVIEW

**Review by snowystinger — COMMENTED** [review]
Hey! Thanks for working on this. Would you mind including a story so we can test it out?
I'll get back to you on the useUnwrapDOMRef
Otherwise it looks really good

**Comment by tomsontom** [comment]
@snowystinger added slightly modified example

**Comment by tomsontom** [comment]
@snowystinger any time frame you can review those changes?

**Comment by snowystinger** [comment]
@tomsontom sorry about the delay and thanks for the reminder. I'll look at it asap.

File: packages/@react-spectrum/picker/src/Picker.tsx [hunk 1]
```diff
@@ -134,6 +134,20 @@ function Picker<T extends object>(props: SpectrumPickerProps<T>, ref: DOMRef<HTM
...
   }, [scale, isMobile, triggerRef, state.selectedKey]);
 
+  // Make sure we only unwrap if the trigger changes otherwise we'll retrigger
+  // the observer too often
+  let resizeRef = useMemo(() => unwrapDOMRef(triggerRef), [triggerRef]);
+
+  let onResize = useCallback(() => {
+    let width = triggerRef.current.UNSAFE_getDOMNode().offsetWidth;
+    setButtonWidth(width);
+  }, [triggerRef, setButtonWidth]);
```
Comment (snowystinger) [inline packages/@react-spectrum/picker/src/Picker.tsx:144]:
```suggestion
  let onResize = useCallback(() => {
    let width = resizeRef.current.offsetWidth;
    setButtonWidth(width);
  }, [resizeRef, setButtonWidth]);
```

**Review by snowystinger — COMMENTED** [review]
Thanks for adding the story, looks like it behaves well. Two general cleanup comments.
I think useUnwrapDomRef sounds reasonable, let's do it in a separate PR though so that the team can comment on it. I haven't had a chance to ask them about it yet and I don't want to hold up the work you've done here

File: packages/@react-spectrum/picker/src/Picker.tsx (hunk 1 above)
Comment (tomsontom) [reply packages/@react-spectrum/picker/src/Picker.tsx]: there are a few more lines where triggerRef is used and who could now use resizeRef but I did not change them do you think that would be a reasonable cleanup task for a follow up issue?

**Comment by tomsontom** [comment]
@snowystinger i filed #1313 to request the new useUnwrapDOMRef API. Once that API is approved and merged a I'll file a follow up issue to adapt picker to use it.

File: packages/@react-spectrum/picker/stories/Picker.stories.tsx [hunk 2]
```diff
@@ -531,14 +531,17 @@ function AsyncLoadingExample() {
...
+        <div style={{width: state ? '200px' : '300px'}}>
+          <Picker label="Choose A" UNSAFE_style={{width: '100%'}}>
+            <Item key="rarely">A1</Item>
+            <Item key="sometimes">A2</Item>
+            <Item key="always">A3</Item>
+          </Picker>
+        </div>
+        <ActionButton onPress={() => setState(!state)}>Toggle size</ActionButton>
+      </div>
+    </Flex>);
```
Comment (snowystinger) [inline packages/@react-spectrum/picker/stories/Picker.stories.tsx:546]: Almost, the Flex won't do anything though with a single child. Also, as much as possible, we want to the use the style props instead of unsafe style.
```suggestion
  return (
    <Flex direction="column" gap="size-200" alignItems="start">
        <div style={{width: state ? '200px' : '300px'}}>
          <Picker label="Choose A" width="100%">
            <Item key="rarely">A1</Item>
            <Item key="sometimes">A2</Item>
            <Item key="always">A3</Item>
          </Picker>
        </div>
        <ActionButton onPress={() => setState(!state)}>Toggle size</ActionButton>
    </Flex>
  );
```

**Review by snowystinger — APPROVED** [review]

**Comment by tomsontom** [comment]
@snowystinger sorry I should have tested the storybook change - sorry. Beside of that I saw you also updated the branch to the latest main-tip - just for future reference. Is this update required before the PR can get merged? Do you prefer to rebase or merge, or would you like to keep that to the committer who merges the PR?

File: packages/@react-spectrum/picker/src/Picker.tsx [hunk 3]
```diff
@@ -134,6 +134,20 @@ function Picker<T extends object>(props: SpectrumPickerProps<T>, ref: DOMRef<HTM
...
   }, [scale, isMobile, triggerRef, state.selectedKey]);
 
+  // Make sure we only unwrap if the trigger changes otherwise we'll retrigger
+  // the observer too often
+  let resizeRef = useMemo(() => unwrapDOMRef(triggerRef), [triggerRef]);
+
+  let onResize = useCallback(() => {
+    let width = resizeRef.current.offsetWidth;
+    setButtonWidth(width);
+  }, [resizeRef, setButtonWidth]);
```
Comment (LFDanLu) [inline packages/@react-spectrum/picker/src/Picker.tsx:144]: Got a nitpick (and I'm totally fine to have this go in as is) but what do you think about moving this code a couple lines up and then reusing `onResize` in the `useLayoutEffect` above? The code inside the useLayoutEffect is basically identical so would be nice to replace it.

Comment (tomsontom) [reply packages/@react-spectrum/picker/src/Picker.tsx:144]: I also noticed that but because I filed #1313 and I plan to revisit I wanted to keep the change focused on the bugfix. I just wanted to point out that beside the few lines above there's also `<HiddenSelect>` who uses the same unwrap-sequence, and other parts so probably this means that it could be the best thing to move that to the top?

Comment (LFDanLu) [reply packages/@react-spectrum/picker/src/Picker.tsx:144]: Yeah that seems like a good idea, I'll approve this pull then and that all can be done in a followup, thanks!

**Review by LFDanLu — APPROVED** [review]

**Comment by snowystinger** [comment]
@tomsontom don't worry about rebasing, i'll squash and merge now that we have two approvals

**Comment by tomsontom** [comment]
May I ask why those changes have not been included in the release that was done on December 22nd?

**Comment by snowystinger** [comment]
Hey, we didn't have enough time to do a complete testing of the release and we were focused on getting Slider out. This will be in our next release.
