### PR TITLE
Remove aria-modal usage due to Safari bug

### LINKED ISSUE #880: Popover focus shifts to 'dismiss' button before user can read the component's content
# 🐛 Bug Report 

I have an issue with how VoiceOver/Safari is interacting with react-spectrum v3 popovers. Focus seems to automatically/quickly move from the content of the popover to the “dismiss” button, and not much time is given to the user to process the popover content.

## 🤔 Expected Behavior

When the Popover is rendered, the screen reader should announce the Popover's content and not place focus on elements outside of that content.

## 😯 Current Behavior

Using OSX/Safari/VoiceOver:

When the Popover is opened, (visible) focus is moved to the hidden 'dismiss' button instead of the content.

image

## 💁 Possible Solution
NA

## 🔦 Context
This is an accessibility issue.

## 💻 Code Sample
NA

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.x
| Browser          | Safari
| Operating System | OSX
| Screen Reader | VoiceOver

## 🧢 Your Company/Team
Adobe/AEP

## 🕷 Tracking Issue (optional)
NA

### PR DESCRIPTION
**Pull request by devongovett**
Fixes #880.

This removes aria-modal usage from dialog due to https://bugs.webkit.org/show_bug.cgi?id=211934. This bug forces the first element to always receive focus inside a dialog in an iframe, regardless of which element we programmatically focus. Since we already use `aria-hidden` on surrounding elements, this should be safe to do.

### CODE REVIEW

File: packages/@react-aria/dialog/src/useDialog.ts [hunk 1]
```diff
@@ -52,13 +52,15 @@ export function useDialog(props: AriaDialogProps, ref: RefObject<HTMLElement>):
     }
   }, [ref]);
 
+  // We do not use aria-modal due to a Safari bug which forces the first focusable element to be focused
+  // on mount when inside an iframe, no matter which element we programmatically focus.
+  // See https://bugs.webkit.org/show_bug.cgi?id=211934.
```
Comment (majornista) [inline packages/@react-aria/dialog/src/useDialog.ts:57]: Should we mention that we are explicitly setting `aria-hidden` on siblings of the dialog, so that the Dialog still behaves as a modal?

**Comment by devongovett** [comment]
This appears to also be a problem on `main`, and doesn't seem to be fixed by #893 either unfortunately. Seems like a separate issue. I believe James reported it in RSP-1836.
