### PR TITLE
SearchAutocomplete: fix duplicate events

### LINKED ISSUE #3684: onKeyDown event on the SearchAutocomplete component is getting fired twice.
# 🐛 Bug Report 

onKeyDown event on the SearchAutocomplete component is getting fired twice.

## 🤔 Expected Behavior

onKeyDown event on the SearchAutocomplete component should get fired once.

## 😯 Current Behavior

onKeyDown event on the SearchAutocomplete component is getting fired twice.

## 💻 Code Sample

https://reactspectrum.blob.core.windows.net/reactspectrum/1b4d3af728d7eed74834601cc796ffb4ecd89966/docs/react-spectrum/SearchAutocomplete.html
https://codesandbox.io/s/jolly-moon-8ljsvy?file=/src/App.js

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |
| Browser          |
| Operating System |

## 🧢 Your Company/Team

 Adobe/Adobe Sign

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #3684

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/@react-aria/autocomplete/src/useSearchAutocomplete.ts [hunk 1]
```diff
@@ -55,7 +55,9 @@ export function useSearchAutocomplete<T>(props: AriaSearchAutocompleteOptions<T>
     listBoxRef,
     keyboardDelegate,
     onSubmit = () => {},
-    onClear
+    onClear,
+    onKeyDown,
+    onKeyUp
```
Comment (snowystinger) [inline packages/@react-aria/autocomplete/src/useSearchAutocomplete.ts:60]: do we need to worry about duplicates for any other events?
onInputChange
onFocusChange
onOpenChange

Comment (reidbarber) [reply packages/@react-aria/autocomplete/src/useSearchAutocomplete.ts:60]: We do need to fix `onFocusChange`. The other two are not used by useSearchField, so those are clear.

**Review by snowystinger — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
