### PR TITLE
[useButton & useToggleButton]: Add dynamic ref type depending on elementType props

### LINKED ISSUE #1172: Allow generic props to ButtonAria type
# 🐛 Bug Report 

## 🤔 Expected Behavior

Hello Adobe team ! 🖖 

I would like to use the `useButton` hook with the props `elementType` to create a button using other HTML markup than the `button` one.

I would like `buttonProps` to be typed depending on the `elementType` props I input.
If we take your exemple we may find [here on your documentation](https://react-spectrum.adobe.com/react-aria/useButton.html#custom-element-type), If `elementType` is `span` then `buttonProps` should have the type `ButtonHTMLAttributes<HTMLSpanElement>`

## 😯 Current Behavior

Using TypeScript, I would like to enforce the type of the ref depending on what `elementType` I use.
Actually `useButton` hook will always apply `ButtonHTMLAttributes<HTMLButtonElement>` to `buttonProps` which will always leads to TypeScript errors if we apply the ref on other HTML DOM node than a button.

## 💁 Possible Solution

`useButton` could accept a generic type which will be applied to `buttonProps` like this :
```typescript
import { AriaButtonProps, AriaToggleButtonProps } from "@react-types/button";
import { ButtonHTMLAttributes, RefObject } from "react";
import { ToggleState } from "@react-stately/toggle";
export interface ButtonAria<T> {
    /** Props for the button element. */
    buttonProps: ButtonHTMLAttributes<T>;
    /** Whether the button is currently pressed. */
    isPressed: boolean;
}
/**
 * Provides the behavior and accessibility implementation for a button component. Handles mouse, keyboard, and touch interactions,
 * focus behavior, and ARIA props for both native button elements and custom element types.
 * @param props - Props to be applied to the button.
 * @param ref - A ref to a DOM element for the button.
 */
export function useButton<T>(props: AriaButtonProps, ref: RefObject<HTMLElement>): ButtonAria<T>;
/**
 * Provides the behavior and accessibility implementation for a toggle button component.
 * ToggleButtons allow users to toggle a selection on or off, for example switching between two states or modes.
 */
export function useToggleButton<T>(props: AriaToggleButtonProps, state: ToggleState, ref: RefObject<HTMLElement>): ButtonAria<T>;

//# sourceMappingURL=types.d.ts.map
```

Another solution could be to apply the ref type dynamically corresponding to the `elementType` props.

## 🔦 Context

I would like to use React Aria among Framer Motion and generate a dynamic Button component with two variations possible based on this Union Type :

```typescript
interface StaticButton extends AriaButtonProps {
  variation: 'static'
  className?: string
  style?: React.CSSProperties
  elementType?: React.ElementType
}

interface MotionButton extends AriaButtonProps {
  variation: 'motion'
  className?: string
  style?: React.CSSProperties
  elementType: 'div'
  motionKey: string
  motionProps: MotionProps
}

type Props = StaticButton | MotionButton
```

The static one will return a simple button like this :
```typescript
<button {...buttonProps} ref={ref} className={props.className} style={props.style}>
  {props.children}
</button>
```

and the `motion` one will wrap a `div` button enhanced with React Aria which will be wrapped with Framer Motion :
```typescript
<motion.div
  {...buttonProps}
  ref={ref}
  className={props.className}
  style={props.style}
  key={props.motionKey}
  {...props.motionProps}
>
  {props.children}
</motion.div>
```
My case here is pretty simple as I need a `div` `elementType` in one case or a `button` in the other but could be more complicated on the case I want something dynamic depending on the `elementType` props input.

## 💻 Code Sample

```typescript
import React, { useRef } from 'react'
import { AriaButtonProps } from '@react-types/button'
import { useButton } from '@react-aria/button'
import { motion, MotionProps } from 'framer-motion'

interface StaticButton extends AriaButtonProps {
  variation: 'static'
  className?: string
  style?: React.CSSProperties
  elementType?: React.ElementType
}

interface MotionButton extends AriaButtonProps {
  variation: 'motion'
  className?: string
  style?: React.CSSProperties
  elementType: 'div'
  motionKey: string
  motionProps: MotionProps
}

type Props = StaticButton | MotionButton

const Button: React.FC<Props> = props => {
  const ref = useRef<HTMLElement | null>(null)
  const { buttonProps } = useButton(
    {
      ...props,
      elementType: props.variation === 'motion' ? 'div' : props.elementType,
    },
    ref
  )

  switch (props.variation) {
    case 'static': {
      // In this case buttonProps ref should be HTMLButtonElement in my case but should be dynamic depending on `props.elementType`
      return (
        <button {...buttonProps} ref={ref} className={props.className} style={props.style}>
          {props.children}
        </button>
      )
    }
    case 'motion': {
      // In this case buttonProps ref should be HTMLDivElement in my case but should be dynamic depending on `props.elementType`
      return (
        <motion.div
          {...buttonProps}
          ref={ref}
          className={props.className}
          style={props.style}
          key={props.motionKey}
          {...props.motionProps}
        >
          {props.children}
        </motion.div>
      )
    }
    default: {
      throw new Error(`Unexpected object: ${props as never}`)
      return null
    }
  }
}

Button.displayName = 'Button'

export default Button

```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| @react-aria/button  | 3.2.2
| Browser          | Google Chrome Canary Version 88.0.4294.0 (Build officiel) canary (x86_64)
| Operating System | Mac OS Catalina 10.15.7 (19H2)

## 🧢 Your Company/Team

Personal project

### PR DESCRIPTION
**Pull request by toinelin**
Closes #1172

Hello Adobe team 👋 
This is an implementation proposal to the types modification request in response to the following issue: #1172

I modified four files :
- `useButton` and `useToggleButton` hooks on which I added functions overloading (thanks to @devongovett advices) to dynamically modify the generic type passed to the returned `ButtonAria` depending on `elementType` props. I also modified the ref object generic type `HTMLElement` to match with the `elementType` one.
- button types in `@react-types/button`: changed `elementType` type from string to `React.ElementType` which may enforce typing to be sure `buttonProps` ref and `elementType` are corresponding to the HTML DOM element used.
- Button spectrum element for a small generic type update

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).

- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
--> Did not added testable code as my modifications are mainly related to types. Please tell me, otherwise, if it may need some.

- [x] Updated documentation (if it already exists for this component).
--> I assumed the props are automatically generated based on the component's props. If no, could you tell me where to update them on `docs:@react-aria/button` ? Also, I think restriction HTML types who would make sense to be used as a button should be notified on the documentation
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Create a button component :

```typescript
export function Button(props: AriaButtonProps) {
  const ref = React.useRef<HTMLDivElement | null>(null);
  const {buttonProps} = useButton(
    {
      ...props,
      elementType: 'div'
    },
    ref
  );
  return (
    <div {...buttonProps} ref={ref}>
      {props.children}
    </div>
  );
}
```

2. Change `useRef` type, `elementType` and HTML node to whatever you want
3. `buttonProps` type should be good

## 🧢 Your Project:

Personal project -> would like to use react-aria with custom components using Framer Motion which may be have different DOM element.

### CODE REVIEW

File: packages/@react-aria/button/src/useButton.ts [hunk 1]
```diff
@@ -31,7 +38,71 @@ export interface ButtonAria {
...
+function useButton(props: AriaButtonProps<'option'>, ref: RefObject<HTMLOptionElement>): ButtonAria<HTMLAttributes<HTMLOptionElement>>;
+function useButton(props: AriaButtonProps<'output'>, ref: RefObject<HTMLOutputElement>): ButtonAria<HTMLAttributes<HTMLOutputElement>>;
+function useButton(props: AriaButtonProps<'p'>, ref: RefObject<HTMLParagraphElement>): ButtonAria<HTMLAttributes<HTMLParagraphElement>>;
+function useButton(props: AriaButtonProps<'param'>, ref: RefObject<HTMLParamElement>): ButtonAria<HTMLAttributes<HTMLParamElement>>;
+function useButton(props: AriaButtonProps<'picture'>, ref: RefObject<HTMLPictureElement>): ButtonAria<HTMLAttributes<HTMLPictureElement>>;
+function useButton(props: AriaButtonProps<'pre'>, ref: RefObject<HTMLPreElement>): ButtonAria<HTMLAttributes<HTMLPreElement>>;
+function useButton(props: AriaButtonProps<'progress'>, ref: RefObject<HTMLProgressElement>): ButtonAria<HTMLAttributes<HTMLProgressElement>>;
+function useButton(props: AriaButtonProps<'script'>, ref: RefObject<HTMLScriptElement>): ButtonAria<HTMLAttributes<HTMLScriptElement>>;
```
Comment (snowystinger) [inline packages/@react-aria/button/src/useButton.ts:85]: is a script tag a valid place to spread button props?

**Review by snowystinger — COMMENTED** [review]
Thanks for getting this started!

File: packages/@react-aria/button/src/useButton.ts [hunk 2]
```diff
@@ -31,7 +38,62 @@ export interface ButtonAria {
...
+function useButton(props: AriaButtonProps<'template'>, ref: RefObject<HTMLTemplateElement>): ButtonAria<HTMLAttributes<HTMLTemplateElement>>;
+function useButton(props: AriaButtonProps<'textarea'>, ref: RefObject<HTMLTextAreaElement>): ButtonAria<HTMLAttributes<HTMLTextAreaElement>>;
+function useButton(props: AriaButtonProps<'tfoot'>, ref: RefObject<HTMLTableSectionElement>): ButtonAria<HTMLAttributes<HTMLTableSectionElement>>;
+function useButton(props: AriaButtonProps<'th'>, ref: RefObject<HTMLTableHeaderCellElement>): ButtonAria<HTMLAttributes<HTMLTableHeaderCellElement>>;
+function useButton(props: AriaButtonProps<'thead'>, ref: RefObject<HTMLTableSectionElement>): ButtonAria<HTMLAttributes<HTMLTableSectionElement>>;
+function useButton(props: AriaButtonProps<'time'>, ref: RefObject<HTMLTimeElement>): ButtonAria<HTMLAttributes<HTMLTimeElement>>;
+function useButton(props: AriaButtonProps<'title'>, ref: RefObject<HTMLTitleElement>): ButtonAria<HTMLAttributes<HTMLTitleElement>>;
+function useButton(props: AriaButtonProps<'ul'>, ref: RefObject<HTMLUListElement>): ButtonAria<HTMLAttributes<HTMLUListElement>>;
```
Comment (devongovett) [inline packages/@react-aria/button/src/useButton.ts:94]: I think we should probably restrict these to elements that would make sense as a button. Maybe `button`, `a`, `input`, `div` and `span`?

File: packages/@react-aria/button/src/useButton.ts [hunk 3]
```diff
@@ -31,7 +38,62 @@ export interface ButtonAria {
...
+function useButton(props: AriaButtonProps<ElementType>, ref: RefObject<HTMLElement>): ButtonAria<HTMLElement>;
```
Comment (devongovett) [inline packages/@react-aria/button/src/useButton.ts:95]: Should the return type be `ButtonAria<HTMLAttributes<HTMLElement>>`?

File: packages/@react-types/button/src/index.d.ts [hunk 4]
```diff
@@ -56,11 +51,17 @@ interface AriaBaseButtonProps extends FocusableDOMProps, AriaLabelingProps {
...
+   * @default 'button'
+   */
+  elementType?: T | JSXElementConstructor<any>
 }
 
-export interface AriaButtonProps extends ButtonProps, LinkButtonProps, AriaBaseButtonProps {}
-export interface AriaToggleButtonProps extends ToggleButtonProps, AriaBaseButtonProps {}
+export interface AriaButtonProps<T extends ElementType = 'button'> extends ButtonProps, LinkButtonProps, AriaBaseButtonProps<T> {}
+
+export interface AriaToggleButtonProps<T extends ElementType = 'button'> extends ToggleButtonProps, LinkButtonProps, AriaBaseButtonProps<T> {}
```
Comment (snowystinger) [inline packages/@react-types/button/src/index.d.ts:64]: We don't want Toggle Buttons to be link buttons, can you remove that change?

**Review by snowystinger — COMMENTED** [review]
@devongovett just a heads up that this will break our documentation
parcel-optimizer-ssg: Cannot read property 'description' of undefined

I think there will be two issues, 1) how is the duplicate function overload displayed in the props table, and 2) this should be an easy one, but move the eslint-disable's to surround the whole block of description + overloads, like so
```
 /* eslint-disable no-redeclare */
/**
 * Provides the behavior and accessibility implementation for a toggle button component.
 * ToggleButtons allow users to toggle a selection on or off, for example switching between two states or modes.
 */
function useToggleButton(props: AriaToggleButtonProps<'a'>, state: ToggleState, ref: RefObject<HTMLAnchorElement>): ButtonAria<AnchorHTMLAttributes<HTMLAnchorElement>>;
function useToggleButton(props: AriaToggleButtonProps<'button'>, state: ToggleState, ref: RefObject<HTMLButtonElement>): ButtonAria<ButtonHTMLAttributes<HTMLButtonElement>>;
function useToggleButton(props: AriaToggleButtonProps<'div'>, state: ToggleState, ref: RefObject<HTMLDivElement>): ButtonAria<HTMLAttributes<HTMLDivElement>>;
function useToggleButton(props: AriaToggleButtonProps<'input'>, state: ToggleState, ref: RefObject<HTMLInputElement>): ButtonAria<InputHTMLAttributes<HTMLInputElement>>;
function useToggleButton(props: AriaToggleButtonProps<'span'>, state: ToggleState, ref: RefObject<HTMLSpanElement>): ButtonAria<HTMLAttributes<HTMLSpanElement>>;
function useToggleButton(props: AriaToggleButtonProps<ElementType>, state: ToggleState, ref: RefObject<HTMLElement>): ButtonAria<HTMLAttributes<HTMLElement>>;
function useToggleButton(props: AriaToggleButtonProps<ElementType>, state: ToggleState, ref: RefObject<any>): ButtonAria<HTMLAttributes<any>> {
 /* eslint-enable no-redeclare */
```

**Comment by devongovett** [comment]
Is this PR ready to go? If so, you could mark it as ready for review. 😄

**Comment by devongovett** [comment]
Thanks @toinelin! I've updated this slightly to avoid adding `elementType` to all spectrum buttons, where it's currently unsupported, and keep this limited to `useButton` and `useToggleButton` for now. Hope you don't mind me pushing to your branch. 😄

**Comment by toinelin** [comment]
Good for me @devongovett , do whatever you want on my branch if needed ahah. Happy to help and hype to see my first open source contribution merged 🤩

**Review by devongovett — APPROVED** [review]
