### PR TITLE
fix Quiet TextArea dosen't resize issue

### LINKED ISSUE #885: Quiet TextArea doesn't resize according to value/defaultValue
# 🐛 Bug Report 

Quiet TextArea doesn't resize when given a large value/defaultValue.

## 🤔 Expected Behavior

TextArea should show the full content of the string given.

## 😯 Current Behavior

TextArea only shows about a line and a half. Manually modifying the content of the TextArea by typing into it makes it resize.

## 💁 Possible Solution

Resize the TextArea when the value changes, not just when typing.

## 🔦 Context

I'm making a subtitling tool using textareas, and the quiet ones look beautiful when I type them in, but bad/truncated when I load long subtitles into them.

## 💻 Code Sample

    function App() {
      return (<Provider theme={defaultTheme}>
        <TextArea isQuiet defaultValue={"foo ".repeat(300)}/>
      </Provider>)
    }

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 3.1.0
| Chrome | 84.0.4147.105 (Official Build) (64-bit)
| Windows | 10

### PR DESCRIPTION
**Pull request by zidian257**
Closes #885 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Since it's resolved using useEffect, the original test `quiet variant automatically adjusts its vertical height on change` is updated, and a new test `quiet variant automatically adjusts its vertical height on mount` is added.

Cases are added to storybook, they are `isQuiet, defaultValue`, and `isQuiet, value`

### CODE REVIEW

File: packages/@react-spectrum/textfield/src/TextArea.tsx [hunk 1]
```diff
@@ -25,22 +25,33 @@ function TextArea(props: SpectrumTextFieldProps, ref: RefObject<TextFieldRef>) {
...
 
   let inputRef = useRef<HTMLInputElement & HTMLTextAreaElement>();
+  let [count, check] = useState(0);
 
-  let onHeightChange = () => {
-    if (isQuiet) {
-      let input = inputRef.current;
-      input.style.height = 'auto';
-      input.style.height = `${input.scrollHeight}px`;
+  function changeDomHeight(dom: HTMLInputElement & HTMLTextAreaElement) {
```
Comment (snowystinger) [inline packages/@react-spectrum/textfield/src/TextArea.tsx:36]: while this will probably work, it would be better not to have an extra piece of state just to make renders
what if we did something more along these lines?
```
let onHeightChange = useCallback(() => {
  if (isQuiet) {
    let input = inputRef.current;
    input.style.height = 'auto';
    input.style.height = `${input.scrollHeight}px`;
  }
}, [isQuiet, inputRef]);

useEffect(() => {
    if (inputRef.current) {
      onHeightChange();
    }    
}, [onHeightChange]);

...

onChange: chain(onChange, onHeightChange)
```

File: packages/@react-spectrum/textfield/src/TextArea.tsx [hunk 2]
```diff
@@ -25,22 +25,33 @@ function TextArea(props: SpectrumTextFieldProps, ref: RefObject<TextFieldRef>) {
...
+    dom.style.height = 'auto';
+    dom.style.height = `${dom.scrollHeight}px`;
+  }
+
+  let onCheckHeight = () => check(x => x + 1);
+
+  useEffect(() => {
+    if (isQuiet && inputRef.current) {
+      if (!defaultValue && !value && count === 0) {
```
Comment (snowystinger) [inline packages/@react-spectrum/textfield/src/TextArea.tsx:45]: what is this check for? can there be a comment explaining it?

File: packages/@react-spectrum/textfield/test/TextArea.test.js [hunk 3]
```diff
@@ -47,11 +47,31 @@ describe('TextArea', () => {
     ${'v3 TextArea'}    | ${TextArea}      | ${{isQuiet: true, onChange}}
     ${'v2 TextArea'}    | ${V2TextArea}    | ${{quiet: true, onChange}}
   `('$Name quiet variant automatically adjusts its vertical height on change', ({Component, props}) => {
-    let tree = renderComponent(Component, props);
-    let input = tree.getByTestId(testId);
+    act(() => {
+      renderComponent(Component, props);
```
Comment (snowystinger) [inline packages/@react-spectrum/textfield/test/TextArea.test.js:51]: is the surrounding act because of the `onCheckHeight`? curious if this need would go away with the suggestion i made

File: packages/@react-spectrum/textfield/test/TextArea.test.js [hunk 4]
```diff
@@ -47,11 +47,31 @@ describe('TextArea', () => {
...
+    });
 
+    let input = screen.getByTestId(testId);
```
Comment (snowystinger) [inline packages/@react-spectrum/textfield/test/TextArea.test.js:54]: learned something new, hadn't seen screen before
is there a reason you are using it over the returned values from render?

**Comment by snowystinger** [comment]
Thanks for getting this started!!!

File: packages/@react-spectrum/textfield/src/TextArea.tsx (hunk 2 above)
Comment (zidian257) [reply packages/@react-spectrum/textfield/src/TextArea.tsx:45]: If we call `onHeightChange` on component mount, the test for `quiet variant automatically adjusts its vertical height on change`, which no `defaultValue` prop or `value` prop is passed to `TextArea` component, will be failed because the test logic is like, if no `defaultValue` prop or `value` prop is passed to `TextArea` then the DOM's height should be `''` after mounting .See [TextArea.test.js#L53](https://github.com/adobe/react-spectrum/blob/8560ae2a0a10fdd1e86b220282b3e0c06f795579/packages/%40react-spectrum/textfield/test/TextArea.test.js#L53).

So the check is for that: don't call `onHeightChange` on that situation. I'm not sure if I get this right 🤣 🤣

File: packages/@react-spectrum/textfield/src/TextArea.tsx (hunk 1 above)
Comment (zidian257) [reply packages/@react-spectrum/textfield/src/TextArea.tsx:36]: At first I was thinking the `change dom height based on scrollheight` thing could be used later somewhere else across the project, so I created a new state `count` and let `useEffect` monitor `count`, change `count` state whenever change event is dispatched. Doing so the logic will be seperated.

But yes I agree with you, this way no extra state is needed, I will make a commit later.

File: packages/@react-spectrum/textfield/test/TextArea.test.js (hunk 4 above)
Comment (zidian257) [reply packages/@react-spectrum/textfield/test/TextArea.test.js:54]: I will redo the test in the later commit and try to do it the right way 🤣 🤣

**Comment by zidian257** [comment]
Redid the test, not sure if I'm doing it right.. Thanks for the great review!

File: packages/@react-spectrum/textfield/src/TextArea.tsx [hunk 5]
```diff
@@ -25,18 +25,32 @@ function TextArea(props: SpectrumTextFieldProps, ref: RefObject<TextFieldRef>) {
...
       input.style.height = `${input.scrollHeight}px`;
     }
-  };
+  }, [isQuiet, inputRef]);
+
+  useEffect(() => {
+    if (inputRef.current) {
+      // if no value or defaultValue is passed
+      // no need to call onHeightChange
+      if (!value && !defaultValue) {
```
Comment (LFDanLu) [inline packages/@react-spectrum/textfield/src/TextArea.tsx:47]: Perhaps this if statement should be something along the lines of 
```suggestion
      if (!inputRef.current.value) {
```
instead? This would make `onHeightChange` properly fire for cases where a non-quiet TextArea with text within it is changed to quiet (in the current implementation it is isn't fired because `value` and `defaultValue` are undefined even if a user has typed text into the field).

Maybe this check could be removed entirely and the failing test is rewritten to something like:
```
    expect(input.style.height).toBe(`${mockScrollHeight}px`);
    Object.defineProperty(HTMLElement.prototype, 'scrollHeight', {configurable: true, value: 1000});
    fireEvent.change(input, {target: {value: '15', style: {}}});
    expect(input.style.height).toBe(`1000px`);
```
since we are really just testing that onHeightChange is fired when the input field receives a change event. What do you think @snowystinger ?

Comment (snowystinger) [reply packages/@react-spectrum/textfield/src/TextArea.tsx:47]: yeah, I don't think this is enough reason to add a full stately package... so `inputRef.current.value` is probably good to start. we can discuss further if need arises.
thanks for catching that case

**Comment by zidian257** [comment]
> @zidian257 Heya, I went ahead and applied the `inputRef.current.value` change, hope you don't mind. Lemme know what you think

No, I don't mind, that change is a great idea, thanks for helping out 😄
