### PR TITLE
Slider: Work around TalkBack not announcing the output element's text content

### LINKED ISSUE #1400: Slider/RangeSlider: TalkBack screen reader on Android fails to announce output text content
# 🐛 Bug Report 

TalkBack screen reader on Android fails to announce output text content.

## 🤔 Expected Behavior

Screen reader should always announce the value of the output element within the Slider/RangeSlider grouping.

## 😯 Current Behavior

Using TalkBack on Android, the Slider/RangeSlider grouping is only announced using the label referenced using `aria-labelledby`, ignoring the text content of the output tag. 

## 💁 Possible Solution

Add a self-referential IDREF to the `output` element's `aria-labelledby` attribute.

## 🔦 Context

Identified as an issue in Dec 17 release testing.

## 💻 Code Sample

```jsx
...
    outputProps: {
      htmlFor: state.values.map((_, index) => getSliderThumbId(state, index)).join(' '),
      id: outputId,
      'aria-labelledby': `${labelProps.id} ${outputId}`,
      'aria-live': 'off'
    }
...
```

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   | 2.21.0-beta.0
| Browser          | Chrome
| Operating System | Android with TalkBack enabled

## 🧢 Your Company/Team

Adobe/accessibility

### PR DESCRIPTION
**Pull request by majornista**
Closes #1400 

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue 1400](https://github.com/adobe/react-spectrum/issue/1400).
- [x] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [x] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

1. Open http://localhost:9003/iframe.html?id=slider--formatoptions-centimeter on Android device with TalkBack screen reader turned on.
2. Navigate to output element showing the current value of the Slider.
3. Output should announce as "Label 0 centimeters status"

## 🧢 Your Project:

Adobe/accessibility

### CODE REVIEW

File: packages/@react-aria/slider/src/useSlider.ts [hunk 1]
```diff
@@ -182,7 +184,8 @@ export function useSlider(
     }, moveProps),
     outputProps: {
       htmlFor: state.values.map((_, index) => getSliderThumbId(state, index)).join(' '),
-      'aria-labelledby': labelProps.id,
+      id: outputId,
+      'aria-labelledby': `${labelProps.id} ${outputId}`,
```
Comment (LFDanLu) [inline packages/@react-aria/slider/src/useSlider.ts:188]: Should there be logic here to handle if no label was passed in but an `aria-label` or `aria-labelledby` was provided in the props? I just noticed that the "Slider (hooks) -> with aria label stories" don't announce the label when moving the accessibility cursor to the output

would something like ``` 'aria-labelledby': `${labelProps.id || fieldProps.id} ${outputId}` ``` be appropriate?

**Review by LFDanLu — COMMENTED** [review]
Confirmed that navigating to the value label (output element) properly announces the text value in the slider/range slider centimeter story and in the slider hooks default, range, and three thumbs story

Just a single comment, lemme know what you think.

**Review by LFDanLu — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
