### PR TITLE
fix: React inert prop compatibility

### LINKED ISSUE #7502: [RAC] TabPanel `shouldForceMount` logs React error
### Provide a general summary of the issue here

Using `shouldForceMount` with `<TabPanel>` logs a React error.

### 🤔 Expected Behavior?

Using `shouldForceMount` should not log an error.

### 😯 Current Behavior

React logs the following error:

```
Received the string `true` for the boolean attribute `inert`. Although this works, it will not work as expected if you pass the string "false". Did you mean inert={true}?
```

https://github.com/facebook/react/blob/372ec00c0384cd2089651154ea7c67693ee3f2a5/packages/react-dom-bindings/src/shared/ReactDOMUnknownPropertyHook.js#L323

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://stackblitz.com/edit/stackblitz-starters-yvbwhznr?file=app%2FClient.tsx

```tsx
'use client';

import { Tabs, TabList, Tab, TabPanel } from 'react-aria-components';

export function Client() {
  return (
    <Tabs>
      <TabList aria-label="History of Ancient Rome">
        <Tab id="FoR">Founding of Rome</Tab>
        <Tab id="MaR">Monarchy and Republic</Tab>
        <Tab id="Emp">Empire</Tab>
      </TabList>
      <TabPanel id="FoR">
        Arma virumque cano, Troiae qui primus ab oris.
      </TabPanel>
      <TabPanel id="MaR" shouldForceMount>
        Senatus Populusque Romanus.
      </TabPanel>
      <TabPanel id="Emp">Alea jacta est.</TabPanel>
    </Tabs>
  );
}
```

### Version

react-aria-components@1.5.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

macOS 15.1.1

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by chirokas**
Closes #7502

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

File: packages/@react-aria/utils/src/inertValue.ts [hunk 1]
```diff
@@ -0,0 +1,9 @@
+import React from 'react';
+
+export function inertValue(value: any) {
+  if (typeof React['use'] === 'function') {
```
Comment (devongovett) [inline packages/@react-aria/utils/src/inertValue.ts:4]: I think we should check React.version here instead, just to avoid `use` being pulled in by tree shaking when it isn't needed.

File: packages/@react-aria/utils/src/inertValue.ts [hunk 2]
```diff
@@ -0,0 +1,11 @@
+import {version} from 'react';
+
+export function inertValue(value: any) {
```
Comment (snowystinger) [inline packages/@react-aria/utils/src/inertValue.ts:3]:
```suggestion
export function inertValue(value?: boolean) {
```

File: packages/@react-aria/utils/src/inertValue.ts [hunk 3]
```diff
@@ -0,0 +1,11 @@
...
+  const pieces = version.split('.');
+  const major = parseInt(pieces[0], 10);
+  if (major >= 19) {
+    return !!value;
```
Comment (snowystinger) [inline packages/@react-aria/utils/src/inertValue.ts:7]: once the arg is typed correctly, this will make more sense i think
```suggestion
    return value ?? undefined;
```

File: packages/@react-aria/utils/src/inertValue.ts [hunk 4]
```diff
@@ -0,0 +1,11 @@
...
+  }
+  // compatibility with React < 19
+  return value ? 'true' : undefined;
```
Comment (snowystinger) [inline packages/@react-aria/utils/src/inertValue.ts:10]: Should this line actually be this?
```suggestion
  if value == undefined {
    return undefined;
  }
  return value ? 'true' : 'false';
```

Comment (chirokas) [reply packages/@react-aria/utils/src/inertValue.ts:10]: Yes, this is also how we handled it before. See https://github.com/facebook/React/issues/17157 for more details about the behavior of the `inert` attribute in React < 19.

**Review by snowystinger — DISMISSED** [review]

**Review by snowystinger — APPROVED** [review]

**Review by yihuiliao — APPROVED** [review]
