### PR TITLE
Fix table keyboard navigation bugs

### LINKED ISSUE #1208: Table keyboard navigation bugs
# 🐛 Bug Report 

- [ ] When I tab out of Table many rows/columns, it does a page down. When I shift tab back into the table, it does another page down
- [ ] using Option Tab in /story/table--hideheader will take you through buttons, if you go through a few of them, and then hit the 'up arrow', it'll put focus back above where the last non-Option-tab stop was
- [x] ~~Nested Columns do not read correctly with NVDA - haven’t tested with other screen readers.~~ **(leave for a later ticket)**

Pending feedback:
- [ ] ~~It seems weird that that in row selection or cell selection, the enter/return key can toggle select, but when you select the check box you can't toggle it with return.~~

Suggestion from @majornista for the above: **Tied to the pending feed back above, won't handle at this time** 
- ~~Change row selection toggle to `Space` key only so that end users can customize `Enter` for other operations (e.g. opening an asset associated to the row, etc). This solves the consistency issue as well.~~

Won't do:
- [x] When there are nested columns, using the keyboard, I goto the second or last sub column, goto the parent, then back down to the sub column and I'm not at the first child, I'd expect to return to the child I entered from.

## 🧢 Your Company/Team

RSP

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #1208 

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

### CODE REVIEW

File: packages/@react-aria/grid/src/useGridCell.ts [hunk 1]
```diff
@@ -54,7 +56,20 @@ export function useGridCell<T, C extends GridCollection<T>>(props: GridCellProps
...
+      // since it respects visual tab order by default.
+      // Perhaps state.selectionManager.childFocusStrategy should default to "undef" in useMultipleSelectionState
+      // so that I can do a childFocusStategy != null check here so it doesn't override what the user sets?
+
+      // If the current active element is a focusable child within the cell, early return.
+      // This means that we've alt/option tab forward/backward into the cell and we should preserve the current
+      // focused child element.
+      if (document.activeElement !== ref.current && ref.current.contains(document.activeElement)) {
+        return;
+      }
```
Comment (LFDanLu) [inline packages/@react-aria/grid/src/useGridCell.ts:70]: Open question here. Not entirely sure what the desired behavior here is with childFocusStrategy, kinda feel like useMultipleSelectionState shouldn't have a default focus strategy, instead setting it to null similar to how useMenuTriggerState does it. Then I could check a child focus strategy exists and perform the early return if one doesn't, allowing shift+option+tab to follow the visual tab order (currently behaves this way w/o these fixes)

File: packages/@react-aria/selection/src/useSelectableCollection.ts [hunk 2]
```diff
@@ -280,7 +280,8 @@ export function useSelectableCollection(options: SelectableCollectionOptions): S
             } while (last);
 
             if (next && !next.contains(document.activeElement)) {
-              next.focus();
+              // Preserve the current scroll position since this will possibly focus an out of view element
+              focusWithoutScrolling(next);
```
Comment (LFDanLu) [inline packages/@react-aria/selection/src/useSelectableCollection.ts:284]: Fixes "When I tab out of Table many rows/columns, it does a page down."

File: packages/@react-aria/virtualizer/src/Virtualizer.tsx [hunk 3]
```diff
@@ -145,6 +145,17 @@ export function useVirtualizer<T extends object, V, W>(props: VirtualizerOptions
...
+      let focusedView = virtualizer.getView(focusedKey);
+      // Otherwise if we are re-entering the collection and there is a previously focused key that is out of view, scroll it into view
+      // If it is in view already, preserve the current scroll position via scrollTo. This is to prevent the shift-tabbing into the
+      // collection from scrolling the focused key out of view due to useSelectableCollection focusing the last element in the table when tabbing out of the collection
+      if (!focusedView) {
+        virtualizer.scrollToItem(focusedKey, {duration: 0});
+      } else {
+        let rect = virtualizer.getVisibleRect();
+        virtualizer.scrollTo(new Point(rect.x, rect.y), 0);
+      }
```
Comment (LFDanLu) [inline packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: Fixes "When I shift tab back into the table, it does another page down"

File: packages/@react-aria/grid/src/useGridCell.ts [hunk 4]
```diff
@@ -36,6 +36,8 @@ interface GridCellAria {
   gridCellProps: HTMLAttributes<HTMLElement>
 }
```
Comment (LFDanLu) [inline packages/@react-aria/grid/src/useGridCell.ts:38]: Changes in this file are for "using Option Tab in /story/table--hideheader will take you through buttons, if you go through a few of them, and then hit the 'up arrow', it'll put focus back above where the last non-Option-tab stop was"

File: packages/@react-aria/grid/src/useGridCell.ts [hunk 5]
```diff
@@ -175,6 +190,16 @@ export function useGridCell<T, C extends GridCollection<T>>(props: GridCellProps
...
+      case 'Tab':
+        // Track if focus is being moved around within the grid via alt/option + tab so we can update focusedKey
+        // when onFocus is called for the next focusable grid cell.
+        if (e.altKey) {
+          isAltTabEvent = true;
+          // Set the grid cell's tab index to -1 so that shift+alt/option+tab doesn't move focus from the focusable child
+          // to the grid cell. This would cause the child to then get refocused, effectively nullifying your shift+alt+tab action
+          ref.current.tabIndex = -1;
+        }
+        break;
```
Comment (LFDanLu) [inline packages/@react-aria/grid/src/useGridCell.ts:202]: Open to other ideas that don't need this `isAltTabEvent` tracker. Problem is that the keyboard delegate doesn't have a way of doing "nextFocusableKey" or "previousFocusableKey" so the approach used in useSelectableCollection is out.

File: packages/@react-aria/grid/src/useGridCell.ts [hunk 6]
```diff
@@ -175,6 +190,16 @@ export function useGridCell<T, C extends GridCollection<T>>(props: GridCellProps
...
+      case 'Tab':
+        // Track if focus is being moved around within the grid via alt/option + tab so we can update focusedKey
+        // when onFocus is called for the next focusable grid cell.
+        if (e.altKey) {
+          isAltTabEvent = true;
+          // Set the grid cell's tab index to -1 so that shift+alt/option+tab doesn't move focus from the focusable child
+          // to the grid cell. This would cause the child to then get refocused due to onFocus below, effectively nullifying your shift+alt+tab action
+          ref.current.tabIndex = -1;
+        }
+        break;
```
Comment (LFDanLu) [inline packages/@react-aria/grid/src/useGridCell.ts:202]: Open to other ideas that don't need this isAltTabEvent tracker. Problem is that the keyboard delegate doesn't have a way of doing "nextFocusableKey" or "previousFocusableKey" so the approach used in useSelectableCollection is out.

File: packages/@react-spectrum/table/test/Table.test.js [hunk 7]
```diff
@@ -1452,6 +1452,35 @@ describe('TableView', function () {
         let before = tree.getByTestId('before');
         expect(document.activeElement).toBe(before);
       });
+
```
Comment (LFDanLu) [inline packages/@react-spectrum/table/test/Table.test.js:1455]: Note: Wasn't able to write a test for the scroll position not changing when tabbing out/shift tabbing back into the Table. Tried a bunch of thing but couldn't get a test case that failed before the useSelectableCollection `focusWithoutScrolling` change

File: packages/@react-aria/virtualizer/src/Virtualizer.tsx (hunk 3 above)
Comment (devongovett) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: Is the root cause here that the focused key actually changes when tabbing out of the table due to focusing the last focusable item? Should we instead prevent this from happening?

File: packages/@react-aria/grid/src/useGridCell.ts (hunk 6 above)
Comment (devongovett) [reply packages/@react-aria/grid/src/useGridCell.ts:211]: This seems pretty weird to me. It only moves through the checkboxes, not the other focusable elements in the table (e.g. the cells). And it will have problems with virtualization too in case some items are not in the DOM, unless we try to reimplement it which seems like overkill. I would say we should not support this rather than trying to hack around it.

File: packages/@react-aria/virtualizer/src/Virtualizer.tsx (hunk 3 above)
Comment (LFDanLu) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: So the focused key actually doesn't change when tabbing out of the table because the last focusable item is actually a checkbox for a row that is out of view (useGridCell actually doesn't update the focusedKey in this case because we are in keyboard modality and useSelectableItem doesn't either because e.target isn't the cell itself).

The root cause of the weird scrolling behavior from shift tabbing into the table is because the browser is moving focus to the last focusable element in the table which is the out of view checkbox, causing the scroll...

Comment (LFDanLu) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: Tried a bunch of stuff but this still feels like the best solution since it fixes the following two cases:
- stopping the table from scrolling to the last checkbox when shift tabbing back into the table
- properly scrolling a item back into view when tabbing into the table

The second one can be reproduced by doing the following:
1. focus a cell in the table by clicking/tabbing into the table
2. using your mouse/touchpad, scroll the cell just out of view by scrolling down a little bit (make sure not to scroll so far that the cell is removed from the DOM)
3. click on an element outside of the table
4. tab back into the table

Without the above code, tabbing back into the table would focus the first focusable item, aka the column's select all checkbox which results in the focused cell in the table not being scrolled back into view

Comment (LFDanLu) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: An alternative would be to apply `excludeFromTabOrder` to the props returned by `useTableSelectionCheckbox` and `useTableSelectAllCheckbox` so that tabbing/shift-tabbing into the table moves focus to the previously focused cell that has tabindex=0.

Comment (LFDanLu) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: A possible solution that could replace the Virtualizer change here is perhaps something like this?
```
  useEffect(() => {
    let onKeyDown = (e) => {
      // The consts here can be removed if we export them from FocusScope
      const focusableElements = [
        'input:not([disabled]):not([type=hidden])',
        'select:not([disabled])',
        'textarea:not([disabled])',
        'button:not([disabled])',
        'a[href]',
        'area[href]',
        'summary',
        'iframe',
        'object',
        'embed',
        'audio[controls]',
        'video[controls]',
        '[contenteditable]'
      ];

      focusableElements.push('[tabindex]:not([tabindex="-1"]):not([disabled])');
      const TABBABLE_ELEMENT_SELECTOR = focusableElements.join(':not([hidden]):not([tabindex="-1"]),');

      if (e.key === 'Tab' && !ref.current.contains(e.target as HTMLElement)) {
        let tabbableElements = Array.from(document.querySelectorAll(TABBABLE_ELEMENT_SELECTOR));
        let index = tabbableElements.findIndex(node => node === e.target)
        let nodeToFocus;
        if (e.shiftKey) {
          nodeToFocus = tabbableElements[index - 1];
        } else {
          nodeToFocus = tabbableElements[index + 1];
        }

        if (ref.current.contains(nodeToFocus) && manager.focusedKey) {
          e.preventDefault();
          manager.setFocused(true);
          focusSafely(ref.current);
        }
      }
    }

    window.addEventListener('keydown', onKeyDown, true);
    return () => {
      window.removeEventListener('keydown', onKeyDown, true);
    }
  }, [])
```
Essentially we capture all keypresses that happen outside of the TableView. If we detect that the key press is Tab/Shift + Tab we then determine if focus would've shifted into the TableView and if so, prevent default behavior of the Tab key down so the browser doesn't shift the scroll position and then focus the TableView itself. The TableView then handles focusing the previously focused key itself via its existing useVirtualizer code (if selectedKey is out of view) or the useSelectableItem code (if selectedKey is already in view)

Comment (LFDanLu) [reply packages/@react-aria/virtualizer/src/Virtualizer.tsx:158]: Another idea is to mimic some of the code in `useSelectableList` used for scrolling the focusedKey into view: https://github.com/adobe/react-spectrum/blob/main/packages/@react-aria/selection/src/useSelectableList.ts#L114-L121. We could add similiar `scrollIntoView` in a capturing onFocus listener that detects when the focus is moved into the Table from outside. If so, then we bring the focused item into view but only if it isn't in view already and if `isVirtualized` is false. For the virtualized case, we keep the changes already made in this PR.

**Review by snowystinger — APPROVED** [review]
lgtm in chrome/safari/ff

**Review by ktabors — APPROVED** [review]
LGTM
I testing it maintaining its focused key and that option/alt-tab doesn't work when the user is within the table.
