### PR TITLE
fix: NumberField increment/decrement via Android TalkBack

### LINKED ISSUE #9406: NumberField: userEvent.click on increment/decrement in storybook does not work anymore
### Provide a general summary of the issue here

Since react-aria-components 1.14.0, my play functions in storybook does not work anymore.
If I click manually on increment/decrement buttons it works, but not with the userEvent.click function, the button are found but the value does not change

### 🤔 Expected Behavior?

As before, be able to test programmatically the number field increment and decrement using userEvent from storybook/test

### 😯 Current Behavior

The click on increment and decrement does nothing when userEvent.click is triggered

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

N/A

### Version

1.14.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

IOS / Ubuntu

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by chirokas**
Closes #9406

Fixes regressions introduced in #9012

https://github.com/adobe/react-spectrum/blob/5670b2accb4d40be8eb1b2c916a563a861de8ba3/packages/%40react-aria/interactions/src/usePress.ts#L537-L542

Since `onPressStart` and `onPressUp` are triggered synchronously, `setIsIncrementPressed(null)` immediately overwrites the previous state, so `onIncrement` is not triggered.

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

Test numberfield increment/decrement button with and without VO (on docs or storybook)

### CODE REVIEW

File: packages/@react-aria/spinbutton/src/useSpinButton.ts [hunk 1]
```diff
@@ -195,19 +189,23 @@ export function useSpinButton(
   let [isIncrementPressed, setIsIncrementPressed] = useState<'touch' | 'mouse' | null>(null);
   useEffect(() => {
     if (isIncrementPressed === 'touch') {
+      onIncrement?.();
       onIncrementPressStart(60);
```
Comment (chirokas) [inline packages/@react-aria/spinbutton/src/useSpinButton.ts]: same reasoning as the above

**Comment by snowystinger** [comment]
Hope you don't mind, pushed some updates while I was testing. I think there was an extraneous onIncrement/decrement, though it didn't seem to affect anything. Do you know where it came from? If needed, I was going to see about merging it with the onPressStart behaviour which already had that for non-touch, but removing it seemed more correct given the code comments.

**Comment by chirokas** [comment]
If I understand correctly, for touch users, we need to wait 600ms before triggering onIncrement/decrement, then start spinning.

Following this logic, the code should look like this:

```ts
_async.current = window.setTimeout(() => {
  onIncrement?.();
  setIsIncrementPressed('touch');
}, 600);
```

However, to ensure we always access the latest onIncrement/decrement from props (avoiding stale closure issues in setTimeout), I moved the call into useEffect.

```ts
useEffect(() => {
  if (isIncrementPressed === 'touch') {
    onIncrement?.();
    onIncrementPressStart(60);
  }
```

If we remove the onIncrement/decrement call from useEffect, the first trigger would occur at 600ms + 60ms = 660ms.

**Comment by snowystinger** [comment]
Ah, thanks, I see, this only affects the amount of time to start a spin. Not for a tap. And it's 60ms, so would be hard to notice manually.
However, I think we can simplify to help the two branches match each other a little more closely. I'll push the change. Thanks for explaining that, I'd missed that little detail.

**Review by yihuiliao — APPROVED** [review]
