### PR TITLE
Prevent resize error when DatePicker input ref is undefined

### LINKED ISSUE #3357: scrollWidth error in DatePicker
# 🐛 Bug Report 

I get an error when I use the `DatePicker` V3 and a `TagField` V2 inside of the `Dialog` after closing the dialog:

## 🤔 Expected Behavior

I shouldn't see an error.

## 😯 Current Behavior

I get the error below when I use the `DatePicker` V3 and a `TagField` V2 inside of the `Dialog` after closing the dialog:

Screen Shot 2022-07-28 at 10 08 31 AM

#### Reproduction Steps

- Have this kind of structure:

``` 
<Dialog>
<TagField>
<DatePicker>
</Dialog>
```
- Use the DatePicker
- Use the TagField
- Submit

https://user-images.githubusercontent.com/29243259/181639672-ff003d07-81ef-40cd-afa5-0d04b2af6f3e.mov

## 💁 Possible Solution

Add a null check on this line:
[https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/datepicker/src/Input.tsx#L42](https://github.com/adobe/react-spectrum/blob/main/packages/@react-spectrum/datepicker/src/Input.tsx#L42)

## 🔦 Context

This bug is blocking the release of a new feature.

## 💻 Code Sample

This code sandbox does not reproduce the error, but does give some context. 
[code sandbox](https://codesandbox.io/s/musing-ishizaka-brk5i3?file=/src/App.js)

The "Recipients" field is a V2 `TagField` component in the actual implementation.

## 🌍 Your Environment

| Software         | Version(s) |
| ---------------- | ---------- |
| react-spectrum   |  "3.19.0"
| Browser          | Chrome
| Operating System | MacOS Big Sur

## 🧢 Your Company/Team

Adobe/Marketo Engage

### PR DESCRIPTION
**Pull request by LFDanLu**
Closes #3357
## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 📝 Test Instructions:

Test that DatePicker and other Date components that use Input still work. Original issue couldn't be reproduced on our end but issue submitter confirmed applying a similar fix resolved the issue on their end

## 🧢 Your Project:

RSP

### CODE REVIEW

File: packages/@react-spectrum/datepicker/src/Input.tsx [hunk 1]
```diff
@@ -37,29 +37,32 @@ function Input(props, ref) {
   // not cause a layout shift.
   let [reservePadding, setReservePadding] = useValueEffect(false);
   let onResize = useCallback(() => setReservePadding(function *(reservePadding) {
-    if (reservePadding) {
-      // Try to collapse padding if the content is clipped.
-      if (inputRef.current.scrollWidth > inputRef.current.offsetWidth) {
-        let width = inputRef.current.parentElement.offsetWidth;
-        yield false;
+    if (inputRef.current) {
```
Comment (LFDanLu) [inline packages/@react-spectrum/datepicker/src/Input.tsx:40]: The diff is weird, this is just wrapping the old if statement in a inputRef.current check

Comment (LFDanLu) [inline packages/@react-spectrum/datepicker/src/Input.tsx:40]: The diff is weird, this is just wrapping the old if statement in a inputRef.current check

**Review by snowystinger — APPROVED** [review]
seems fine

**Review by devongovett — APPROVED** [review]
