### PR TITLE
fix(focus): add permisison element to focusable elements list

### LINKED ISSUE #8226: focusableElements selectors list doesn't include the new <permission /> element
### Provide a general summary of the issue here

the focusableElements selectors list (https://github.com/adobe/react-spectrum/blob/2e9061df69eb17f17b0fb7d64d318c2835aed145/packages/%40react-aria/utils/src/isFocusable.ts) doesn't include the new <permission /> element (https://github.com/WICG/PEPC/blob/main/explainer.md)

this is a new element introduced in Chrome, which acts as a button, and has role: button in the accessibility tree

### 🤔 Expected Behavior?

the permission element should be part of that list so that usages of <FocusScope /> and more would work with the new <permission /> element

### 😯 Current Behavior

it ain't part of the list, so when using <FocusScope /> it skips over the <permission /> element

### 💁 Possible Solution

add to list

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

https://codesandbox.io/p/sandbox/strange-monad-2zyz2p
must be on chrome, with the "Page embedded permission control (permission element)" flag enabled in chrome://flags

### Version

3.30.0

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

Mac

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by gabrielchl**
Closes #8226

## ✅ Pull Request Checklist:

- [x] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [x] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

## 📝 Test Instructions:

- change `contain={contain}` to `contain` at `packages/@react-aria/focus/stories/FocusScope.stories.tsx:61`
- add `<permission type="microphone"></permission>` to `packages/@react-aria/focus/stories/FocusScope.stories.tsx:66`
- in Chrome Beta, visit `http://localhost:9003/?path=/story/focusscope--keyboard-navigation-no-contain` and verify that the permission element can now be tabbed to and away from

## 🧢 Your Project:

before (when tab/shift-tab-ing, it skips over the permission element):
Untitled2

after (able to navigate to the permission element via keyboard, and activate the element):
Untitled1

### CODE REVIEW

**Review by reidbarber — APPROVED** [review]
Thanks!!

**Comment by reidbarber** [comment]
Looks like you'll need to [Sign the CLA](https://github.com/adobe/react-spectrum/pull/8356/checks?check_run_id=43616608473), then close and re-open this PR to trigger another build that passes.

**Review by reidbarber — APPROVED** [review]

**Comment by gabrielchl** [comment]
(could i get the 2nd approval plz? 🥺)

File: packages/@react-aria/utils/src/isFocusable.ts [hunk 1]
```diff
@@ -11,7 +11,8 @@ const focusableElements = [
   'embed',
   'audio[controls]',
   'video[controls]',
-  '[contenteditable]:not([contenteditable^="false"])'
+  '[contenteditable]:not([contenteditable^="false"])',
+  'permission'
```
Comment (snowystinger) [inline packages/@react-aria/utils/src/isFocusable.ts:15]: can a permission be disabled?

Comment (gabrielchl) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: i don't believe so, the spec (https://wicg.github.io/PEPC/permission-element.html) does not mention a way to achieve this

Comment (snowystinger) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: what happens to the programmatic focus call once this has happened?
> Once an element has a permanent blocker, it will be disabled permanently

will the focus call silently fail like it does for other disabled controls? or should users still be able to visit it?

Comment (gabrielchl) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: yeah so in the current chrome implementation, the button, when disabled by the browser, will still receive focus like normal
you can test with this in chrome beta:
```
<button>button 1</button>
<permission type="microphone" style="background: transparent"></permission>
<button>button 2</button>
```

Comment (snowystinger) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: I've opened Canary and enabled the setting in flags, clicking a permission doesn't do anything right now, so I can't tell if it's "blocked" or not regardless of the style. Am I missing something to get it to actually prompt? https://jsfiddle.net/dyjecvw9/1/

Comment (gabrielchl) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: ah take away the style to "un-disable" it
i used it to "toggle" between the disabled vs non-disabled behaviour

Comment (gabrielchl) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: ah looks like also it doesn't work in jsfiddle lmao
try this: https://codesandbox.io/p/sandbox/permission-focus-example-rnj4pr (once the cloudflare outage is over)

Comment (gabrielchl) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: mmmm my bad it doesn't work there either, you'll have it do it locally :<

Comment (snowystinger) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: haha, worried that might end up being the case, o well, one of us will try it when we have some time, thanks for the extra info

Comment (snowystinger) [reply packages/@react-aria/utils/src/isFocusable.ts:15]: Thanks again for the extra info and your patience, I was able to reproduce the behaviours in Chrome Canary with a local build

**Review by snowystinger — APPROVED** [review]
