### PR TITLE
Fix default color value in ColorPicker

### LINKED ISSUE #6363: ColorPicker goes transparant when no value is entered into ColorField
### Provide a general summary of the issue here

In your example documentation for building a Color Picker using a Color Area, Field, Swatch and Slider, if you delete the content in the Color Field so the the field is left blank and then blur the input the value gets automatically changed to "#000000", and the swatch changes to transparant in colour.

If you then try to move the slider or area selection around, the hex value is updated in the field component, but the swatch remains showing a transparant colour.

The only way to stop the swatch from being transparant is to type a value manually into the ColorField, which then causes it to update correctly.

### 🤔 Expected Behavior?

When the field value is set automatically to #000000 I would expect the swatch to be black not transparant, I would also expect the swatch to update correctly when the sliders are moved after such an action.

### 😯 Current Behavior

Color Picker incorrectly sets colour on swatch to transparant and then doesn't update correctly.

### 💁 Possible Solution

_No response_

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

Go to [https://react-spectrum.adobe.com/react-aria/ColorPicker.html](https://react-spectrum.adobe.com/react-aria/ColorPicker.html) and open the first example colour picker.

Delete the content in the colour field input and then try to change colour using the slider or colour area.

### Version

1.2.0 of aria-components

### What browsers are you seeing the problem on?

Chrome

### If other, please specify.

_No response_

### What operating system are you using?

MacOS

### 🧢 Your Company/Team

_No response_

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by reidbarber**
Closes #6363

## ✅ Pull Request Checklist:

- [ ] Included link to corresponding [React Spectrum GitHub Issue](https://github.com/adobe/react-spectrum/issues).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [ ] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/WAI/ARIA/apg/)

### CODE REVIEW

**Comment by devongovett** [comment]
I did do this on purpose. In Spectrum, we have a specific state for [no value](https://react-spectrum.adobe.com/react-spectrum/ColorSwatch.html#no-value) that gets shown. RAC users could also implement something like that with the render props. Open to discussing the default but just thought I'd mention.

**Comment by reidbarber** [comment]
@devongovett Maybe we can differentiate `null` and `undefined`? Or handle the default values of color swatch and color picker differently.

File: packages/@react-stately/color/src/useColorPickerState.ts [hunk 1]
```diff
@@ -15,13 +15,13 @@ export interface ColorPickerState {
 
 export function useColorPickerState(props: ColorPickerProps): ColorPickerState {
   let value = useColor(props.value);
-  let defaultValue = useColor(props.defaultValue || '#0000')!;
+  let defaultValue = useColor(props.defaultValue || '#000000')!;
   let [color, setColor] = useControlledState(value || undefined, defaultValue, props.onChange);
   
   return {
     color,
     setColor(color) {
```
Comment (LFDanLu) [inline packages/@react-stately/color/src/useColorPickerState.ts:23]: - add if check for null to early return in here
- update useColorSwatch so that color is required
- update docs (RSP/RAC/hooks)

File: packages/@react-spectrum/color/docs/ColorSwatch.mdx [hunk 2]
```diff
@@ -63,14 +63,6 @@ function Example() {
 }
 ```
 
-### No value
```
Comment (devongovett) [inline packages/@react-spectrum/color/docs/ColorSwatch.mdx:66]: So how do you get this state then? Pass in a transparent color? Should we have an example of that?

File: packages/@react-aria/color/src/useColorSwatch.ts [hunk 3]
```diff
@@ -21,7 +21,7 @@ import {useLocale, useLocalizedStringFormatter} from '@react-aria/i18n';
 
 export interface AriaColorSwatchProps extends AriaLabelingProps, DOMProps {
   /** The color value to display in the swatch. */
-  color?: string | Color | null,
+  color?: string | Color,
```
Comment (devongovett) [inline packages/@react-aria/color/src/useColorSwatch.ts:24]: Technically this can still be undefined so I guess we'd want it to be non-optional?

Comment (reidbarber) [reply packages/@react-aria/color/src/useColorSwatch.ts:24]: I started with that, but isn't there the case where RAC user's just want it to use the value from context?

File: packages/@react-spectrum/color/test/ColorField.test.js [hunk 4]
```diff
@@ -150,7 +150,7 @@ describe('ColorField', function () {
     // should call onChange when input is cleared
     expect(colorField.value).toBe('');
     expect(onChangeSpy).toHaveBeenCalledTimes(1);
-    expect(onChangeSpy).toHaveBeenCalledWith(null);
+    expect(onChangeSpy).toHaveBeenCalledWith(undefined);
```
Comment (snowystinger) [inline packages/@react-spectrum/color/test/ColorField.test.js:153]: won't this cause a problem because it will switch between controlled and uncontrolled?

**Review by ktabors — DISMISSED** [review]
This seems good. Just noticed some pre-existing stuff.

This is pre-existing, but if you zero out these fields we show NaN.
image
Also, pre-existing, if you delete a value from a RGB, HSL, or HSB ColorField the ColorPicker crashes. This seems more like part two of this fix.

File: packages/@react-stately/color/src/useColorPickerState.ts [hunk 5]
```diff
@@ -15,13 +15,15 @@ export interface ColorPickerState {
 
 export function useColorPickerState(props: ColorPickerProps): ColorPickerState {
   let value = useColor(props.value);
```
Comment (devongovett) [inline packages/@react-stately/color/src/useColorPickerState.ts:17]: We should remove `null` from the `ColorPickerProps` interface above as well.

**Review by devongovett — APPROVED** [review]

**Review by LFDanLu — APPROVED** [review]

**Review by ktabors — APPROVED** [review]
The ColorPicker and ColorField docs examples that were crashing are no longer crashing!!!!!
