### PR TITLE
#5621 [a11y] ResizableTableContainer: focused row obscured by table header with position: sticky

### LINKED ISSUE #5621: [a11y] ResizableTableContainer: focused row obscured by table header with position: sticky
### Provide a general summary of the issue here

When a table within a ResizableTableContainer is scrolled, and its `thead` has `position: sticky`, when a row receives focus, it can be obscured by the sticky header.

### 🤔 Expected Behavior?

Focused elements should not be obscured by other content. See https://www.w3.org/WAI/WCAG22/Understanding/focus-not-obscured-minimum

### 😯 Current Behavior

The RAC table example has a fixed header that can obscure focused content in the row, when the table is scrolled.

### 💁 Possible Solution

Use [`scroll-padding`](https://developer.mozilla.org/en-US/docs/Web/CSS/scroll-padding-top) to fix the issue with CSS, or with JavaScript, add a listener as follows:
```ts
// Ensure that the row containing focus is not obscured by a thead with position: sticky.
  const onFocusCapture = useCallback((e: React.FocusEvent<HTMLDivElement>) => {
    const target = e.target as HTMLElement;
    const {scrollTop, scrollLeft} = e.currentTarget;
    const row = target.tagName === 'TR' || target.getAttribute('role') === 'row' ? target : target.closest('tr, [role="row"]') as HTMLElement;
    const thead = target.closest('table, [role="grid"], [role="table"]').querySelector('thead, [role="rowgroup"]') as HTMLElement;
    const top = row.offsetTop - thead.offsetHeight;
    if (
      scrollTop > top &&
      getComputedStyle(thead).position === 'sticky'
    ) {
      e.currentTarget.scrollTo({
        top,
        left: scrollLeft,
        behavior: 'smooth'
      });
    }
  }, []);
```
to the `ResizableTableContainer` at https://github.com/adobe/react-spectrum/blob/main/packages/react-aria-components/src/Table.tsx#L211-L245

### 🔦 Context

_No response_

### 🖥️ Steps to Reproduce

Open https://react-spectrum.adobe.com/react-aria/

1. Navigate to the Example App
2. Scroll the Table 
3. Tab or use arrow keys to focus rows or cells within the table
4. Notice that focused content can become obscured by the sticky thead.

https://github.com/adobe/react-spectrum/assets/154077/67310457-05ef-4d4c-b641-b1e5fab5b1d3

### Version

RAC 1.0

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### If other, please specify.

_No response_

### What operating system are you using?

macOS

### 🧢 Your Company/Team

Adobe/Accessibility

### 🕷 Tracking Issue

_No response_

### PR DESCRIPTION
**Pull request by majornista**
Note that this commit includes both Tailwind CSS and Javascript solutions to the problem.

Closes #5621

## ✅ Pull Request Checklist:

- [X] Included link to corresponding [React Spectrum GitHub Issue 5621](https://github.com/adobe/react-spectrum/issue/5621).
- [ ] Added/updated unit tests and storybook for this change (for new code or code which already has tests).
- [ ] Filled out test instructions.
- [ ] Updated documentation (if it already exists for this component).
- [x] Looked at the Accessibility Practices for this feature - [Aria Practices](https://www.w3.org/TR/wai-aria-practices-1.1/)

## 🧢 Your Project:

Adobe/Accessibility

### CODE REVIEW

**Review by ktabors — APPROVED** [review]
Behaves well in Chrome on Desktop

**Comment by devongovett** [comment]
Do we need both solutions? I thought the CSS one would be enough. Or were you just demonstrating?

File: packages/react-aria-components/src/Table.tsx [hunk 1]
```diff
@@ -230,13 +230,62 @@ function ResizableTableContainer(props: ResizableTableContainerProps, ref: Forwa
...
+          }
+        }
+      });
+    }
+    return () => {
+      if (requestRef.current !== undefined) {
+        cancelAnimationFrame(requestRef.current);
+      }
+    };
+  }, [objectRef, isSticky, scrollPaddingTop]);
```
Comment (majornista) [inline packages/react-aria-components/src/Table.tsx:260]: > Do we need both solutions? I thought the CSS one would be enough. Or were you just demonstrating?
I think the javascript solution, or css added with javascript as done here, would be more robust. With users bringing their own CSS, I'm not sure we can count on them adding `scroll-padding` to the container when they add `sticky` to the `thead`, otherwise we would never have discovered this bug. We may not need the `onFocusCapture` fallback with adequate browser support for `scroll-padding`.

Comment (majornista) [reply packages/react-aria-components/src/Table.tsx:260]: Note: I removed `onFocusCapture` fallback.

Comment (devongovett) [reply packages/react-aria-components/src/Table.tsx:260]: Didn't realize this was in the component itself. I was thinking of just solving the immediate issue in the example. I'm not sure what the side effects of us adding scroll-padding automatically would be. If we did do that we'd probably want to do it somewhere deeper as this would affect more than just table (e.g. if you have sticky section headers in a menu or another collection).

Comment (majornista) [reply packages/react-aria-components/src/Table.tsx:260]: I can remove the change to the component itself and just make the change in the documentation example, but my concern about the potential for error with sticky still stands.

**Review by LFDanLu — APPROVED** [review]

**Review by ktabors — APPROVED** [review]

**Review by devongovett — APPROVED** [review]
